kv3_framework: pclUtilitys Class Reference
pclUtilitys Class Reference
#include "pclUtilitys.h"
Public Member Functions
pclUtilitys ()
~pclUtilitys ()
void createWallPlane (pcl::PointCloud< pcl::PointXYZRGB >::Ptr &out)
void setWallrelativeToOriginXY (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &out)
void getBiggestPlaneLocation (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointXYZ &out)
pcl::PointCloud< pcl::PointXYZRGB >::Ptr createAxis (float x, float y, float z)
void convertZPcl (pcl::PointCloud< pcl::PointXYZRGB > &in)
void setPclRGBColor (pcl::PointCloud< pcl::PointXYZRGB > &in, float r, float g, float b)
void mergeXYZRGBPcl (const pcl::PointCloud< pcl::PointXYZRGB > &in1, const pcl::PointCloud< pcl::PointXYZRGB > &in2, pcl::PointCloud< pcl::PointXYZRGB >::Ptr &out)
void mergeXYZPcl (const pcl::PointCloud< pcl::PointXYZ > &in1, const pcl::PointCloud< pcl::PointXYZ > &in2, pcl::PointCloud< pcl::PointXYZ >::Ptr &out)
void convertXYZBGRtoRGB (pcl::PointCloud< pcl::PointXYZRGB > &in)
void convertXYZRGBtoXYZ (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZ >::Ptr out)
void convertPtrXYZtoXYZRGB (const pcl::PointCloud< pcl::PointXYZ > &in, pcl::PointCloud< pcl::PointXYZRGB >::Ptr &out)
void convertPtrXYZRGBtoXYZ (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZ >::Ptr &out)
void convertXYZRGBtoXYZI (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZINormal >::Ptr out)
void convertXYZItoXYZRGB (const pcl::PointCloud< pcl::PointXYZINormal > &in, pcl::PointCloud< pcl::PointXYZRGB >::Ptr out)
void convertXYZRGBtoXYZRGBNormal (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGBNormal >::Ptr out)
void convertXYZRGBNormaltoXYZRGB (const pcl::PointCloud< pcl::PointXYZRGBNormal > &in, pcl::PointCloud< pcl::PointXYZRGB >::Ptr out)
void getNormalsFromCloud (const pcl::PointCloud< pcl::PointXYZ > &cloud, pcl::PointCloud< pcl::PointNormal > &normals)
void getNormalsFromCloudRgb (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::Normal > &normals)
void getNormalsXYZIFromCloud (const pcl::PointCloud< pcl::PointXYZ > &cloud, pcl::PointCloud< pcl::PointXYZINormal > &cloudOut)
void getNormalsXYZIFromCloudRgb (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::PointXYZINormal > &cloudOut)
void extractPlaneFromCloud (const pcl::PointCloud< pcl::PointXYZ > &cloud, pcl::PointCloud< pcl::PointXYZ > &cloudOut, bool bSegPlane)
void extractPlaneFromCloudRgb (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::PointXYZRGB > &cloudOut, bool bSegPlane)
void voxelGrid (const pcl::PointCloud< pcl::PointXYZ > &cloud, pcl::PointCloud< pcl::PointXYZ > &cloudOut, float distanceThreshold)
void voxelGridRgb (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::PointXYZRGB > &cloudOut, float distanceThreshold)
void passTroughFilter (const pcl::PointCloud< pcl::PointXYZ > &cloud, pcl::PointCloud< pcl::PointXYZ > &cloudOut, float minfl, float maxfl)
void passTroughFilterRgb (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::PointXYZRGB > &cloudOut, float minfl, float maxfl)
void statisticalOutlierRemovalFilter (const pcl::PointCloud< pcl::PointXYZ > &cloud, pcl::PointCloud< pcl::PointXYZ > &cloudOut, int numbersOfNeighbors, float deviationMul)
void statisticalOutlierRemovalFilterRgb (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::PointXYZRGB > &cloudOut, int numbersOfNeighbors, float deviationMul)
void radiusOutlierRemovalhelpFilter (const pcl::PointCloud< pcl::PointXYZ > &in, pcl::PointCloud< pcl::PointXYZ > &out, int mode, float radius, int numbersOfNeighbors)
void doConditionalEuclideanClusteringRgb (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::PointXYZRGB > &cloudOut)
void doEuclideanClustering (const pcl::PointCloud< pcl::PointXYZ > &cloud, pcl::PointCloud< pcl::PointXYZ > &out)
void doEuclideanClusteringRgb (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &out)
void testDoEuclideanClusteringRgb (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &out)
void movingLeastSquaresFilerRgb (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &cloudOut, int polyOrder, float radius)
void createRangeImageFromPcl (const pcl::PointCloud< pcl::PointXYZ > &cloud, pcl::RangeImage &rangeImage)
void doRegionGrowingSegmentationColor (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &out)
void doRegionGrowingSegmentation (const pcl::PointCloud< pcl::PointXYZ > &in, pcl::PointCloud< pcl::PointXYZRGB > &out)
void doCylinderSegmentationRgb (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &out)
void momentOfInertiaTest (const pcl::PointCloud< pcl::PointXYZ > &in, pcl::PointCloud< pcl::PointXYZ > &out)
void momentOfInertiaTestRgb (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &out)
void momentOfInertiaRgb (const pcl::PointCloud< pcl::PointXYZRGB > &in)
void testRandomSampleConsensus ()
void narfKeypointExtraction (const pcl::PointCloud< pcl::PointXYZ > &cloud, pcl::PointCloud< pcl::PointXYZ > &cloudOut)
void narfKeypointExtractionRgb (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::PointXYZRGB > &cloudOut)
void icpSimple (const pcl::PointCloud< pcl::PointXYZRGB > &in1, const pcl::PointCloud< pcl::PointXYZRGB > &in2, pcl::PointCloud< pcl::PointXYZRGB > &out)
void icpNormals (const pcl::PointCloud< pcl::PointXYZRGB > &in1, const pcl::PointCloud< pcl::PointXYZRGB > &in2, pcl::PointCloud< pcl::PointXYZRGB > &out)
void rotateX (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::PointXYZRGB > &cloudOut, float radiantAngle)
void rotateY (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::PointXYZRGB > &cloudOut, float radiantAngle)
void rotateZ (const pcl::PointCloud< pcl::PointXYZRGB > &cloud, pcl::PointCloud< pcl::PointXYZRGB > &cloudOut, float radiantAngle)
void translationXYZ (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &out, float x, float y, float z)
void keypointExtractionNARF (const pcl::PointCloud< pcl::PointXYZ > &in, pcl::PointCloud< pcl::PointXYZ > &out)
void keypointExtractionNARF (const pcl::PointCloud< pcl::PointXYZ > &in, pcl::PointCloud< pcl::PointWithScale > &out)
void keypointExtractionISS (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &out)
void keypointExtractionSIFT (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &out)
void keypointExtractionSIFT (const pcl::PointCloud< pcl::PointXYZ > &in, pcl::PointCloud< pcl::PointWithScale > &out)
void keypointExtractionSIFT (const pcl::PointCloud< pcl::PointXYZ > &in, pcl::PointCloud< pcl::PointNormal >::Ptr &normalCloud, pcl::PointCloud< pcl::PointWithScale > &out)
void keypointExtractionHarris (const pcl::PointCloud< pcl::PointXYZRGB > &in, pcl::PointCloud< pcl::PointXYZRGB > &out)
void FastPointFeatureHistogramsExample (const pcl::PointCloud< pcl::PointXYZRGB > &in1, const pcl::PointCloud< pcl::PointXYZRGB > &in2, pcl::PointCloud< pcl::PointXYZRGB > &out)
void extractFPFHfromKeypoints (const pcl::PointCloud< pcl::PointXYZ > &in1, const pcl::PointCloud< pcl::PointXYZ > &in2, const pcl::PointCloud< pcl::PointWithScale > &inKP1, const pcl::PointCloud< pcl::PointWithScale > &inKP2, const pcl::PointCloud< pcl::PointNormal > &inN1, const pcl::PointCloud< pcl::PointNormal > &inN2, pcl::PointCloud< pcl::PointXYZ > &out)
void extractFPFHfromKeypoints (const pcl::PointCloud< pcl::PointXYZ > &in1, const pcl::PointCloud< pcl::PointXYZ > &in2, const pcl::PointCloud< pcl::PointWithScale > &inKP1, const pcl::PointCloud< pcl::PointWithScale > &inKP2, const pcl::PointCloud< pcl::PointNormal > &inN1, const pcl::PointCloud< pcl::PointNormal > &inN2, Eigen::Matrix4f &tform)
void reconTwoPcl (const pcl::PointCloud< pcl::PointXYZ > &in1, const pcl::PointCloud< pcl::PointXYZ > &in2, Eigen::Matrix4f &tform)
pcl::visualization::PCLVisualizer::Ptr simpleVis (pcl::PointCloud< pcl::PointXYZ >::ConstPtr cloud)
pcl::visualization::PCLVisualizer::Ptr rgbVis (pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloud)
pcl::visualization::PCLVisualizer::Ptr rgbVisDouble (pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloud, pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloud2)
pcl::visualization::PCLVisualizer::Ptr normalsVis (pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloud, pcl::PointCloud< pcl::Normal >::ConstPtr normals)
pcl::visualization::PCLVisualizer::Ptr viewportsVis (pcl::PointCloud< pcl::PointXYZ >::ConstPtr cloud, pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloudRgb)
pcl::visualization::PCLVisualizer::Ptr viewportsDiffVisRgb (pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloud, pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloudRgb)
pcl::visualization::PCLVisualizer::Ptr viewportsDiffVis (pcl::PointCloud< pcl::PointXYZ >::ConstPtr cloud1, pcl::PointCloud< pcl::PointXYZ >::ConstPtr cloud2)
void setViewerPose (pcl::visualization::PCLVisualizer &viewer, const Eigen::Affine3f &viewer_pose)
Static Public Member Functions
static bool customRegionGrowing (const PointTypeFull &point_a, const PointTypeFull &point_b, float squared_distance)
Public Attributes
pcl::visualization::PCLVisualizer::Ptr viewer
Eigen::Matrix4f transM
Static Public Attributes
static int rootPclSize
static int rootPclRgbSize
static int rootPclResultSize
static int rootPclRgbResultSize
static pcl::RangeImage & range_image
static pcl::visualization::RangeImageVisualizer range_image_widget
static pcl::search::KdTree< pcl::PointXYZ >::Ptr tree_xyz
static pcl::search::KdTree< pcl::PointXYZRGB >::Ptr tree_xyzrgb
Private Member Functions
Eigen::Matrix4f computeInitialAlignment (const PointCloudPtr &source_points, const LocalDescriptorsPtr &source_descriptors, const PointCloudPtr &target_points, const LocalDescriptorsPtr &target_descriptors, float min_sample_distance, float max_correspondence_distance, int nr_iterations)
Eigen::Matrix4f refineAlignment (const ICPPointCloudPtr &source_points, const ICPPointCloudPtr &target_points, const Eigen::Matrix4f initial_alignment, float max_correspondence_distance, float outlier_rejection_threshold, float transformation_epsilon, float max_iterations)
void DetectSIFTKeypoints (PointCloud< PointXYZRGB >::Ptr &points, PointCloud< PointT >::Ptr &keypoints)
void DetectHarrisKeypoints (PointCloud< PointXYZRGB >::Ptr &points, PointCloud< PointXYZI >::Ptr &keypoints)
void DetectISSKeypoints (PointCloud< PointXYZRGB >::Ptr &points, PointCloud< PointXYZRGB >::Ptr &keypoints)
void DetectNARFKeypoints (PointCloud< PointXYZ >::Ptr &points, PointCloud< PointXYZ >::Ptr &keypoints)
pcl::PointCloud< pcl::FPFHSignature33 >::Ptr compute_fpfh_feature (pcl::PointCloud< pcl::PointXYZ > ::Ptr input_cloud, pcl::search::KdTree< pcl::PointXYZ >::Ptr tree)
Detailed Description
Definition at line 108 of file pclUtilitys.h.
Constructor & Destructor Documentation
pclUtilitys()
pclUtilitys::pclUtilitys ()
Definition at line 23 of file pclUtilitys.cpp.
{
 }
~pclUtilitys()
pclUtilitys::~pclUtilitys ()
Definition at line 26 of file pclUtilitys.cpp.
{
 }
Member Function Documentation
compute_fpfh_feature()
pcl::PointCloud< pcl::FPFHSignature33 >::Ptr pclUtilitys::compute_fpfh_feature (pcl::PointCloud< pcl::PointXYZ > ::Ptr input_cloud, pcl::search::KdTree< pcl::PointXYZ >::Ptr tree) private
DetectNARFKeypoints input:
Parameters
pcl::PointCloud<pcl::PointXYZ> ::Ptr input_cloud, pcl::search::KdTree<pcl::PointXYZ>::Ptr tree
Returns
pcl::PointCloud<pcl::FPFHSignature33>::Ptr
Definition at line 2990 of file pclUtilitys.cpp.
{
     pointnormal::Ptr point_normal(new pointnormal);
     pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> est_normal;
     est_normal.setInputCloud(input_cloud);
     est_normal.setSearchMethod(tree);
     est_normal.setKSearch(10);
     est_normal.compute(*point_normal);
     fpfhFeature::Ptr fpfh(new fpfhFeature);
     pcl::FPFHEstimationOMP<pcl::PointXYZ, pcl::Normal, pcl::FPFHSignature33> est_fpfh;
     est_fpfh.setNumberOfThreads(6);
     est_fpfh.setInputCloud(input_cloud);
     est_fpfh.setInputNormals(point_normal);
     est_fpfh.setSearchMethod(tree);
     est_fpfh.setKSearch(10);
     est_fpfh.compute(*fpfh);
     return fpfh;
 }
Referenced by FastPointFeatureHistogramsExample().
computeInitialAlignment()
Eigen::Matrix4f pclUtilitys::computeInitialAlignment (const PointCloudPtr & source_points, const LocalDescriptorsPtr & source_descriptors, const PointCloudPtr & target_points, const LocalDescriptorsPtr & target_descriptors, float min_sample_distance, float max_correspondence_distance, int nr_iterations) private
computeInitialAlignment input:
Parameters
const PointCloudPtr & source_points, const LocalDescriptorsPtr & source_descriptors, const PointCloudPtr & target_points, const LocalDescriptorsPtr & target_descriptors, float min_sample_distance, float max_correspondence_distance, int nr_iterations
Returns
Eigen::Matrix4f
Definition at line 2806 of file pclUtilitys.cpp.
 {
   pcl::SampleConsensusInitialAlignment<PointT, PointT, LocalDescriptorT> sac_ia;
   sac_ia.setMinSampleDistance (min_sample_distance);
   sac_ia.setMaxCorrespondenceDistance (max_correspondence_distance);
   sac_ia.setMaximumIterations (nr_iterations);
   sac_ia.setInputSource (source_points);
   sac_ia.setSourceFeatures (source_descriptors);
   sac_ia.setInputTarget (target_points);
   sac_ia.setTargetFeatures (target_descriptors);
   pcl::PointCloud<PointT> registration_output;
   sac_ia.align (registration_output);
   return (sac_ia.getFinalTransformation ());
 }
Referenced by extractFPFHfromKeypoints().
convertPtrXYZRGBtoXYZ()
void pclUtilitys::convertPtrXYZRGBtoXYZ (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZ >::Ptr & out)
convert color PCL to PCL without color input:
Parameters
pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 407 of file pclUtilitys.cpp.
{
     out->points.resize(in.size());
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         out->points[i].x = in.points[i].x;
         out->points[i].y = in.points[i].y;
         out->points[i].z = in.points[i].z;
         i++;
     }
 }
Referenced by setWallrelativeToOriginXY().
convertPtrXYZtoXYZRGB()
void pclUtilitys::convertPtrXYZtoXYZRGB (const pcl::PointCloud< pcl::PointXYZ > & in, pcl::PointCloud< pcl::PointXYZRGB >::Ptr & out)
convert PCL to PCL color (white) input:
Parameters
pcl::PointCloud<pcl::PointXYZ>& in output:
pcl::PointCloud<pcl::PointXYZRGB>::Ptr& out
Returns
void
Definition at line 428 of file pclUtilitys.cpp.
{
     out->points.resize(in.size());
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         out->points[i].x = in.points[i].x;
         out->points[i].y = in.points[i].y;
         out->points[i].z = in.points[i].z;
         out->points[i].r = 255;
         out->points[i].g = 255;
         out->points[i].b = 255;
         i++;
     }
 }
Referenced by setWallrelativeToOriginXY().
convertXYZBGRtoRGB()
void pclUtilitys::convertXYZBGRtoRGB (pcl::PointCloud< pcl::PointXYZRGB > & in)
convert PCL BGR to RGB input:
Parameters
pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& in
Returns
void
Definition at line 364 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr buffer (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::copyPointCloud(in, *buffer);
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         in.points[i].b = buffer->points[i].r;
         in.points[i].g = buffer->points[i].g;
         in.points[i].r = buffer->points[i].b;
         i++;
     }
 }
convertXYZItoXYZRGB()
void pclUtilitys::convertXYZItoXYZRGB (const pcl::PointCloud< pcl::PointXYZINormal > & in, pcl::PointCloud< pcl::PointXYZRGB >::Ptr out)
convert PCL no color with normal to PCL color input:
Parameters
const pcl::PointCloud<pcl::PointXYZINormal>& in output:
pcl::PointCloud<pcl::PointXYZRGB>::Ptr out
Returns
void
Definition at line 535 of file pclUtilitys.cpp.
{
     out->points.resize(in.size());
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         out->points[i].x = in.points[i].x;
         out->points[i].y = in.points[i].y;
         out->points[i].z = in.points[i].z;
         i++;
     }
 }
convertXYZRGBNormaltoXYZRGB()
void pclUtilitys::convertXYZRGBNormaltoXYZRGB (const pcl::PointCloud< pcl::PointXYZRGBNormal > & in, pcl::PointCloud< pcl::PointXYZRGB >::Ptr out)
convert color PCL with normal to PCL color input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGBNormal>& in output:
pcl::PointCloud<pcl::PointXYZRGB>::Ptr out
Returns
void
Definition at line 511 of file pclUtilitys.cpp.
{
     out->points.resize(in.size());
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         out->points[i].x = in.points[i].x;
         out->points[i].y = in.points[i].y;
         out->points[i].z = in.points[i].z;
         out->points[i].r = in.points[i].r;
         out->points[i].g = in.points[i].g;
         out->points[i].b = in.points[i].b;
         i++;
     }
 }
Referenced by icpNormals().
convertXYZRGBtoXYZ()
void pclUtilitys::convertXYZRGBtoXYZ (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZ >::Ptr out)
convert color PCL to PCL without color input:
Parameters
pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 386 of file pclUtilitys.cpp.
{
     out->points.resize(in.size());
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         out->points[i].x = in.points[i].x;
         out->points[i].y = in.points[i].y;
         out->points[i].z = in.points[i].z;
         i++;
     }
 }
Referenced by getNormalsFromCloudRgb(), pclApp::loadPlyTestPcl(), momentOfInertiaRgb(), and momentOfInertiaTestRgb().
convertXYZRGBtoXYZI()
void pclUtilitys::convertXYZRGBtoXYZI (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZINormal >::Ptr out)
convert color PCL to PCL without color with normal input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZINormal>::Ptr out
Returns
void
Definition at line 452 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::Normal>::Ptr normalAtWork (new pcl::PointCloud<pcl::Normal>);
     getNormalsFromCloudRgb(in, *normalAtWork);
     out->points.resize(in.size());
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         out->points[i].x = in.points[i].x;
         out->points[i].y = in.points[i].y;
         out->points[i].z = in.points[i].z;
         out->points[i].normal_x = normalAtWork->points[i].normal_x;
         out->points[i].normal_y = normalAtWork->points[i].normal_y;
         out->points[i].normal_z = normalAtWork->points[i].normal_z;
         i++;
     }
 }
References getNormalsFromCloudRgb().
Referenced by doConditionalEuclideanClusteringRgb().
convertXYZRGBtoXYZRGBNormal()
void pclUtilitys::convertXYZRGBtoXYZRGBNormal (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGBNormal >::Ptr out)
convert color PCL to PCL color with normal input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZINormal>::Ptr out
Returns
void
Definition at line 479 of file pclUtilitys.cpp.
{
     //pcl::PointCloud<pcl::PointXYZ>::Ptr cloudRgbIn (new pcl::PointCloud<pcl::PointXYZ>);
     //*cloudRgbIn = in;
     pcl::PointCloud<pcl::Normal>::Ptr normalAtWork (new pcl::PointCloud<pcl::Normal>);
     getNormalsFromCloudRgb(in, *normalAtWork);
     out->points.resize(in.size());
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         out->points[i].x = in.points[i].x;
         out->points[i].y = in.points[i].y;
         out->points[i].z = in.points[i].z;
         out->points[i].r = in.points[i].r;
         out->points[i].g = in.points[i].g;
         out->points[i].b = in.points[i].b;
         out->points[i].normal_x = normalAtWork->points[i].normal_x;
         out->points[i].normal_y = normalAtWork->points[i].normal_y;
         out->points[i].normal_z = normalAtWork->points[i].normal_z;
         i++;
     }
 }
References getNormalsFromCloudRgb().
Referenced by icpNormals().
convertZPcl()
void pclUtilitys::convertZPcl (pcl::PointCloud< pcl::PointXYZRGB > & in)
invert the z(depth) value input:
Parameters
pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& in
Returns
void
Definition at line 325 of file pclUtilitys.cpp.
{
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         float buffer = in.points[i].z;
         in.points[i].z = (float)(buffer * (-1.0));
         i++;
     }
 }
createAxis()
pcl::PointCloud< pcl::PointXYZRGB >::Ptr pclUtilitys::createAxis (float x, float y, float z)
draw axis PCL input:
Parameters
float x, float y, float z
Returns
pcl::PointCloud<pcl::PointXYZRGB>::Ptr
Definition at line 275 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr axisPcl (new pcl::PointCloud<pcl::PointXYZRGB>);
     float ix = x;
     float iy = y;
     float iz = z;
     float step = 0.01;
     int i=0;
     int imax=100;
     while(i<imax){
         pcl::PointXYZRGB axisPointX = pcl::PointXYZRGB(ix,y,z ,255,0,0);
         pcl::PointXYZRGB axisPointY = pcl::PointXYZRGB(x,iy,z ,0,255,0);
         pcl::PointXYZRGB axisPointZ = pcl::PointXYZRGB(x,y,iz ,0,0,255);
         axisPcl->push_back(axisPointX);
         ix = ix + step;
         axisPcl->push_back(axisPointY);
         iy = iy + step;
         axisPcl->push_back(axisPointZ);
         iz = iz + step;
     i++;
     }
     return(axisPcl);
 }
References z.
createRangeImageFromPcl()
void pclUtilitys::createRangeImageFromPcl (const pcl::PointCloud< pcl::PointXYZ > & cloud, pcl::RangeImage & rangeImage)
create Range Image from Pcl input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& cloud output:
pcl::RangeImage& rangeImage
Returns
void
pcl::RangeImage rangeImage;
Definition at line 1152 of file pclUtilitys.cpp.
{
      pcl::PointCloud<pcl::PointXYZ> pointCloud;
      pointCloud = cloud;
       //cout << "createRangeImageFromPcl " << endl;
       //cout << "Generate the data " << endl;
       /*
       // Generate the data
       for (float y=-0.5f; y<=0.5f; y+=0.01f) {
         for (float z=-0.5f; z<=0.5f; z+=0.01f) {
           pcl::PointXYZ point;
           point.x = 2.0f - y;
           point.y = y;
           point.z = z;
           pointCloud.push_back(point);
         }
       }
       pointCloud.width = pointCloud.size();
       pointCloud.height = 1;
       */
       //cout << "init " << endl;
       // We now want to create a range image from the above point cloud, with a 1deg angular resolution
       float angularResolution = (float) (  1.0f * (M_PI/180.0f));  //   1.0 degree in radians
       float maxAngleWidth     = (float) (360.0f * (M_PI/180.0f));  // 360.0 degree in radians
       float maxAngleHeight    = (float) (180.0f * (M_PI/180.0f));  // 180.0 degree in radians
       Eigen::Affine3f sensorPose = (Eigen::Affine3f)Eigen::Translation3f(0.0f, 0.0f, 0.0f);
       pcl::RangeImage::CoordinateFrame coordinate_frame = pcl::RangeImage::CAMERA_FRAME;
       float noiseLevel=0.00;
       float minRange = 0.0f;
       int borderSize = 1;
       //cout << "createFromPointCloud ... " << endl;
       rangeImage.createFromPointCloud(pointCloud, angularResolution, maxAngleWidth, maxAngleHeight,
                                       sensorPose, coordinate_frame, noiseLevel, minRange, borderSize);
       //cout << "Range image ... " << endl;
      // std::cout << rangeImage << "\n";
 }
createWallPlane()
void pclUtilitys::createWallPlane (pcl::PointCloud< pcl::PointXYZRGB >::Ptr & out)
set wall relative to detected origin XY input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 230 of file pclUtilitys.cpp.
{
     //pcl::PointCloud<pcl::PointXYZRGB>::Ptr wallPlane (new pcl::PointCloud<pcl::PointXYZRGB>);
     float step = 0.1;
     const float maxOverall = 10;
     float maxHalf = maxOverall * 0.5 * (-1);
     float ix = maxHalf*step;
     float iy = maxHalf*step;
     float iz = 0;
     int t=0;
     float tStep=0.5;
     int tmax=10;
     int i=0;
     int j=0;
     int imax=maxOverall;
     int jmax=maxOverall;
     t=0;
     while(t<tmax){
         iy = maxHalf*step;
         i=0;
         while(i<imax){
             ix = maxHalf*step;
             j=0;
             while(j<jmax){
                 pcl::PointXYZRGB bufferPoint = pcl::PointXYZRGB(ix, iy, iz, 0,255,0);
                 out->push_back(bufferPoint);
                 ix = ix + step;
                 j++;
             }
             iy = iy + step;
         i++;
         }
     iz = iz - tStep;
     t++;
     }//end tmax
 }
customRegionGrowing()
bool pclUtilitys::customRegionGrowing (const PointTypeFull & point_a, const PointTypeFull & point_b, float squared_distance) static
convert PCL no color with normal to PCL color input:
Parameters
const pcl::PointXYZINormal& point_a, const pcl::PointXYZINormal& point_b output:
float squared_distance
Returns
void
Definition at line 556 of file pclUtilitys.cpp.
 {
   Eigen::Map<const Eigen::Vector3f> point_a_normal = point_a.getNormalVector3fMap (), point_b_normal = point_b.getNormalVector3fMap ();
   if (squared_distance < 10000)
   {
     if (std::abs (point_a.intensity - point_b.intensity) < 8.0f)
       return (true);
     if (std::abs (point_a_normal.dot (point_b_normal)) < 0.06)
       return (true);
   }
   else
   {
     if (std::abs (point_a.intensity - point_b.intensity) < 3.0f)
       return (true);
   }
   return (false);
 }
DetectHarrisKeypoints()
void pclUtilitys::DetectHarrisKeypoints (PointCloud< PointXYZRGB >::Ptr & cloud, PointCloud< PointXYZI >::Ptr & keypoints) private
DetectHarrisKeypoints input:
Parameters
PointCloud<PointXYZRGB>::Ptr &cloud output:
PointCloud<PointXYZI>::Ptr &keypoints
Returns
void
Definition at line 2912 of file pclUtilitys.cpp.
 {
     float threshold = 0.0000001f;
     HarrisKeypoint3D<PointXYZRGB, PointXYZI> harrisDetect;
     harrisDetect.setNonMaxSupression(true);
     harrisDetect.setInputCloud(cloud);
     harrisDetect.setThreshold(threshold);
     harrisDetect.compute(*keypoints);
 }
DetectISSKeypoints()
void pclUtilitys::DetectISSKeypoints (PointCloud< PointXYZRGB >::Ptr & points, PointCloud< PointXYZRGB >::Ptr & keypoints) private
DetectISSKeypoints input:
Parameters
PointCloud<PointXYZRGB>::Ptr &cloud output:
PointCloud<PointXYZRGB>::Ptr &keypoints
Returns
void
Definition at line 2931 of file pclUtilitys.cpp.
 {
     double modelResolution = 0.001f;
     pcl::search::KdTree<pcl::PointXYZRGB>::Ptr kdTree(new pcl::search::KdTree<pcl::PointXYZRGB>());
     ISSKeypoint3D<pcl::PointXYZRGB, pcl::PointXYZRGB> issDetector;
     issDetector.setSearchMethod (kdTree);
     issDetector.setSalientRadius (6 * modelResolution);
     issDetector.setNonMaxRadius (4 * modelResolution);
     issDetector.setThreshold21 (0.9);
     issDetector.setThreshold32 (0.9);
     issDetector.setMinNeighbors (5);
     issDetector.setNumberOfThreads (4);
     issDetector.setInputCloud (cloud);
     issDetector.compute (*keypoints);
 }
Referenced by keypointExtractionISS().
DetectNARFKeypoints()
void pclUtilitys::DetectNARFKeypoints (PointCloud< PointXYZ >::Ptr & points, PointCloud< PointXYZ >::Ptr & keypoints) private
DetectNARFKeypoints input:
Parameters
PointCloud<PointXYZ>::Ptr &cloud output:
PointCloud<PointXYZ>::Ptr &keypoints
Returns
void
Definition at line 2957 of file pclUtilitys.cpp.
 {
     shared_ptr<RangeImage> rangeImage(new RangeImage);
     pcl::PointCloud<PointXYZ>& pointCloud = *cloud;
     Eigen::Affine3f sceneSensorPose = Eigen::Affine3f(Eigen::Translation3f(pointCloud.sensor_origin_[0], pointCloud.sensor_origin_[1], pointCloud.sensor_origin_[2]))*Eigen::Affine3f (pointCloud.sensor_orientation_);
     rangeImage->createFromPointCloud (pointCloud, pcl::deg2rad (0.5f), pcl::deg2rad (360.0f), pcl::deg2rad (180.0f), sceneSensorPose, pcl::RangeImage::CAMERA_FRAME, 0.0, 0.0f, 1);
     rangeImage->setUnseenToMaxRange();
     pcl::RangeImageBorderExtractor rangeImageBorderExtractor;
     pcl::NarfKeypoint narfKeypointDetector;
     narfKeypointDetector.setRangeImageBorderExtractor (&rangeImageBorderExtractor);
     narfKeypointDetector.setRangeImage (rangeImage.get());
     narfKeypointDetector.getParameters().support_size = 0.02f;
     narfKeypointDetector.setRadiusSearch(0.004);
     pcl::PointCloud<int> keypointIndices;
     narfKeypointDetector.compute (keypointIndices);
     keypoints->points.resize(keypointIndices.points.size());
     for (size_t i=0; i<keypointIndices.points.size(); ++i)
     {
         keypoints->points[i].getVector3fMap () = rangeImage->points[keypointIndices.points[i]].getVector3fMap();
     }
 }
Referenced by keypointExtractionNARF().
DetectSIFTKeypoints()
void pclUtilitys::DetectSIFTKeypoints (PointCloud< PointXYZRGB >::Ptr & cloud, PointCloud< PointT >::Ptr & keypoints) private
DetectSIFTKeypoints input:
Parameters
PointCloud<PointXYZRGB>::Ptr &cloud output:
PointCloud<PointT>::Ptr &keypoints
Returns
void
Definition at line 2868 of file pclUtilitys.cpp.
 {
     // Estimate the normals
     pcl::NormalEstimation<pcl::PointXYZRGB, pcl::PointNormal> normalEstimation;
     pcl::PointCloud<pcl::PointNormal>::Ptr normalCloud (new pcl::PointCloud<pcl::PointNormal>);
     pcl::search::KdTree<pcl::PointXYZRGB>::Ptr normalKdTree(new pcl::search::KdTree<pcl::PointXYZRGB>());
     normalEstimation.setInputCloud(cloud);
     normalEstimation.setSearchMethod(normalKdTree);
     normalEstimation.setRadiusSearch(0.05);
     normalEstimation.compute(*normalCloud);
     for(size_t i = 0; i<normalCloud->points.size(); ++i)
     {
         normalCloud->points[i].x = cloud->points[i].x;
         normalCloud->points[i].y = cloud->points[i].y;
         normalCloud->points[i].z = cloud->points[i].z;
     }
     float minScale = 0.001f;
     int nrOctaves = 3;
     int nrScalesPerOctave = 4;
     float minContrast = 0.0001f;
     pcl::SIFTKeypoint<pcl::PointNormal, pcl::PointWithScale> sift;
     //SIFTKeypoint<PointNormal, PointWithScale> sift;
     search::KdTree<PointNormal>::Ptr kdTree(new search::KdTree<PointNormal>());
     sift.setSearchMethod(kdTree);
     sift.setScales(minScale, nrOctaves, nrScalesPerOctave);
     sift.setMinimumContrast(minContrast);
     sift.setInputCloud(normalCloud);
     sift.compute(*keypoints);
 }
doConditionalEuclideanClusteringRgb()
void pclUtilitys::doConditionalEuclideanClusteringRgb (const pcl::PointCloud< pcl::PointXYZRGB > & cloud, pcl::PointCloud< pcl::PointXYZRGB > & cloudOut)
doConditionalEuclideanClusteringRgb input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& cloud output:
pcl::PointCloud<pcl::PointXYZRGB>& cloudOut
Returns
void
Definition at line 1090 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudFinalOut (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = cloud;
     pcl::copyPointCloud(*cloudIn, *cloudFinalOut);
     pcl::PointCloud<pcl::PointXYZINormal>::Ptr cloudNormals (new pcl::PointCloud<pcl::PointXYZINormal>);
     pcl::IndicesClustersPtr clusters (new pcl::IndicesClusters), small_clusters (new pcl::IndicesClusters), large_clusters (new pcl::IndicesClusters);
     pcl::PointCloud<pcl::PointXYZINormal>::Ptr clout (new pcl::PointCloud<pcl::PointXYZINormal>);
     convertXYZRGBtoXYZI(*cloudIn, clout);//copy in to out --- from PointXYZRGB to PointXYZI
     //pcl::copyPointCloud(*cloudIn, *clout);//copy in to out --- from PointXYZRGB to PointXYZI
     getNormalsXYZIFromCloudRgb(*cloudIn, *cloudNormals);
     std::vector<pcl::PointIndices> cluster_indices;
      pcl::ConditionalEuclideanClustering<pcl::PointXYZINormal> cec (true);
       cec.setInputCloud(cloudNormals);
       //cec.setConditionFunction(&pclUtilitys::customRegionGrowing);
       cec.setClusterTolerance (0.02);
       cec.setMinClusterSize (cloudNormals->size () / 1000);
       cec.setMaxClusterSize (cloudNormals->size () / 5);
       //cec.setMinClusterSize (60);
       //cec.setMaxClusterSize (8000);
       cec.segment (*clusters);
       cec.getRemovedClusters (small_clusters, large_clusters);
       cout << "doConditionalEuclideanClusteringRgb ... "<< endl;
       cout << "clusters size: " << clusters->size() << endl;
       cout << "small_clusters size: " << small_clusters->size() << endl;
       cout << "large_clusters size: " << large_clusters->size() << endl;
       /*
       // Using the intensity channel for lazy visualization of the output
       for (int i = 0; i < small_clusters->size (); ++i)
         for (int j = 0; j < (*small_clusters)[i].indices.size (); ++j)
           (*clout)[(*small_clusters)[i].indices[j]].intensity = -2.0;
       for (int i = 0; i < large_clusters->size (); ++i)
         for (int j = 0; j < (*large_clusters)[i].indices.size (); ++j)
           (*clout)[(*large_clusters)[i].indices[j]].intensity = +10.0;
       for (int i = 0; i < clusters->size (); ++i)
       {
         int label = rand () % 8;
         for (int j = 0; j < (*clusters)[i].indices.size (); ++j)
           (*clout)[(*clusters)[i].indices[j]].intensity = label;
       }
       */
      // convertXYZItoXYZRGB(*clout, cloudFinalOut);//copy in to out --- from PointXYZRGB to PointXYZI
      // cloudOut = *cloudFinalOut;//rgb
 }
References convertXYZRGBtoXYZI(), and getNormalsXYZIFromCloudRgb().
doCylinderSegmentationRgb()
void pclUtilitys::doCylinderSegmentationRgb (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
do Cylinder Segmentation Rgb input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 1873 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudRgbIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudRgbIn = in;
     pcl::PointCloud<PointXYZRGB>::Ptr cloud_cylinder (new pcl::PointCloud<PointXYZRGB> ());
     pcl::PointCloud<pcl::Normal>::Ptr cloud_normals (new pcl::PointCloud<pcl::Normal>);
     getNormalsFromCloudRgb(*cloudRgbIn, *cloud_normals);
     pcl::ModelCoefficients::Ptr coefficients_plane (new pcl::ModelCoefficients), coefficients_cylinder (new pcl::ModelCoefficients);
     pcl::PointIndices::Ptr inliers_plane (new pcl::PointIndices), inliers_cylinder (new pcl::PointIndices);
     pcl::ExtractIndices<PointXYZRGB> extract;
     pcl::ExtractIndices<pcl::Normal> extract_normals;
     pcl::SACSegmentationFromNormals<PointXYZRGB, pcl::Normal> seg;
     // Create the segmentation object for cylinder segmentation and set all the parameters
     seg.setOptimizeCoefficients (true);
     seg.setModelType (pcl::SACMODEL_CYLINDER);
     seg.setMethodType (pcl::SAC_RANSAC);
     seg.setNormalDistanceWeight (0.1);
     seg.setMaxIterations (5000);
     seg.setDistanceThreshold (0.05);
     seg.setRadiusLimits (0.2, 0.6);
     seg.setInputCloud (cloudRgbIn);
     seg.setInputNormals (cloud_normals);
     // Obtain the cylinder inliers and coefficients
     seg.segment (*inliers_cylinder, *coefficients_cylinder);
     std::cerr << "Cylinder coefficients: " << *coefficients_cylinder << std::endl;
     // Write the cylinder inliers to disk
     extract.setInputCloud (cloudRgbIn);
     extract.setIndices (inliers_cylinder);
     extract.setNegative (false);
     //pcl::PointCloud<PointT>::Ptr cloud_cylinder (new pcl::PointCloud<PointT> ());
     extract.filter (*cloud_cylinder);
     if (cloud_cylinder->points.empty ())
         std::cerr << "Can't find the cylindrical component." << std::endl;
     else{
         std::cerr << "PointCloud representing the cylindrical component: " << cloud_cylinder->size () << " data points." << std::endl;
         //writer.write ("table_scene_mug_stereo_textured_cylinder.pcd", *cloud_cylinder, false);
     }
     out = *cloud_cylinder;
 }
References getNormalsFromCloudRgb().
doEuclideanClustering()
void pclUtilitys::doEuclideanClustering (const pcl::PointCloud< pcl::PointXYZ > & in, pcl::PointCloud< pcl::PointXYZ > & out)
do euclidean clustering input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in output:
pcl::PointCloud<pcl::PointXYZ>& out
Returns
void
Definition at line 1511 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = in;
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_f (new pcl::PointCloud<pcl::PointXYZ>);
     // Creating the KdTree object for the search method of the extraction
     pcl::search::KdTree<pcl::PointXYZ>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZ>);
     tree->setInputCloud (cloudIn);
     //extracting
     std::vector<pcl::PointIndices> cluster_indices;
     pcl::EuclideanClusterExtraction<pcl::PointXYZ> ec;
     ec.setClusterTolerance (0.02);// 0.02 = 2cm
     ec.setMinClusterSize (60);
     ec.setMaxClusterSize (400);
     ec.setSearchMethod (tree);
     ec.setInputCloud (cloudIn);
     ec.extract (cluster_indices);
     //cout << "found clusters: " << cluster_indices.size() << endl;
     int comidx = 0;
     int idx=0;
     int idxmax=0;
     int i=0;
     int imax=cluster_indices.size();
     while(i<imax){
         idx=0;
         idxmax = cluster_indices[i].indices.size();
         //cout << "  clusters nr: " << i << " size: " << idxmax << endl;
         while(idx<idxmax){
             out.push_back((*cloudIn)[comidx]);
         idx++;
         comidx++;
         }
     i++;
     }
 }
doEuclideanClusteringRgb()
void pclUtilitys::doEuclideanClusteringRgb (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
do euclidean clustering with RGB cloud input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 1558 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = in;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud_f (new pcl::PointCloud<pcl::PointXYZRGB>);
     // Creating the KdTree object for the search method of the extraction
     pcl::search::KdTree<pcl::PointXYZRGB>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZRGB>);
     tree->setInputCloud (cloudIn);
     //extracting
     std::vector<pcl::PointIndices> cluster_indices;
     pcl::EuclideanClusterExtraction<pcl::PointXYZRGB> ec;
     ec.setClusterTolerance (0.02); // 0.02 = 2cm
     ec.setMinClusterSize (60);
     ec.setMaxClusterSize (600);
     ec.setSearchMethod (tree);
     ec.setInputCloud (cloudIn);
     ec.extract (cluster_indices);
     cout << "found clusters: " << cluster_indices.size() << endl;
     int comidx = 0;
     int idx=0;
     int idxmax=0;
     int i=0;
     int imax=cluster_indices.size();
     while(i<imax){
         idx=0;
         idxmax = cluster_indices[i].indices.size();
         cout << "  clusters nr: " << i << " size: " << idxmax << endl;
         while(idx<idxmax){
             out.push_back((*cloudIn)[comidx]);
         idx++;
         comidx++;
         }
     i++;
     }
 }
doRegionGrowingSegmentation()
void pclUtilitys::doRegionGrowingSegmentation (const pcl::PointCloud< pcl::PointXYZ > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
doRegionGrowingSegmentationColor with cloud without color input input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 1688 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = in;
     pcl::search::Search<pcl::PointXYZ>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZ>);
     pcl::PointCloud <pcl::Normal>::Ptr normals (new pcl::PointCloud <pcl::Normal>);
     pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> normal_estimator;
     normal_estimator.setSearchMethod (tree);
     normal_estimator.setInputCloud (cloudIn);
     normal_estimator.setKSearch (50);
     normal_estimator.compute (*normals);
     pcl::IndicesPtr indices (new std::vector <int>);
     pcl::removeNaNFromPointCloud(*cloudIn, *indices);
     pcl::RegionGrowing<pcl::PointXYZ, pcl::Normal> reg;
     reg.setMinClusterSize (50);
     reg.setMaxClusterSize (1000000);
     reg.setSearchMethod (tree);
     reg.setNumberOfNeighbours (30);
     reg.setInputCloud (cloudIn);
     reg.setIndices (indices);
     reg.setInputNormals (normals);
     reg.setSmoothnessThreshold (3.0 / 180.0 * M_PI);
     reg.setCurvatureThreshold (1.0);
     std::vector <pcl::PointIndices> clusters;
     reg.extract (clusters);
     pcl::PointCloud <pcl::PointXYZRGB>::Ptr colored_cloud = reg.getColoredCloud ();
     out = *colored_cloud;
 }
doRegionGrowingSegmentationColor()
void pclUtilitys::doRegionGrowingSegmentationColor (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
doRegionGrowingSegmentationColor with RGB cloud input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 1654 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = in;
     pcl::search::Search <pcl::PointXYZRGB>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZRGB>);
     pcl::IndicesPtr indices (new std::vector <int>);
     pcl::removeNaNFromPointCloud (*cloudIn, *indices);
     pcl::RegionGrowingRGB<pcl::PointXYZRGB> reg;
     reg.setInputCloud (cloudIn);
     reg.setIndices (indices);
     reg.setSearchMethod (tree);
     reg.setDistanceThreshold (0.08);
     reg.setPointColorThreshold (30);
     reg.setRegionColorThreshold (5);
     reg.setMinClusterSize (200);
     std::vector <pcl::PointIndices> clusters;
     reg.extract (clusters);
     cout << "doRegionGrowingSegmentation cluster size: " << clusters.size() << endl;
     pcl::PointCloud <pcl::PointXYZRGB>::Ptr colored_cloud = reg.getColoredCloud ();
     out = *colored_cloud;
 }
extractFPFHfromKeypoints() [1/2]
void pclUtilitys::extractFPFHfromKeypoints (const pcl::PointCloud< pcl::PointXYZ > & in1, const pcl::PointCloud< pcl::PointXYZ > & in2, const pcl::PointCloud< pcl::PointWithScale > & inKP1, const pcl::PointCloud< pcl::PointWithScale > & inKP2, const pcl::PointCloud< pcl::PointNormal > & inN1, const pcl::PointCloud< pcl::PointNormal > & inN2, Eigen::Matrix4f & tform)
extractFPFHfromKeypoints input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in1, const pcl::PointCloud<pcl::PointXYZ>& in2, const pcl::PointCloud<pcl::PointWithScale>& inKP1, const pcl::PointCloud<pcl::PointWithScale>& inKP2, const pcl::PointCloud<pcl::PointNormal>& inN1, const pcl::PointCloud<pcl::PointNormal>& inN2, output:
Eigen::Matrix4f& tform
Returns
void
Definition at line 2700 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr source_cloud_ptr (new pcl::PointCloud<pcl::PointXYZ>);
     *source_cloud_ptr = in1;
     pcl::PointCloud<pcl::PointXYZ>::Ptr target_cloud_ptr (new pcl::PointCloud<pcl::PointXYZ>);
     *target_cloud_ptr = in2;
     pcl::PointCloud<pcl::PointWithScale>::Ptr src_keypoints (new pcl::PointCloud<pcl::PointWithScale>);
     *src_keypoints = inKP1;
     pcl::PointCloud<pcl::PointWithScale>::Ptr tar_keypoints (new pcl::PointCloud<pcl::PointWithScale>);
     *tar_keypoints = inKP2;
     pcl::PointCloud<pcl::PointNormal>::Ptr src_normals_ptr (new pcl::PointCloud<pcl::PointNormal>);
     *src_normals_ptr = inN1;
     pcl::PointCloud<pcl::PointNormal>::Ptr tar_normals_ptr (new pcl::PointCloud<pcl::PointNormal>);
     *tar_normals_ptr = inN2;
   // Extract FPFH features from SIFT keypoints
   pcl::PointCloud<pcl::PointXYZ>::Ptr src_keypoints_xyz (new pcl::PointCloud<pcl::PointXYZ>);
   pcl::copyPointCloud (*src_keypoints, *src_keypoints_xyz);
   pcl::FPFHEstimation<pcl::PointXYZ, pcl::PointNormal, pcl::FPFHSignature33> fpfh;
   fpfh.setSearchSurface (source_cloud_ptr);
   fpfh.setInputCloud (src_keypoints_xyz);
   fpfh.setInputNormals (src_normals_ptr);
   fpfh.setSearchMethod (pclUtilitys::tree_xyz);
   pcl::PointCloud<pcl::FPFHSignature33>::Ptr src_features_ptr (new pcl::PointCloud<pcl::FPFHSignature33>());
   pcl::PointCloud<pcl::FPFHSignature33>& src_features = *src_features_ptr;
   fpfh.setRadiusSearch(0.05);
   fpfh.compute(src_features);
   cout << "Computed " << src_features.size() << " FPFH features for source cloud\n";
   pcl::PointCloud<pcl::PointXYZ>::Ptr tar_keypoints_xyz (new pcl::PointCloud<pcl::PointXYZ>);
   pcl::copyPointCloud (*tar_keypoints, *tar_keypoints_xyz);
   fpfh.setSearchSurface (target_cloud_ptr);
   fpfh.setInputCloud (tar_keypoints_xyz);
   fpfh.setInputNormals (tar_normals_ptr);
   pcl::PointCloud<pcl::FPFHSignature33>::Ptr tar_features_ptr (new pcl::PointCloud<pcl::FPFHSignature33>());
   pcl::PointCloud<pcl::FPFHSignature33>& tar_features = *tar_features_ptr;
   fpfh.compute(tar_features);
   cout << "Computed " << tar_features.size() << " FPFH features for target cloud\n";
   // Sample Consensus Initial Alignment parameters (explanation below)
 const float min_sample_dist = 0.02f;
 const float max_correspondence_dist = 0.041f;
 const int nr_iters = 500;
 // ICP parameters (explanation below)
 const float max_correspondence_distance = 0.10f;
 const float outlier_rejection_threshold = 0.041f;
 const float transformation_epsilon = 0;
 const int max_iterations = 200;
   // Compute the transformation matrix for alignment
   tform = computeInitialAlignment (src_keypoints, src_features_ptr, tar_keypoints,
           tar_features_ptr, min_sample_dist, max_correspondence_dist, nr_iters);
   /* Uncomment this code to run ICP */
   tform = refineAlignment (source_cloud_ptr, target_cloud_ptr, tform, max_correspondence_distance,
           outlier_rejection_threshold, transformation_epsilon, max_iterations);
 }
References computeInitialAlignment(), refineAlignment(), and tree_xyz.
extractFPFHfromKeypoints() [2/2]
void pclUtilitys::extractFPFHfromKeypoints (const pcl::PointCloud< pcl::PointXYZ > & in1, const pcl::PointCloud< pcl::PointXYZ > & in2, const pcl::PointCloud< pcl::PointWithScale > & inKP1, const pcl::PointCloud< pcl::PointWithScale > & inKP2, const pcl::PointCloud< pcl::PointNormal > & inN1, const pcl::PointCloud< pcl::PointNormal > & inN2, pcl::PointCloud< pcl::PointXYZ > & out)
extractFPFHfromKeypoints input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in1, const pcl::PointCloud<pcl::PointXYZ>& in2, const pcl::PointCloud<pcl::PointWithScale>& inKP1, const pcl::PointCloud<pcl::PointWithScale>& inKP2, const pcl::PointCloud<pcl::PointNormal>& inN1, const pcl::PointCloud<pcl::PointNormal>& inN2, output:
pcl::PointCloud<pcl::PointXYZ>& out
Returns
void
Definition at line 2621 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr source_cloud_ptr (new pcl::PointCloud<pcl::PointXYZ>);
     *source_cloud_ptr = in1;
     pcl::PointCloud<pcl::PointXYZ>::Ptr target_cloud_ptr (new pcl::PointCloud<pcl::PointXYZ>);
     *target_cloud_ptr = in2;
     pcl::PointCloud<pcl::PointWithScale>::Ptr src_keypoints (new pcl::PointCloud<pcl::PointWithScale>);
     *src_keypoints = inKP1;
     pcl::PointCloud<pcl::PointWithScale>::Ptr tar_keypoints (new pcl::PointCloud<pcl::PointWithScale>);
     *tar_keypoints = inKP2;
     pcl::PointCloud<pcl::PointNormal>::Ptr src_normals_ptr (new pcl::PointCloud<pcl::PointNormal>);
     *src_normals_ptr = inN1;
     pcl::PointCloud<pcl::PointNormal>::Ptr tar_normals_ptr (new pcl::PointCloud<pcl::PointNormal>);
     *tar_normals_ptr = inN2;
   // Extract FPFH features from SIFT keypoints
   pcl::PointCloud<pcl::PointXYZ>::Ptr src_keypoints_xyz (new pcl::PointCloud<pcl::PointXYZ>);
   pcl::copyPointCloud (*src_keypoints, *src_keypoints_xyz);
   pcl::FPFHEstimation<pcl::PointXYZ, pcl::PointNormal, pcl::FPFHSignature33> fpfh;
   fpfh.setSearchSurface (source_cloud_ptr);
   fpfh.setInputCloud (src_keypoints_xyz);
   fpfh.setInputNormals (src_normals_ptr);
   fpfh.setSearchMethod (pclUtilitys::tree_xyz);
   pcl::PointCloud<pcl::FPFHSignature33>::Ptr src_features_ptr (new pcl::PointCloud<pcl::FPFHSignature33>());
   pcl::PointCloud<pcl::FPFHSignature33>& src_features = *src_features_ptr;
   fpfh.setRadiusSearch(0.05);
   fpfh.compute(src_features);
   cout << "Computed " << src_features.size() << " FPFH features for source cloud\n";
   pcl::PointCloud<pcl::PointXYZ>::Ptr tar_keypoints_xyz (new pcl::PointCloud<pcl::PointXYZ>);
   pcl::copyPointCloud (*tar_keypoints, *tar_keypoints_xyz);
   fpfh.setSearchSurface (target_cloud_ptr);
   fpfh.setInputCloud (tar_keypoints_xyz);
   fpfh.setInputNormals (tar_normals_ptr);
   pcl::PointCloud<pcl::FPFHSignature33>::Ptr tar_features_ptr (new pcl::PointCloud<pcl::FPFHSignature33>());
   pcl::PointCloud<pcl::FPFHSignature33>& tar_features = *tar_features_ptr;
   fpfh.compute(tar_features);
   cout << "Computed " << tar_features.size() << " FPFH features for target cloud\n";
   // Sample Consensus Initial Alignment parameters
 const float min_sample_dist = 0.04f;
 const float max_correspondence_dist = 0.02f;
 const int nr_iters = 500;
 // ICP parameters
 const float max_correspondence_distance = 0.02f;
 const float outlier_rejection_threshold = 0.02f;
 const float transformation_epsilon = 0;
 const int max_iterations = 200;
   // Compute the transformation matrix for alignment
   Eigen::Matrix4f tform = Eigen::Matrix4f::Identity();
   tform = computeInitialAlignment (src_keypoints, src_features_ptr, tar_keypoints,
           tar_features_ptr, min_sample_dist, max_correspondence_dist, nr_iters);
   /* Uncomment this code to run ICP */
   tform = refineAlignment (source_cloud_ptr, target_cloud_ptr, tform, max_correspondence_distance,
           outlier_rejection_threshold, transformation_epsilon, max_iterations);
   //pcl::PointCloud<pcl::PointXYZ>::Ptr transformed_cloud_ptr (new pcl::PointCloud<pcl::PointXYZ>);
   //pcl::PointCloud<pcl::PointXYZ>& transformed_cloud = *transformed_cloud_ptr;
   pcl::transformPointCloud(in1, out, tform);
 }
References computeInitialAlignment(), refineAlignment(), and tree_xyz.
Referenced by reconTwoPcl().
extractPlaneFromCloud()
void pclUtilitys::extractPlaneFromCloud (const pcl::PointCloud< pcl::PointXYZ > & cloud, pcl::PointCloud< pcl::PointXYZ > & cloudOut, bool bSegPlane)
Definition at line 576 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = cloud;
     cout << "1 start: " << cloudIn->size() << endl;
     //SAC plane segmentation
     pcl::ModelCoefficients::Ptr coefficients (new pcl::ModelCoefficients);
     pcl::PointIndices::Ptr inliers (new pcl::PointIndices);
     pcl::SACSegmentation<pcl::PointXYZ> seg;
     seg.setOptimizeCoefficients (true);// Optional
     cout << "2 start: " << cloudIn->size() << endl;
     // Mandatory
     seg.setModelType (pcl::SACMODEL_PLANE);// pcl::SACMODEL_NORMAL_PLANE //SACMODEL_PLANE // SACMODEL_PERPENDICULAR_PLANE
     seg.setMethodType (pcl::SAC_RANSAC); // pcl::SAC_RANSAC
     seg.setDistanceThreshold (0.20);
     seg.setInputCloud(cloudIn);
     cout << " ------ " << endl;
     seg.segment (*inliers, *coefficients);
     if (inliers->indices.size () == 0){
         cout << "Could not estimate a planar model for the given dataset" << endl;
     }else{
         cout << "Inliers: " << inliers->indices.size() << endl;
     }
 /*
     // Extract the inliers - no rgb
     pcl::ExtractIndices<pcl::PointXYZ> extract;
     extract.setInputCloud(cloudIn);
     extract.setIndices (inliers);
     extract.setNegative (bSegPlane);
     cout << " start: " << cloudIn->size() << endl;
     extract.filter(*cloudOutTemp);
     cout << " End: " << cloudOutTemp->size() << endl;
     cloudOut = *cloudOutTemp;
     */
 }
extractPlaneFromCloudRgb()
void pclUtilitys::extractPlaneFromCloudRgb (const pcl::PointCloud< pcl::PointXYZRGB > & cloud, pcl::PointCloud< pcl::PointXYZRGB > & cloudOut, bool bSegPlane)
get PCL plane from color PCL input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& cloud, bool bSegPlane output:
pcl::PointCloud<pcl::PointXYZRGB>& cloudOut
Returns
void
Definition at line 626 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = cloud;
     //SAC plane segmentation
     pcl::ModelCoefficients::Ptr coefficients (new pcl::ModelCoefficients);
     pcl::PointIndices::Ptr inliers (new pcl::PointIndices);
     pcl::SACSegmentation<pcl::PointXYZRGB> seg;// Create the segmentation object
     seg.setOptimizeCoefficients (true);// Optional
     // Mandatory
     seg.setModelType (pcl::SACMODEL_PLANE);// pcl::SACMODEL_NORMAL_PLANE //
     seg.setMethodType (pcl::SAC_RANSAC);
     seg.setDistanceThreshold (0.10);
     seg.setInputCloud(cloudIn);
     seg.segment (*inliers, *coefficients);
     // Extract the inliers - no rgb
     pcl::ExtractIndices<pcl::PointXYZRGB> extract;
     extract.setInputCloud(cloudIn);
     extract.setIndices (inliers);
     extract.setNegative (bSegPlane);
     extract.filter(cloudOut);
 }
Referenced by setWallrelativeToOriginXY().
FastPointFeatureHistogramsExample()
void pclUtilitys::FastPointFeatureHistogramsExample (const pcl::PointCloud< pcl::PointXYZRGB > & in1, const pcl::PointCloud< pcl::PointXYZRGB > & in2, pcl::PointCloud< pcl::PointXYZRGB > & out)
FastPointFeatureHistogramsExample input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in1, const pcl::PointCloud<pcl::PointXYZRGB>& in2, output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 2539 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn1 (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn1 = in1;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn2 (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn2 = in2;
     pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>());
     pointcloud::Ptr source(new pointcloud);
     pointcloud::Ptr target(new pointcloud);
     pcl::copyPointCloud(*cloudIn1, *source);
     pcl::copyPointCloud(*cloudIn2, *target);
     float s1 = 0.02, s2 = 0.02; //default = 0.01
     pointcloud::Ptr source_f(new pointcloud);
     pcl::console::print_info("Waiting for filtering the data\n");
     pcl::VoxelGrid<pcl::PointXYZ> sor;
     sor.setInputCloud(source);
     sor.setLeafSize(s1, s1, s1);
     sor.filter(*source_f);
     pcl::PointCloud<pcl::PointXYZ>::Ptr target_f(new pcl::PointCloud<pcl::PointXYZ>);
     pcl::console::print_info("Waiting for filtering the data\n");
     pcl::VoxelGrid<pcl::PointXYZ> sor2;
     sor2.setInputCloud(target);
     sor2.setLeafSize(s2, s2, s2);
     sor2.filter(*target_f);
     fpfhFeature::Ptr source_fpfh = compute_fpfh_feature(source_f, tree);
     //cout << "calculate time is: " << float(end3 - start) / CLOCKS_PER_SEC << endl;
     cout << "source cloud number is " << source_f->points.size() << endl;
     fpfhFeature::Ptr target_fpfh = compute_fpfh_feature(target_f, tree);
     //cout << "calculate time is: " << float(end2 - end3) / CLOCKS_PER_SEC << endl;
     cout << "targrt cloud number is " << target_f->points.size() << endl;
     pcl::SampleConsensusInitialAlignment<pcl::PointXYZ, pcl::PointXYZ, pcl::FPFHSignature33> sac_ia;
     sac_ia.setMaximumIterations(60);
     sac_ia.setInputSource(source_f);
     sac_ia.setSourceFeatures(source_fpfh);
     sac_ia.setInputTarget(target_f);
     sac_ia.setTargetFeatures(target_fpfh);
     pointcloud::Ptr align(new pointcloud);
     sac_ia.setNumberOfSamples(30);
     sac_ia.align(*align);
     //cout << "calculate time is: " << float(end - end2) / CLOCKS_PER_SEC << endl;
     pcl::copyPointCloud(*align, out);
     pcl::visualization::PCLVisualizer viewer("PCL Viewer");
     viewer.setBackgroundColor(0.0, 0.0, 0.0);
     pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ> alignColorHandler(align, 255, 255, 0);
     viewer.addPointCloud(align, alignColorHandler, "align");
     viewer.setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 3, "align");
     pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ> sourceColorHandler(source, 0, 0, 200);
     viewer.addPointCloud(source, sourceColorHandler, "source");
     viewer.setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 3, "source");
     pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ> targetColorHandler(target, 120, 120, 120);
     viewer.addPointCloud(target, targetColorHandler, "target");
     viewer.setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 3, "target");
     while (!viewer.wasStopped())
     {
         viewer.spinOnce();
     }
 }
References compute_fpfh_feature(), and viewer.
getBiggestPlaneLocation()
void pclUtilitys::getBiggestPlaneLocation (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointXYZ & out)
Definition at line 29 of file pclUtilitys.cpp.
{
     //better implement it in opencv, because of of the cv::mat handling
     //proof gradienten grid
     //proof the whole cloud
 }
getNormalsFromCloud()
void pclUtilitys::getNormalsFromCloud (const pcl::PointCloud< pcl::PointXYZ > & cloud, pcl::PointCloud< pcl::PointNormal > & normals)
normal from cloud input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& cloud output:
pcl::PointCloud<pcl::PointNormal>& normals
Returns
void
Definition at line 964 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = cloud;
     const float radius = 0.02;//0.05
     const float k = 0; //must be 0
     if (cloudIn->isOrganized ()){
       pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::PointNormal> ne;
       ne.setInputCloud (cloudIn);
       ne.setNormalEstimationMethod (pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::PointNormal>::COVARIANCE_MATRIX);
       ne.setNormalSmoothingSize (radius);
       ne.setDepthDependentSmoothing (true);
       ne.compute (normals);
     }else{
         // Estimate the normals
         pcl::NormalEstimation<pcl::PointXYZ, pcl::PointNormal> ne;
         pcl::search::KdTree<pcl::PointXYZ>::Ptr normalKdTree(new pcl::search::KdTree<pcl::PointXYZ>());
         ne.setInputCloud(cloudIn);
         ne.setSearchMethod(normalKdTree);
         ne.setKSearch(k);
         ne.setRadiusSearch(radius); //0.02
         ne.compute(normals);
     }
 }
Referenced by reconTwoPcl().
getNormalsFromCloudRgb()
void pclUtilitys::getNormalsFromCloudRgb (const pcl::PointCloud< pcl::PointXYZRGB > & cloud, pcl::PointCloud< pcl::Normal > & normals)
normal from RGB cloud input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& cloud output:
pcl::PointCloud<pcl::Normal>& normals
Returns
void
Definition at line 998 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudInRGB (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudInRGB = cloud;
     const float radius = 0.05;
     const float k = 0; //must be 0
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     convertXYZRGBtoXYZ(*cloudInRGB, cloudIn);
     if (cloudIn->isOrganized ()){
       pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::Normal> ne;
       ne.setInputCloud (cloudIn);
       ne.setNormalEstimationMethod (pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::Normal>::COVARIANCE_MATRIX);
       ne.setNormalSmoothingSize (float (radius));
       ne.setDepthDependentSmoothing (true);
       ne.compute (normals);
     }else{
       pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> ne;
       ne.setInputCloud (cloudIn);
       //ne.setSearchMethod (pcl::search::KdTree<pcl::PointXYZ>::Ptr (new pcl::search::KdTree<pcl::PointXYZ>));
       ne.setSearchMethod (pclUtilitys::tree_xyz);
       ne.setKSearch(k);
       ne.setRadiusSearch (radius);
       ne.compute (normals);
     }
 }
References convertXYZRGBtoXYZ(), and tree_xyz.
Referenced by convertXYZRGBtoXYZI(), convertXYZRGBtoXYZRGBNormal(), doCylinderSegmentationRgb(), and pclApp::testViewsWithNormals().
getNormalsXYZIFromCloud()
void pclUtilitys::getNormalsXYZIFromCloud (const pcl::PointCloud< pcl::PointXYZ > & cloud, pcl::PointCloud< pcl::PointXYZINormal > & cloudOut)
normal from RGB cloud to RGBI input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& cloud output:
pcl::PointCloud<pcl::PointXYZINormal>& cloudOut
Returns
void
Definition at line 1034 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = cloud;
     // Create the normal estimation class, and pass the input dataset to it
     pcl::NormalEstimation<pcl::PointXYZ, pcl::PointXYZINormal> ne;
     ne.setInputCloud (cloudIn);
     // Create an empty kdtree representation, and pass it to the normal estimation object.
     // Its content will be filled inside the object, based on the given input dataset (as no other search surface is given).
     //pcl::search::KdTree<pcl::PointXYZ>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZ> ());
     //ne.setSearchMethod (tree);
     ne.setSearchMethod (pclUtilitys::tree_xyz);
     // Output datasets
     pcl::PointCloud<pcl::PointXYZINormal>::Ptr cloud_normals (new pcl::PointCloud<pcl::PointXYZINormal>);
     // Use all neighbors in a sphere of radius 5cm
     ne.setRadiusSearch (0.05);
     // Compute the features
     ne.compute (cloudOut);
 }
References tree_xyz.
getNormalsXYZIFromCloudRgb()
void pclUtilitys::getNormalsXYZIFromCloudRgb (const pcl::PointCloud< pcl::PointXYZRGB > & cloud, pcl::PointCloud< pcl::PointXYZINormal > & cloudOut)
get NormalsXYZI from Cloud RGB input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& cloud output:
pcl::PointCloud<pcl::PointXYZINormal>& cloudOut
Returns
void
Definition at line 1062 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = cloud;
     // Create the normal estimation class, and pass the input dataset to it
     pcl::NormalEstimation<pcl::PointXYZRGB, pcl::PointXYZINormal> ne;
     ne.setInputCloud (cloudIn);
     // Create an empty kdtree representation, and pass it to the normal estimation object.
     // Its content will be filled inside the object, based on the given input dataset (as no other search surface is given).
     //pcl::search::KdTree<pcl::PointXYZRGB>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZRGB> ());
     //ne.setSearchMethod (tree);
     ne.setSearchMethod (pclUtilitys::tree_xyzrgb);
     // Output datasets
     pcl::PointCloud<pcl::PointXYZINormal>::Ptr cloud_normals (new pcl::PointCloud<pcl::PointXYZINormal>);
     // Use all neighbors in a sphere of radius 5cm
     ne.setRadiusSearch (0.05);
     // Compute the features
     ne.compute (cloudOut);
 }
References tree_xyzrgb.
Referenced by doConditionalEuclideanClusteringRgb().
icpNormals()
void pclUtilitys::icpNormals (const pcl::PointCloud< pcl::PointXYZRGB > & in1, const pcl::PointCloud< pcl::PointXYZRGB > & in2, pcl::PointCloud< pcl::PointXYZRGB > & out)
ICP via normals input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in1, const pcl::PointCloud<pcl::PointXYZRGB>& in2 output:
pcl::PointCloud<pcl::PointXYZRGB>::Ptr& out
Returns
void
Definition at line 2230 of file pclUtilitys.cpp.
{
     int iterations = 20000;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr rgbIn1 (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr rgbIn2 (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr outResult (new pcl::PointCloud<pcl::PointXYZRGB>);
     *rgbIn1 = in1;
     *rgbIn2 = in2;
     *outResult = out;
     pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr rgbNormal1 (new pcl::PointCloud<pcl::PointXYZRGBNormal>);
     pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr rgbNormal2 (new pcl::PointCloud<pcl::PointXYZRGBNormal>);
     pclUtilitys::convertXYZRGBtoXYZRGBNormal(*rgbIn1, rgbNormal1);
     pclUtilitys::convertXYZRGBtoXYZRGBNormal(*rgbIn2, rgbNormal2);
     pcl::IterativeClosestPoint<pcl::PointXYZRGBNormal, pcl::PointXYZRGBNormal> icp;
     icp.setInputSource(rgbNormal1);
     icp.setInputTarget(rgbNormal2);
     icp.setMaximumIterations (iterations);
     icp.setTransformationEpsilon (1e-6);
     icp.setMaxCorrespondenceDistance (0.001);
     /*
     MyPointRepresentation point_representation;
     float alpha[4] = {1.0, 1.0, 1.0, 1.0};
     point_representation.setRescaleValues (alpha);
     icp.setPointRepresentation (pcl::make_shared<const pcl::PointXYZRGBNormal> (point_representation));
     */
     pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr icpAligned (new pcl::PointCloud<pcl::PointXYZRGBNormal>);
     icp.align(*icpAligned);
     transM = icp.getFinalTransformation();
     pclUtilitys::convertXYZRGBNormaltoXYZRGB(*icpAligned, outResult);
     out = *outResult;
 }
References convertXYZRGBNormaltoXYZRGB(), convertXYZRGBtoXYZRGBNormal(), and transM.
icpSimple()
void pclUtilitys::icpSimple (const pcl::PointCloud< pcl::PointXYZRGB > & in1, const pcl::PointCloud< pcl::PointXYZRGB > & in2, pcl::PointCloud< pcl::PointXYZRGB > & out)
ICP simple input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in1, const pcl::PointCloud<pcl::PointXYZRGB>& in2 output:
pcl::PointCloud<pcl::PointXYZRGB>::Ptr& out
Returns
void
Definition at line 2181 of file pclUtilitys.cpp.
{
     int iterations = 20000;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr rgbIn1 (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr rgbIn2 (new pcl::PointCloud<pcl::PointXYZRGB>);
     *rgbIn1 = in1;
     *rgbIn2 = in2;
     //pcl::PointCloud<pcl::PointXYZ>::Ptr pclIn1 (new pcl::PointCloud<pcl::PointXYZ>);
     //pcl::PointCloud<pcl::PointXYZ>::Ptr pclIn2 (new pcl::PointCloud<pcl::PointXYZ>);
     //pcl::PointCloud<pcl::PointXYZRGB>::Ptr rgbOut (new pcl::PointCloud<pcl::PointXYZRGB>);
     //pcl::IterativeClosestPoint<pcl::PointXYZ, pcl::PointXYZ> icp;
     //convertXYZRGBtoXYZ(*rgbIn1, pclIn1);
     //convertXYZRGBtoXYZ(*rgbIn2, pclIn2);
     pcl::IterativeClosestPoint<pcl::PointXYZRGB, pcl::PointXYZRGB> icp;
     icp.setInputSource(rgbIn1);
     icp.setInputTarget(rgbIn2);
     icp.setMaximumIterations (iterations);
     icp.setTransformationEpsilon (1e-6);
     // Set the maximum distance between two correspondences (src<->tgt) to 10cm
     // Note: adjust this based on the size of your datasets
     icp.setMaxCorrespondenceDistance (0.01);
     /*
         icp.setPointRepresentation (pcl::make_shared<const MyPointRepresentation> (point_representation));
         // Instantiate our custom point representation (defined above) ...
         MyPointRepresentation point_representation;
         // ... and weight the 'curvature' dimension so that it is balanced against x, y, and z
         float alpha[4] = {1.0, 1.0, 1.0, 1.0};
         point_representation.setRescaleValues (alpha);
     */
     //pcl::PointCloud<pcl::PointXYZ> final;
     icp.align(out);
     //convertPtrXYZtoXYZRGB(final, rgbOut);
     //out = *rgbOut;
     std::cout << "has converged:" << icp.hasConverged() << " score: " <<
     icp.getFitnessScore() << std::endl;
     transM = icp.getFinalTransformation();
     //std::cout << "final Transformation...\n" << icp.getFinalTransformation() << std::endl;
 }
References transM.
keypointExtractionHarris()
void pclUtilitys::keypointExtractionHarris (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
keypointExtractionHarris input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 2517 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZI>::Ptr keypoints (new pcl::PointCloud<pcl::PointXYZI>);
     *cloudIn = in;
     float threshold = 0.0000001f;
     HarrisKeypoint3D<PointXYZRGB, PointXYZI> harrisDetect;
     harrisDetect.setNonMaxSupression(true);
     harrisDetect.setInputCloud(cloudIn);
     harrisDetect.setThreshold(threshold);
     harrisDetect.compute(*keypoints);
     pcl::copyPointCloud(*keypoints, out);
 }
keypointExtractionISS()
void pclUtilitys::keypointExtractionISS (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
keypointExtractionISS input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 2366 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = in;
     /*
         const std::string strFilePath = std::string("/media/hd2/db/RGBD/kv2/400/0_020298740747_PCLrgb.ply");
         pcl::PLYReader Reader;
         Reader.read(strFilePath, *cloudIn);
     */
     PointCloud<PointXYZRGB>::Ptr pIss(new PointCloud<PointXYZRGB>());
     DetectISSKeypoints(cloudIn, pIss);
     std::cout << "ISS KeyPoints: " << pIss->points.size() << std::endl;
     pcl::copyPointCloud(*pIss, out);
 }
References DetectISSKeypoints().
keypointExtractionNARF() [1/2]
void pclUtilitys::keypointExtractionNARF (const pcl::PointCloud< pcl::PointXYZ > & in, pcl::PointCloud< pcl::PointWithScale > & out)
keypointExtractionNARF input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in output:
pcl::PointCloud<pcl::PointWithScale>& out
Returns
void
Definition at line 2346 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = in;
     //PointCloud<PointWithScale>::Ptr pSift(new PointCloud<PointWithScale>());
     //PointCloud<PointT>::Ptr pSift(new PointCloud<PointT>());
     PointCloud<PointXYZ>::Ptr pSift(new PointCloud<PointXYZ>());
     DetectNARFKeypoints(cloudIn, pSift);
     std::cout << "NARF KeyPoints: " << pSift->points.size() << std::endl;
     pcl::copyPointCloud(*pSift, out);
 }
References DetectNARFKeypoints().
keypointExtractionNARF() [2/2]
void pclUtilitys::keypointExtractionNARF (const pcl::PointCloud< pcl::PointXYZ > & in, pcl::PointCloud< pcl::PointXYZ > & out)
keypointExtractionNARF input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in output:
pcl::PointCloud<pcl::PointXYZ>& out
Returns
void
Definition at line 2326 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = in;
     //PointCloud<PointWithScale>::Ptr pSift(new PointCloud<PointWithScale>());
     //PointCloud<PointT>::Ptr pSift(new PointCloud<PointT>());
     PointCloud<PointXYZ>::Ptr pSift(new PointCloud<PointXYZ>());
     DetectNARFKeypoints(cloudIn, pSift);
     std::cout << "NARF KeyPoints: " << pSift->points.size() << std::endl;
     pcl::copyPointCloud(*pSift, out);
 }
References DetectNARFKeypoints().
keypointExtractionSIFT() [1/3]
void pclUtilitys::keypointExtractionSIFT (const pcl::PointCloud< pcl::PointXYZ > & in, pcl::PointCloud< pcl::PointNormal >::Ptr & normalCloud, pcl::PointCloud< pcl::PointWithScale > & out)
keypointExtractionSIFT input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in output:
pcl::PointCloud<pcl::PointNormal>::Ptr& normalCloud, pcl::PointCloud<pcl::PointWithScale>& out
Returns
void
Definition at line 2479 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     pcl::PointCloud<pcl::PointWithScale>::Ptr keypoints (new pcl::PointCloud<pcl::PointWithScale>);
     *cloudIn = in;
         int i=0;
         int imax = normalCloud->points.size();
         while(i<imax)        {
             normalCloud->points[i].x = cloudIn->points[i].x;
             normalCloud->points[i].y = cloudIn->points[i].y;
             normalCloud->points[i].z = cloudIn->points[i].z;
             i++;
         }
         float minScale = 0.002f;// the standard deviation of the smallest scale in the scale space
         int nrOctaves = 8;// the number of octaves (i.e. doublings of scale) to compute
         int nrScalesPerOctave = 8;// the number of scales to compute within each octave
         float minContrast = 0.001f;// the minimum contrast required for detection
         SIFTKeypoint<PointNormal, PointWithScale> sift;
         search::KdTree<PointNormal>::Ptr kdTree(new search::KdTree<PointNormal>());
         sift.setSearchMethod(kdTree);
         sift.setScales(minScale, nrOctaves, nrScalesPerOctave);
         sift.setMinimumContrast(minContrast);
         sift.setInputCloud(normalCloud);
         sift.compute(*keypoints);
         pcl::copyPointCloud(*keypoints, out);
 }
keypointExtractionSIFT() [2/3]
void pclUtilitys::keypointExtractionSIFT (const pcl::PointCloud< pcl::PointXYZ > & in, pcl::PointCloud< pcl::PointWithScale > & out)
keypointExtractionSIFT input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in output:
pcl::PointCloud<pcl::PointWithScale>& out
Returns
void
Definition at line 2434 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     pcl::PointCloud<pcl::PointWithScale>::Ptr keypoints (new pcl::PointCloud<pcl::PointWithScale>);
     *cloudIn = in;
         // Estimate the normals
         pcl::NormalEstimation<pcl::PointXYZ, pcl::PointNormal> normalEstimation;
         pcl::PointCloud<pcl::PointNormal>::Ptr normalCloud (new pcl::PointCloud<pcl::PointNormal>);
         pcl::search::KdTree<pcl::PointXYZ>::Ptr normalKdTree(new pcl::search::KdTree<pcl::PointXYZ>());
         normalEstimation.setInputCloud(cloudIn);
         normalEstimation.setSearchMethod(normalKdTree);
         normalEstimation.setRadiusSearch(0.02);
         normalEstimation.compute(*normalCloud);
         for(size_t i = 0; i<normalCloud->points.size(); ++i)
         {
             normalCloud->points[i].x = cloudIn->points[i].x;
             normalCloud->points[i].y = cloudIn->points[i].y;
             normalCloud->points[i].z = cloudIn->points[i].z;
         }
         float minScale = 0.002f;// the standard deviation of the smallest scale in the scale space
         int nrOctaves = 4;// the number of octaves (i.e. doublings of scale) to compute
         int nrScalesPerOctave = 4;// the number of scales to compute within each octave
         float minContrast = 0.001f;// the minimum contrast required for detection
         SIFTKeypoint<PointNormal, PointWithScale> sift;
         search::KdTree<PointNormal>::Ptr kdTree(new search::KdTree<PointNormal>());
         sift.setSearchMethod(kdTree);
         sift.setScales(minScale, nrOctaves, nrScalesPerOctave);
         sift.setMinimumContrast(minContrast);
         sift.setInputCloud(normalCloud);
         sift.compute(*keypoints);
         pcl::copyPointCloud(*keypoints, out);
 }
keypointExtractionSIFT() [3/3]
void pclUtilitys::keypointExtractionSIFT (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
keypointExtractionSIFT input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 2389 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointWithScale>::Ptr keypoints (new pcl::PointCloud<pcl::PointWithScale>);
     *cloudIn = in;
         // Estimate the normals
         pcl::NormalEstimation<pcl::PointXYZRGB, pcl::PointNormal> normalEstimation;
         pcl::PointCloud<pcl::PointNormal>::Ptr normalCloud (new pcl::PointCloud<pcl::PointNormal>);
         pcl::search::KdTree<pcl::PointXYZRGB>::Ptr normalKdTree(new pcl::search::KdTree<pcl::PointXYZRGB>());
         normalEstimation.setInputCloud(cloudIn);
         normalEstimation.setSearchMethod(normalKdTree);
         normalEstimation.setRadiusSearch(0.02);
         normalEstimation.compute(*normalCloud);
         for(size_t i = 0; i<normalCloud->points.size(); ++i)
         {
             normalCloud->points[i].x = cloudIn->points[i].x;
             normalCloud->points[i].y = cloudIn->points[i].y;
             normalCloud->points[i].z = cloudIn->points[i].z;
         }
         float minScale = 0.002f;// the standard deviation of the smallest scale in the scale space
         int nrOctaves = 4;// the number of octaves (i.e. doublings of scale) to compute
         int nrScalesPerOctave = 4;// the number of scales to compute within each octave
         float minContrast = 0.001f;// the minimum contrast required for detection
         SIFTKeypoint<PointNormal, PointWithScale> siftDetect;
         search::KdTree<PointNormal>::Ptr kdTree(new search::KdTree<PointNormal>());
         siftDetect.setSearchMethod(kdTree);
         siftDetect.setScales(minScale, nrOctaves, nrScalesPerOctave);
         siftDetect.setMinimumContrast(minContrast);
         siftDetect.setInputCloud(normalCloud);
         siftDetect.compute(*keypoints);
         pcl::copyPointCloud(*keypoints, out);
 }
Referenced by reconTwoPcl().
mergeXYZPcl()
void pclUtilitys::mergeXYZPcl (const pcl::PointCloud< pcl::PointXYZ > & in1, const pcl::PointCloud< pcl::PointXYZ > & in2, pcl::PointCloud< pcl::PointXYZ >::Ptr & out)
merge two PCL without color input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in1, const pcl::PointCloud<pcl::PointXYZ>& in2 output:
pcl::PointCloud<pcl::PointXYZ>::Ptr& out
Returns
void
Definition at line 2116 of file pclUtilitys.cpp.
{
     int i=0;
     int imax = in1.points.size();
     //cout << "imax in1: " << imax << endl;
     while(i<imax){
         out->push_back(in1.points[i]);
         i++;
     }
     i=0;
     imax = in2.points.size();
     cout << "imax in2: " << imax << endl;
     while(i<imax){
         out->push_back(in2.points[i]);
         i++;
     }
 }
mergeXYZRGBPcl()
void pclUtilitys::mergeXYZRGBPcl (const pcl::PointCloud< pcl::PointXYZRGB > & in1, const pcl::PointCloud< pcl::PointXYZRGB > & in2, pcl::PointCloud< pcl::PointXYZRGB >::Ptr & out)
merge two PCL with color input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in1, const pcl::PointCloud<pcl::PointXYZRGB>& in2 output:
pcl::PointCloud<pcl::PointXYZRGB>::Ptr& out
Returns
void
Definition at line 2142 of file pclUtilitys.cpp.
{
     //long int outPclSize = in1.size()+in2.size();
     //vector<pcl::PointXYZRGB> outPcl;
     //out->points.resize(outPclSize);
     int i=0;
     int imax = in1.points.size();
     cout << "imax in1: " << imax << endl;
     while(i<imax){
         out->push_back(in1.points[i]);
         /*
         out->points[i].r = 0.0;
         out->points[i].g = 0.0;
         out->points[i].b = 0.0;
         */
         i++;
     }
     i=0;
     imax = in2.points.size();
     cout << "imax in2: " << imax << endl;
     while(i<imax){
         out->push_back(in2.points[i]);
         /*
         out->points[j].r = 0.0;
         out->points[j].g = 1.0;
         out->points[j].b = 0.0;
         */
         i++;
     }
 }
Referenced by pclApp::testPclRgbObjectDetectionPipe01().
momentOfInertiaRgb()
void pclUtilitys::momentOfInertiaRgb (const pcl::PointCloud< pcl::PointXYZRGB > & in)
momentOfInertiaRgb input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 1731 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudRgbIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudRgbIn = in;
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     convertXYZRGBtoXYZ(*cloudRgbIn, cloudIn);
     pcl::MomentOfInertiaEstimation <pcl::PointXYZ> feature_extractor;
     feature_extractor.setInputCloud (cloudIn);
     feature_extractor.compute ();
     std::vector <float> moment_of_inertia;
     std::vector <float> eccentricity;
     pcl::PointXYZ min_point_AABB;
     pcl::PointXYZ max_point_AABB;
     pcl::PointXYZ min_point_OBB;
     pcl::PointXYZ max_point_OBB;
     pcl::PointXYZ position_OBB;
     Eigen::Matrix3f rotational_matrix_OBB;
     float major_value, middle_value, minor_value;
     Eigen::Vector3f major_vector, middle_vector, minor_vector;
     Eigen::Vector3f mass_center;
     feature_extractor.getMomentOfInertia (moment_of_inertia);
     feature_extractor.getEccentricity (eccentricity);
     feature_extractor.getAABB (min_point_AABB, max_point_AABB);
     feature_extractor.getOBB (min_point_OBB, max_point_OBB, position_OBB, rotational_matrix_OBB);
     feature_extractor.getEigenValues (major_value, middle_value, minor_value);
     feature_extractor.getEigenVectors (major_vector, middle_vector, minor_vector);
     feature_extractor.getMassCenter (mass_center);
     //viewer->addPointCloud<pcl::PointXYZRGB> (cloudRgbIn, "sample cloud");
     //axis aligned AABB
     //viewer->addCube (min_point_AABB.x, max_point_AABB.x, min_point_AABB.y, max_point_AABB.y, min_point_AABB.z, max_point_AABB.z, 1.0, 1.0, 0.0, "AABB");
     //viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_REPRESENTATION, pcl::visualization::PCL_VISUALIZER_REPRESENTATION_WIREFRAME, "AABB");
     //obj aligened OBB
     Eigen::Vector3f position (position_OBB.x, position_OBB.y, position_OBB.z);
     Eigen::Quaternionf quat (rotational_matrix_OBB);
     viewer->addCube (position, quat, max_point_OBB.x - min_point_OBB.x, max_point_OBB.y - min_point_OBB.y, max_point_OBB.z - min_point_OBB.z, "OBB");
     viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_REPRESENTATION, pcl::visualization::PCL_VISUALIZER_REPRESENTATION_WIREFRAME, "OBB");
     /*
     pcl::PointXYZ center (mass_center (0), mass_center (1), mass_center (2));
     pcl::PointXYZ x_axis (major_vector (0) + mass_center (0), major_vector (1) + mass_center (1), major_vector (2) + mass_center (2));
     pcl::PointXYZ y_axis (middle_vector (0) + mass_center (0), middle_vector (1) + mass_center (1), middle_vector (2) + mass_center (2));
     pcl::PointXYZ z_axis (minor_vector (0) + mass_center (0), minor_vector (1) + mass_center (1), minor_vector (2) + mass_center (2));
     viewer->addLine (center, x_axis, 1.0f, 0.0f, 0.0f, "major eigen vector");
     viewer->addLine (center, y_axis, 0.0f, 1.0f, 0.0f, "middle eigen vector");
     viewer->addLine (center, z_axis, 0.0f, 0.0f, 1.0f, "minor eigen vector");
     */
 }
References convertXYZRGBtoXYZ(), and viewer.
momentOfInertiaTest()
void pclUtilitys::momentOfInertiaTest (const pcl::PointCloud< pcl::PointXYZ > & in, pcl::PointCloud< pcl::PointXYZ > & out)
momentOfInertiaTest input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in output:
pcl::PointCloud<pcl::PointXYZ>& out
Returns
void
Definition at line 657 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = in;
       pcl::MomentOfInertiaEstimation <pcl::PointXYZ> feature_extractor;
       feature_extractor.setInputCloud (cloudIn);
       feature_extractor.compute ();
       std::vector <float> moment_of_inertia;
       std::vector <float> eccentricity;
       pcl::PointXYZ min_point_AABB;
       pcl::PointXYZ max_point_AABB;
       pcl::PointXYZ min_point_OBB;
       pcl::PointXYZ max_point_OBB;
       pcl::PointXYZ position_OBB;
       Eigen::Matrix3f rotational_matrix_OBB;
       float major_value, middle_value, minor_value;
       Eigen::Vector3f major_vector, middle_vector, minor_vector;
       Eigen::Vector3f mass_center;
       feature_extractor.getMomentOfInertia (moment_of_inertia);
       feature_extractor.getEccentricity (eccentricity);
       feature_extractor.getAABB (min_point_AABB, max_point_AABB);
       feature_extractor.getOBB (min_point_OBB, max_point_OBB, position_OBB, rotational_matrix_OBB);
       feature_extractor.getEigenValues (major_value, middle_value, minor_value);
       feature_extractor.getEigenVectors (major_vector, middle_vector, minor_vector);
       feature_extractor.getMassCenter (mass_center);
       pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
       viewer->setBackgroundColor (0, 0, 0);
       viewer->addCoordinateSystem (1.0);
       viewer->initCameraParameters ();
       viewer->addPointCloud<pcl::PointXYZ> (cloudIn, "sample cloud");
       viewer->addCube (min_point_AABB.x, max_point_AABB.x, min_point_AABB.y, max_point_AABB.y, min_point_AABB.z, max_point_AABB.z, 1.0, 1.0, 0.0, "AABB");
       viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_REPRESENTATION, pcl::visualization::PCL_VISUALIZER_REPRESENTATION_WIREFRAME, "AABB");
       Eigen::Vector3f position (position_OBB.x, position_OBB.y, position_OBB.z);
       Eigen::Quaternionf quat (rotational_matrix_OBB);
       viewer->addCube (position, quat, max_point_OBB.x - min_point_OBB.x, max_point_OBB.y - min_point_OBB.y, max_point_OBB.z - min_point_OBB.z, "OBB");
       viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_REPRESENTATION, pcl::visualization::PCL_VISUALIZER_REPRESENTATION_WIREFRAME, "OBB");
       pcl::PointXYZ center (mass_center (0), mass_center (1), mass_center (2));
       pcl::PointXYZ x_axis (major_vector (0) + mass_center (0), major_vector (1) + mass_center (1), major_vector (2) + mass_center (2));
       pcl::PointXYZ y_axis (middle_vector (0) + mass_center (0), middle_vector (1) + mass_center (1), middle_vector (2) + mass_center (2));
       pcl::PointXYZ z_axis (minor_vector (0) + mass_center (0), minor_vector (1) + mass_center (1), minor_vector (2) + mass_center (2));
       viewer->addLine (center, x_axis, 1.0f, 0.0f, 0.0f, "major eigen vector");
       viewer->addLine (center, y_axis, 0.0f, 1.0f, 0.0f, "middle eigen vector");
       viewer->addLine (center, z_axis, 0.0f, 0.0f, 1.0f, "minor eigen vector");
       while(!viewer->wasStopped())
       {
         viewer->spinOnce (100);
         std::this_thread::sleep_for(100ms);
       }
 }
References viewer.
momentOfInertiaTestRgb()
void pclUtilitys::momentOfInertiaTestRgb (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
momentOfInertiaTestRGB input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 723 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudRgbIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudRgbIn = in;
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     convertXYZRGBtoXYZ(*cloudRgbIn, cloudIn);
       pcl::MomentOfInertiaEstimation <pcl::PointXYZ> feature_extractor;
       feature_extractor.setInputCloud (cloudIn);
       feature_extractor.compute ();
       std::vector <float> moment_of_inertia;
       std::vector <float> eccentricity;
       pcl::PointXYZ min_point_AABB;
       pcl::PointXYZ max_point_AABB;
       pcl::PointXYZ min_point_OBB;
       pcl::PointXYZ max_point_OBB;
       pcl::PointXYZ position_OBB;
       Eigen::Matrix3f rotational_matrix_OBB;
       float major_value, middle_value, minor_value;
       Eigen::Vector3f major_vector, middle_vector, minor_vector;
       Eigen::Vector3f mass_center;
       feature_extractor.getMomentOfInertia (moment_of_inertia);
       feature_extractor.getEccentricity (eccentricity);
       feature_extractor.getAABB (min_point_AABB, max_point_AABB);
       feature_extractor.getOBB (min_point_OBB, max_point_OBB, position_OBB, rotational_matrix_OBB);
       feature_extractor.getEigenValues (major_value, middle_value, minor_value);
       feature_extractor.getEigenVectors (major_vector, middle_vector, minor_vector);
       feature_extractor.getMassCenter (mass_center);
       pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
       viewer->setBackgroundColor (0, 0, 0);
       viewer->addCoordinateSystem (1.0);
       viewer->initCameraParameters ();
       viewer->addPointCloud<pcl::PointXYZRGB> (cloudRgbIn, "sample cloud");
       viewer->addCube (min_point_AABB.x, max_point_AABB.x, min_point_AABB.y, max_point_AABB.y, min_point_AABB.z, max_point_AABB.z, 1.0, 1.0, 0.0, "AABB");
       viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_REPRESENTATION, pcl::visualization::PCL_VISUALIZER_REPRESENTATION_WIREFRAME, "AABB");
       Eigen::Vector3f position (position_OBB.x, position_OBB.y, position_OBB.z);
       Eigen::Quaternionf quat (rotational_matrix_OBB);
       viewer->addCube (position, quat, max_point_OBB.x - min_point_OBB.x, max_point_OBB.y - min_point_OBB.y, max_point_OBB.z - min_point_OBB.z, "OBB");
       viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_REPRESENTATION, pcl::visualization::PCL_VISUALIZER_REPRESENTATION_WIREFRAME, "OBB");
       pcl::PointXYZ center (mass_center (0), mass_center (1), mass_center (2));
       pcl::PointXYZ x_axis (major_vector (0) + mass_center (0), major_vector (1) + mass_center (1), major_vector (2) + mass_center (2));
       pcl::PointXYZ y_axis (middle_vector (0) + mass_center (0), middle_vector (1) + mass_center (1), middle_vector (2) + mass_center (2));
       pcl::PointXYZ z_axis (minor_vector (0) + mass_center (0), minor_vector (1) + mass_center (1), minor_vector (2) + mass_center (2));
       viewer->addLine (center, x_axis, 1.0f, 0.0f, 0.0f, "major eigen vector");
       viewer->addLine (center, y_axis, 0.0f, 1.0f, 0.0f, "middle eigen vector");
       viewer->addLine (center, z_axis, 0.0f, 0.0f, 1.0f, "minor eigen vector");
       while(!viewer->wasStopped())
       {
         viewer->spinOnce (100);
         std::this_thread::sleep_for(100ms);
       }
 }
References convertXYZRGBtoXYZ(), and viewer.
movingLeastSquaresFilerRgb()
void pclUtilitys::movingLeastSquaresFilerRgb (const pcl::PointCloud< pcl::PointXYZRGB > & cloud, pcl::PointCloud< pcl::PointXYZRGB > & cloudOut, int polyOrder, float radius)
movingLeastSquaresFilerRgb input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& cloud, float distanceThreshold, int polyOrder, float radius output:
pcl::PointCloud<pcl::PointXYZRGB>& cloudOut
Returns
void
Definition at line 917 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = cloud;
     //pcl::PointCloud<PointXYZ> mls_points;
     //pcl::PointCloud<PointNormal>::Ptr mls_normals (new PointCloud<PointNormal> ());
     pcl::MovingLeastSquares<PointXYZRGB, PointNormal> mls;
     /*
   mls.setInputCloud (cloud);
   mls.setComputeNormals (true);
   mls.setPolynomialOrder (2);
   mls.setSearchMethod (tree);
   mls.setSearchRadius (0.03);
     */
 }
narfKeypointExtraction()
void pclUtilitys::narfKeypointExtraction (const pcl::PointCloud< pcl::PointXYZ > & in, pcl::PointCloud< pcl::PointXYZ > & out)
narfKeypointExtraction input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in output:
pcl::PointCloud<pcl::PointXYZ>& out
Returns
void
Definition at line 1929 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = in;
     //Parameter
     float angular_resolution = 0.2f;
     float support_size = 0.02f;//0.2
     pcl::RangeImage::CoordinateFrame coordinate_frame = pcl::RangeImage::CAMERA_FRAME;
     bool setUnseenToMaxRange = true;
     pcl::PointCloud<pcl::PointWithViewpoint> far_ranges;
     Eigen::Affine3f scene_sensor_pose (Eigen::Affine3f::Identity ());
     scene_sensor_pose = Eigen::Affine3f (Eigen::Translation3f (in.sensor_origin_[0],in.sensor_origin_[1],in.sensor_origin_[2])) * Eigen::Affine3f (in.sensor_orientation_);
     // -----------------------------------------------
     // -----Create RangeImage from the PointCloud-----
     // -----------------------------------------------
     float noise_level = 0.1f;
     float min_range = 0.0f;
     int border_size = 1;
     pcl::RangeImage::Ptr range_image_ptr (new pcl::RangeImage);
     pcl::RangeImage& range_image = *range_image_ptr;
     range_image.createFromPointCloud (in, angular_resolution, pcl::deg2rad (360.0f), pcl::deg2rad (180.0f),
                                      scene_sensor_pose, coordinate_frame, noise_level, min_range, border_size);
     range_image.integrateFarRanges (far_ranges);
     if (setUnseenToMaxRange)
       range_image.setUnseenToMaxRange ();
     // --------------------------------------------
     // -----Open 3D viewer and add point cloud-----
     // --------------------------------------------
     pcl::visualization::PCLVisualizer viewerNarf ("3D Viewer NARF");
     viewerNarf.setBackgroundColor (1.0f, 1.0f, 1.0f);
     pcl::visualization::PointCloudColorHandlerCustom<pcl::PointWithRange> range_image_color_handler (range_image_ptr, 0.0f, 0.0f, 0.0f);
     viewerNarf.addPointCloud (range_image_ptr, range_image_color_handler, "range image");
     viewerNarf.setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "range image");
     viewerNarf.initCameraParameters ();
     //setViewerPose (viewerNarf, range_image.getTransformationToWorldSystem ());
     // --------------------------
     // -----Show range image-----
     // --------------------------
     pcl::visualization::RangeImageVisualizer range_image_widget ("Range image");
     if(range_image.empty()){cout << "range_image is empty"<< endl;}
     range_image_widget.showRangeImage (range_image);
     // --------------------------------
     // -----Extract NARF keypoints-----
     // --------------------------------
     pcl::RangeImageBorderExtractor range_image_border_extractor;
     pcl::NarfKeypoint narf_keypoint_detector (&range_image_border_extractor);
     narf_keypoint_detector.setRangeImage (&range_image);
     narf_keypoint_detector.getParameters ().support_size = support_size;
     narf_keypoint_detector.getParameters ().add_points_on_straight_edges = true;
     narf_keypoint_detector.getParameters ().distance_for_additional_points = 0.5;
     pcl::PointCloud<int> keypoint_indices;
     narf_keypoint_detector.compute (keypoint_indices);
     std::cout << "Found "<<keypoint_indices.size ()<<" key points.\n";
     // ----------------------------------------------
     // -----Show keypoints in range image widget-----
     // ----------------------------------------------
     //for (std::size_t i=0; i<keypoint_indices.size (); ++i)
       //range_image_widget.markPoint (keypoint_indices[i]%range_image.width,
                                     //keypoint_indices[i]/range_image.width);
     // -------------------------------------
     // -----Show keypoints in 3D viewer-----
     // -------------------------------------
     pcl::PointCloud<pcl::PointXYZ>::Ptr keypoints_ptr (new pcl::PointCloud<pcl::PointXYZ>);
     pcl::PointCloud<pcl::PointXYZ>& keypoints = *keypoints_ptr;
     keypoints.resize (keypoint_indices.size ());
     for (std::size_t i=0; i<keypoint_indices.size (); ++i)
       keypoints[i].getVector3fMap () = range_image[keypoint_indices[i]].getVector3fMap ();
 /*
     pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ> keypoints_color_handler (keypoints_ptr, 0, 255, 0);
     viewerNarf.addPointCloud<pcl::PointXYZ> (keypoints_ptr, keypoints_color_handler, "keypoints");
     viewerNarf.setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 7, "keypoints");
 */
     out = *keypoints_ptr;
     /*
     //--------------------
     // -----Main loop-----
     //--------------------
     while (!viewerNarf.wasStopped ())
     {
       range_image_widget.spinOnce ();  // process GUI events
       viewerNarf.spinOnce ();
       pcl_sleep(0.01);
     }
     */
 }
References range_image, and range_image_widget.
narfKeypointExtractionRgb()
void pclUtilitys::narfKeypointExtractionRgb (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
narfKeypointExtraction RGB input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 2033 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = in;
     //Parameter
     float angular_resolution = 0.008f;
     float support_size = 0.01f;//0.2
     pcl::RangeImage::CoordinateFrame coordinate_frame = pcl::RangeImage::CAMERA_FRAME;
     bool setUnseenToMaxRange = true;
     pcl::PointCloud<pcl::PointWithViewpoint> far_ranges;
     Eigen::Affine3f scene_sensor_pose (Eigen::Affine3f::Identity ());
     scene_sensor_pose = Eigen::Affine3f (Eigen::Translation3f (in.sensor_origin_[0],in.sensor_origin_[1],in.sensor_origin_[2])) * Eigen::Affine3f (in.sensor_orientation_);
     // -----------------------------------------------
     // -----Create RangeImage from the PointCloud-----
     // -----------------------------------------------
     float noise_level = 0.05f;
     float min_range = 0.02f;
     int border_size = 1;
     pcl::RangeImage::Ptr range_image_ptr (new pcl::RangeImage);
     pcl::RangeImage& range_image = *range_image_ptr;
     //range_image = &range_image_ptr;
     range_image.createFromPointCloud (in, angular_resolution, pcl::deg2rad (360.0f), pcl::deg2rad (180.0f),
                                      scene_sensor_pose, coordinate_frame, noise_level, min_range, border_size);
     range_image.integrateFarRanges (far_ranges);
     if (setUnseenToMaxRange)
       range_image.setUnseenToMaxRange ();
     /*
     // --------------------------------------------
     // -----Open 3D viewer and add point cloud-----
     // --------------------------------------------
     pcl::visualization::PCLVisualizer viewerNarf ("3D Viewer NARF");
     viewerNarf.setBackgroundColor (1.0f, 1.0f, 1.0f);
     pcl::visualization::PointCloudColorHandlerCustom<pcl::PointWithRange> range_image_color_handler (range_image_ptr, 0.0f, 0.0f, 0.0f);
     viewerNarf.addPointCloud (range_image_ptr, range_image_color_handler, "range image");
     viewerNarf.setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "range image");
     viewerNarf.initCameraParameters ();
     //setViewerPose (viewerNarf, range_image.getTransformationToWorldSystem ());
     // --------------------------
     // -----Show range image-----
     // --------------------------
     pcl::visualization::RangeImageVisualizer range_image_widget ("Range image");
     if(range_image.empty()){cout << "range_image is empty"<< endl;}
     range_image_widget.showRangeImage (range_image);
 */
     // --------------------------------
     // -----Extract NARF keypoints-----
     // --------------------------------
     pcl::RangeImageBorderExtractor range_image_border_extractor;
     pcl::NarfKeypoint narf_keypoint_detector (&range_image_border_extractor);
     narf_keypoint_detector.setRangeImage (&range_image);
     narf_keypoint_detector.getParameters ().support_size = support_size;
     narf_keypoint_detector.getParameters ().add_points_on_straight_edges = true;
     narf_keypoint_detector.getParameters ().distance_for_additional_points = 0.5;
     pcl::PointCloud<int> keypoint_indices;
     narf_keypoint_detector.compute (keypoint_indices);
     std::cout << "Found "<<keypoint_indices.size ()<<" key points.\n";
     // -------------------------------------
     // -----Show keypoints in 3D viewer-----
     // -------------------------------------
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr keypoints_ptr (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>& keypoints = *keypoints_ptr;
     keypoints.resize (keypoint_indices.size ());
     for (std::size_t i=0; i<keypoint_indices.size (); ++i)
       keypoints[i].getVector3fMap () = range_image[keypoint_indices[i]].getVector3fMap ();
     out = *keypoints_ptr;
 }
References range_image.
normalsVis()
pcl::visualization::PCLVisualizer::Ptr pclUtilitys::normalsVis (pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloud, pcl::PointCloud< pcl::Normal >::ConstPtr normals)
visualisation normals from cloud input:
Parameters
pcl::PointCloud<pcl::PointXYZRGB>::ConstPtr cloud, pcl::PointCloud<pcl::Normal>::ConstPtr normals
Returns
pcl::visualization::PCLVisualizer::Ptr
Definition at line 1310 of file pclUtilitys.cpp.
 {
   // --------------------------------------------------------
   // -----Open 3D viewer and add point cloud and normals-----
   // --------------------------------------------------------
   pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
   viewer->setBackgroundColor (0, 0, 0);
   pcl::visualization::PointCloudColorHandlerRGBField<pcl::PointXYZRGB> rgb(cloud);
   viewer->addPointCloud<pcl::PointXYZRGB> (cloud, rgb, "sample cloud");
   viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "sample cloud");
   viewer->addPointCloudNormals<pcl::PointXYZRGB, pcl::Normal> (cloud, normals, 10, 0.05, "normals");
   viewer->addCoordinateSystem (1.0);
   viewer->initCameraParameters ();
   return (viewer);
 }
References viewer.
Referenced by pclApp::testViewsWithNormals().
passTroughFilter()
void pclUtilitys::passTroughFilter (const pcl::PointCloud< pcl::PointXYZ > & cloud, pcl::PointCloud< pcl::PointXYZ > & cloudOut, float minfl, float maxfl)
cliping z (depth) based input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& cloud, float distanceThreshold, float minfl, float maxfl output:
pcl::PointCloud<pcl::PointXYZ>& cloudOut
Returns
void
Definition at line 853 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = cloud;
     // Create the filtering object
     pcl::PassThrough<pcl::PointXYZ> pass;
     pass.setInputCloud(cloudIn);
     pass.setFilterFieldName ("z");
     pass.setFilterLimits (minfl, maxfl);
     //pass.setNegative (true);
     pass.filter(cloudOut);
 }
passTroughFilterRgb()
void pclUtilitys::passTroughFilterRgb (const pcl::PointCloud< pcl::PointXYZRGB > & cloud, pcl::PointCloud< pcl::PointXYZRGB > & cloudOut, float minfl, float maxfl)
cliping z (depth) based input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& cloud, float distanceThreshold, float minfl, float maxfl output:
pcl::PointCloud<pcl::PointXYZRGB>& cloudOut
Returns
void
Definition at line 875 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = cloud;
     // Create the filtering object
     pcl::PassThrough<pcl::PointXYZRGB> pass;
     pass.setInputCloud(cloudIn);
     pass.setFilterFieldName ("z");
     pass.setFilterLimits (minfl, maxfl);
     //pass.setNegative (true);
     pass.filter(cloudOut);
 }
radiusOutlierRemovalhelpFilter()
void pclUtilitys::radiusOutlierRemovalhelpFilter (const pcl::PointCloud< pcl::PointXYZ > & in, pcl::PointCloud< pcl::PointXYZ > & out, int mode, float radius, int numbersOfNeighbors)
radiusOutlierRemovalhelpFilter input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in, float radius, int numbersOfNeighbors output:
pcl::PointCloud<pcl::PointXYZ>& out
Returns
void
Definition at line 1199 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = in;
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudOutTemp (new pcl::PointCloud<pcl::PointXYZ>);
     //*cloudIn = cloud;
     //pcl::copyPointCloud(cloud, *cloudIn);
     //int mode = 1; int numbersOfNeighbors = 2; float radius = 0.8;
     if (mode == 0){
       pcl::RadiusOutlierRemoval<pcl::PointXYZ> outrem;
       // build the filter
       outrem.setInputCloud(cloudIn);
       outrem.setRadiusSearch(radius); //0.8
       outrem.setMinNeighborsInRadius (numbersOfNeighbors);  //2
       outrem.setKeepOrganized(true);
       // apply filter
       outrem.filter(out);
       //pcl::copyPointCloud(*cloudOutTemp, out);
     }
     else if (mode == 1){
       // build the condition
       pcl::ConditionAnd<pcl::PointXYZ>::Ptr range_cond (new
         pcl::ConditionAnd<pcl::PointXYZ> ());
       range_cond->addComparison (pcl::FieldComparison<pcl::PointXYZ>::ConstPtr (new
         pcl::FieldComparison<pcl::PointXYZ> ("z", pcl::ComparisonOps::GT, 0.0)));
       range_cond->addComparison (pcl::FieldComparison<pcl::PointXYZ>::ConstPtr (new
         pcl::FieldComparison<pcl::PointXYZ> ("z", pcl::ComparisonOps::LT, 0.8)));
       // build the filter
       pcl::ConditionalRemoval<pcl::PointXYZ> condrem;
       condrem.setCondition (range_cond);
       condrem.setInputCloud (cloudIn);
       condrem.setKeepOrganized(true);
       // apply filter
       condrem.filter(out);
       //pcl::copyPointCloud(*cloudOutTemp, cloudOut);
     }
 }
reconTwoPcl()
void pclUtilitys::reconTwoPcl (const pcl::PointCloud< pcl::PointXYZ > & in1, const pcl::PointCloud< pcl::PointXYZ > & in2, Eigen::Matrix4f & tform)
reconTwoPcl input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& in1, const pcl::PointCloud<pcl::PointXYZ>& in2 output:
Eigen::Matrix4f& tform
Returns
void
Definition at line 2772 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr pclfilter1 (new pcl::PointCloud<pcl::PointXYZ>);
     pcl::PointCloud<pcl::PointXYZ>::Ptr pclfilter2 (new pcl::PointCloud<pcl::PointXYZ>);
     voxelGrid(in1, *pclfilter1, 0.020f);
     voxelGrid(in2, *pclfilter2, 0.020f);
     pcl::PointCloud<pcl::PointNormal>::Ptr src_normals_ptr (new pcl::PointCloud<pcl::PointNormal>);
     pcl::PointCloud<pcl::PointNormal>::Ptr tar_normals_ptr (new pcl::PointCloud<pcl::PointNormal>);
     getNormalsFromCloud(*pclfilter1, *src_normals_ptr);
     getNormalsFromCloud(*pclfilter2, *tar_normals_ptr);
     pcl::PointCloud<pcl::PointWithScale>::Ptr src_keypoints_ptr (new pcl::PointCloud<pcl::PointWithScale>);
     keypointExtractionSIFT(*pclfilter1, src_normals_ptr, *src_keypoints_ptr);   //voxel grid error - why ever
     pcl::PointCloud<pcl::PointWithScale>::Ptr tar_keypoints_ptr (new pcl::PointCloud<pcl::PointWithScale>);
     keypointExtractionSIFT(*pclfilter2, tar_normals_ptr, *tar_keypoints_ptr);   //voxel grid error - why ever
     //Eigen::Matrix4f tform = Eigen::Matrix4f::Identity();
     extractFPFHfromKeypoints(*pclfilter1, *pclfilter2,
                                      *src_keypoints_ptr, *tar_keypoints_ptr,
                                      *src_normals_ptr, *tar_normals_ptr, tform);
 }
References extractFPFHfromKeypoints(), getNormalsFromCloud(), keypointExtractionSIFT(), and voxelGrid().
Referenced by pclApp::testPclRgbObjectDetectionPipe01().
refineAlignment()
Eigen::Matrix4f pclUtilitys::refineAlignment (const ICPPointCloudPtr & source_points, const ICPPointCloudPtr & target_points, const Eigen::Matrix4f initial_alignment, float max_correspondence_distance, float outlier_rejection_threshold, float transformation_epsilon, float max_iterations) private
refineAlignment input:
Parameters
const ICPPointCloudPtr & source_points, const ICPPointCloudPtr & target_points, const Eigen::Matrix4f initial_alignment, float max_correspondence_distance, float outlier_rejection_threshold, float transformation_epsilon, float max_iterations
Returns
Eigen::Matrix4f
Definition at line 2836 of file pclUtilitys.cpp.
{
   pcl::IterativeClosestPoint<ICPPointT, ICPPointT> icp;
   icp.setMaxCorrespondenceDistance (max_correspondence_distance);
   icp.setRANSACOutlierRejectionThreshold (outlier_rejection_threshold);
   icp.setTransformationEpsilon (transformation_epsilon);
   icp.setMaximumIterations (max_iterations);
   ICPPointCloudPtr source_points_transformed (new ICPPointCloud);
   pcl::transformPointCloud (*source_points, *source_points_transformed, initial_alignment);
   icp.setInputSource (source_points_transformed);
   icp.setInputTarget (target_points);
   ICPPointCloud registration_output;
   icp.align (registration_output);
   return (icp.getFinalTransformation () * initial_alignment);
 }
Referenced by extractFPFHfromKeypoints().
rgbVis()
pcl::visualization::PCLVisualizer::Ptr pclUtilitys::rgbVis (pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloud)
visualisation from RGB cloud input:
Parameters
pcl::PointCloud<pcl::PointXYZRGB>::ConstPtr cloud
Returns
pcl::visualization::PCLVisualizer::Ptr
Definition at line 1265 of file pclUtilitys.cpp.
 {
   // --------------------------------------------
   // -----Open 3D viewer and add point cloud-----
   // --------------------------------------------
   pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
   viewer->setBackgroundColor (0, 0, 0);
   pcl::visualization::PointCloudColorHandlerRGBField<pcl::PointXYZRGB> rgb(cloud);
   viewer->addPointCloud<pcl::PointXYZRGB> (cloud, rgb, "sample cloud");
   viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 3, "sample cloud");
   viewer->addCoordinateSystem (1.0);
   viewer->initCameraParameters ();
   return (viewer);
 }
References viewer.
Referenced by pclApp::testLineCreater().
rgbVisDouble()
pcl::visualization::PCLVisualizer::Ptr pclUtilitys::rgbVisDouble (pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloud, pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloud2)
visualisation from two RGB clouds input:
Parameters
pcl::PointCloud<pcl::PointXYZRGB>::ConstPtr cloud, pcl::PointCloud<pcl::PointXYZRGB>::ConstPtr cloud2
Returns
pcl::visualization::PCLVisualizer::Ptr
Definition at line 1287 of file pclUtilitys.cpp.
 {
   // --------------------------------------------
   // -----Open 3D viewer and add point cloud-----
   // --------------------------------------------
   pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
   viewer->setBackgroundColor (0, 0, 0);
   pcl::visualization::PointCloudColorHandlerRGBField<pcl::PointXYZRGB> rgb(cloud);
   viewer->addPointCloud<pcl::PointXYZRGB> (cloud, rgb, "sample cloud");
   viewer->addPointCloud<pcl::PointXYZRGB> (cloud2, rgb, "sample cloud2");
   viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 3, "sample cloud");
   viewer->addCoordinateSystem (1.0);
   viewer->initCameraParameters ();
   return (viewer);
 }
References viewer.
rotateX()
void pclUtilitys::rotateX (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out, float radiantAngle)
rotate PCL over X axis input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in, float radiantAngle output:
pcl::PointCloud<pcl::PointXYZRGB>& out,
Returns
void
Definition at line 2273 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = in;
     Eigen::Affine3f transform_2 = Eigen::Affine3f::Identity();
     transform_2.rotate (Eigen::AngleAxisf (radiantAngle, Eigen::Vector3f::UnitX()));
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr transformed_cloud (new pcl::PointCloud<pcl::PointXYZRGB> ());
     pcl::transformPointCloud<pcl::PointXYZRGB> (*cloudIn, out, transform_2);
 }
Referenced by setWallrelativeToOriginXY().
rotateY()
void pclUtilitys::rotateY (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out, float radiantAngle)
rotate PCL over Y axis input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in, float radiantAngle output:
pcl::PointCloud<pcl::PointXYZRGB>& out,
Returns
void
Definition at line 2290 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = in;
     Eigen::Affine3f transform_2 = Eigen::Affine3f::Identity();
     transform_2.rotate (Eigen::AngleAxisf (radiantAngle, Eigen::Vector3f::UnitY()));
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr transformed_cloud (new pcl::PointCloud<pcl::PointXYZRGB> ());
     pcl::transformPointCloud<pcl::PointXYZRGB> (*cloudIn, out, transform_2);
 }
Referenced by setWallrelativeToOriginXY().
rotateZ()
void pclUtilitys::rotateZ (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out, float radiantAngle)
rotate PCL over Z axis input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in, float radiantAngle output:
pcl::PointCloud<pcl::PointXYZRGB>& out,
Returns
void
Definition at line 2308 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = in;
     Eigen::Affine3f transform_2 = Eigen::Affine3f::Identity();
     transform_2.rotate (Eigen::AngleAxisf (radiantAngle, Eigen::Vector3f::UnitZ()));
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr transformed_cloud (new pcl::PointCloud<pcl::PointXYZRGB> ());
     pcl::transformPointCloud<pcl::PointXYZRGB> (*cloudIn, out, transform_2);
 }
setPclRGBColor()
void pclUtilitys::setPclRGBColor (pcl::PointCloud< pcl::PointXYZRGB > & in, float r, float g, float b)
set color for this PCL input:
Parameters
pcl::PointCloud<pcl::PointXYZRGB>& in, float red, float green, float blue output:
pcl::PointCloud<pcl::PointXYZRGB>& in
Returns
void
Definition at line 344 of file pclUtilitys.cpp.
{
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         in.points[i].b = b;
         in.points[i].g = g;
         in.points[i].r = r;
         i++;
     }
 }
setViewerPose()
void pclUtilitys::setViewerPose (pcl::visualization::PCLVisualizer & viewer, const Eigen::Affine3f & viewer_pose)
set viewer pose input:
Parameters
pcl::visualization::PCLVisualizer& viewer, const Eigen::Affine3f& viewer_pose
Returns
void
Definition at line 1461 of file pclUtilitys.cpp.
 {
   Eigen::Vector3f pos_vector = viewer_pose * Eigen::Vector3f(0, 0, 0);
   Eigen::Vector3f look_at_vector = viewer_pose.rotation () * Eigen::Vector3f(0, 0, 1) + pos_vector;
   Eigen::Vector3f up_vector = viewer_pose.rotation () * Eigen::Vector3f(0, -1, 0);
   viewer.setCameraPosition (pos_vector[0], pos_vector[1], pos_vector[2],
                             look_at_vector[0], look_at_vector[1], look_at_vector[2],
                             up_vector[0], up_vector[1], up_vector[2]);
 }
References viewer.
setWallrelativeToOriginXY()
void pclUtilitys::setWallrelativeToOriginXY (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
set wall relative to detected origin XY input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 46 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr rawWallPlanePCL (new pcl::PointCloud<pcl::PointXYZRGB>);
     const float range = 0.4;
     float minX = range * (-1);
     float maxX = range;
     float minY = range * (-1);
     float maxY = range;
     int i=0;
     int imax = in.points.size();
     while(i<imax){
         if((in.points[i].x > minX)&&(in.points[i].x < maxX)&&
         (in.points[i].y > minY)&&(in.points[i].y < maxY)
         ){
             pcl::PointXYZRGB bufferPoint;
             bufferPoint.x = in.points[i].x;
             bufferPoint.y = in.points[i].y;
             bufferPoint.z = in.points[i].z;
             bufferPoint.r = in.points[i].r;
             bufferPoint.g = in.points[i].g;
             bufferPoint.b = in.points[i].b;
             rawWallPlanePCL->push_back(bufferPoint);
         }
         i++;
     }
     pcl::PointCloud<pcl::PointXYZ>::Ptr wallPlaneFil (new pcl::PointCloud<pcl::PointXYZ>);
     convertPtrXYZRGBtoXYZ(*rawWallPlanePCL, wallPlaneFil);
     //radiusOutlierRemovalhelpFilter(*wallPlaneFil, *wallPlaneFil, 0, 0.22, 600);
     //radiusOutlierRemovalhelpFilter(*wallPlaneFil, *wallPlaneFil, 0, 0.4, 300);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr outPcl (new pcl::PointCloud<pcl::PointXYZRGB>);
     this->convertPtrXYZtoXYZRGB(*wallPlaneFil, outPcl);
     extractPlaneFromCloudRgb(*outPcl, *outPcl, false);
     float deltaYup = 0.2;
     float rangeXLimit1 = 0.05;
     float rangeXLimit2 = 0.15;
     float rangeYLimit1 = 0.12;
     float rangeYLimit2 = 0.18;
     float rangeY2Limit1 = rangeYLimit1 + deltaYup;
     float rangeY2Limit2 = rangeYLimit2 + deltaYup;
     //side A
     double summSideA = 0;
     long int summSideACounter = 0;
     double summSideB = 0;
     long int summSideBCounter = 0;
     double summSideC = 0;
     long int summSideCCounter = 0;
     int j=0;
     int jmax=outPcl->points.size();
     while(j<jmax){
         outPcl->points[j].r = 160;
         outPcl->points[j].g = 160;
         outPcl->points[j].b = 160;
         //side A
         if((outPcl->points[j].x > rangeXLimit1)&&(outPcl->points[j].x < rangeXLimit2)&&
            (outPcl->points[j].y > rangeYLimit1)&&(outPcl->points[j].y < rangeYLimit2)
         ){
             summSideA = summSideA + outPcl->points[j].z;
             summSideACounter++;
             outPcl->points[j].r = 255;
             outPcl->points[j].g = 0;
             outPcl->points[j].b = 0;
         }
         //side B
         if((outPcl->points[j].x > -rangeXLimit2)&&(outPcl->points[j].x < -rangeXLimit1)&&
            (outPcl->points[j].y > rangeYLimit1)&&(outPcl->points[j].y < rangeYLimit2)
         ){
             summSideB = summSideB + outPcl->points[j].z;
             summSideBCounter++;
             outPcl->points[j].r = 0;
             outPcl->points[j].g = 255;
             outPcl->points[j].b = 0;
         }
         //upper side
         if((outPcl->points[j].x > -rangeXLimit2)&&(outPcl->points[j].x < -rangeXLimit1)&&
            (outPcl->points[j].y > rangeY2Limit1)&&(outPcl->points[j].y < rangeY2Limit2)
         ){
             summSideC = summSideC + outPcl->points[j].z;
             summSideCCounter++;
             outPcl->points[j].r = 0;
             outPcl->points[j].g = 0;
             outPcl->points[j].b = 255;
         }
         if(j==jmax-1){
             //cout << "check" << endl;
             if(summSideACounter == 0){
                 cout << "Counter A error ..." << endl;
                 cout << " rangeXLimit1:" << rangeXLimit1 << " rangeXLimit2:" << rangeXLimit2 << endl;
                 cout << " rangeYLimit1:" << rangeYLimit1 << " rangeYLimit2:" << rangeYLimit2 << endl;
                 rangeXLimit1 = rangeXLimit1 + 0.01;
                 rangeXLimit2 = rangeXLimit2 + 0.01;
                 if(rangeXLimit1 > 10){
                     rangeXLimit1 = rangeXLimit1 - 10;
                     rangeXLimit2 = rangeXLimit2 - 10;
                 }
                 //rangeYLimit1 = rangeYLimit1 - 0.01;
                 //rangeYLimit2 = rangeYLimit2 - 0.01;
                 if(rangeYLimit1 > 10){j = jmax;}
                 j = 0;
             }
             if(summSideBCounter == 0){
                 cout << "Counter B error ..." << endl;
                 cout << " rangeXLimit1:" << rangeXLimit1 << " rangeXLimit2:" << rangeXLimit2 << endl;
                 cout << " rangeYLimit1:" << rangeYLimit1 << " rangeYLimit2:" << rangeYLimit2 << endl;
                 rangeYLimit1 = rangeYLimit1 - 0.01;
                 rangeYLimit2 = rangeYLimit2 - 0.01;
                 if(rangeYLimit1 > 10){j = jmax;}
                 j = 0;
             }
             if(summSideBCounter == 0){
                 cout << "Counter C error ..." << endl;
                 cout << " rangeXLimit1:" << rangeXLimit1 << " rangeXLimit2:" << rangeXLimit2 << endl;
                 cout << " rangeYLimit1:" << rangeYLimit1 << " rangeYLimit2:" << rangeYLimit2 << endl;
                 rangeYLimit1 = rangeYLimit1 - 0.01;
                 rangeYLimit2 = rangeYLimit2 - 0.01;
                 if(rangeYLimit1 > 10){j = jmax;}
                 j = 0;
             }
         }
     j++;
     }
     summSideA = abs(summSideA / (float)summSideACounter);
     cout << "nr: " << summSideACounter << " summSideA: " << summSideA << endl;
     summSideB = abs(summSideB / (float)summSideBCounter);
     cout << "nr: " << summSideBCounter  << " summSideB: " << summSideB << endl;
     summSideC = abs(summSideC / (float)summSideCCounter);
     cout << "nr: " << summSideCCounter << " summSideC: " << summSideC << endl;
     float deltaZ = summSideA-summSideB;
     cout << "deltaZ: " << deltaZ << endl;
     float deltaZx = summSideB-summSideC;
     cout << "deltaZx: " << deltaZx << endl;
     float transZ;
     if(summSideA > summSideB){
         transZ = summSideA - (abs(deltaZ)*0.5);
         translationXYZ(*outPcl, *outPcl, 0, 0, transZ);
     }else{
         transZ = summSideB - (abs(deltaZ)*0.5);
         translationXYZ(*outPcl, *outPcl, 0, 0, transZ);
     }
     //calculate rotation for Y axis
     float deltaX = 0.2;
     float hyp = (float)sqrt( (deltaX*deltaX)+(deltaZ*deltaZ) );
     cout << "hyp: " << hyp << endl;
     double alphaPre = deltaZ/hyp;
     float alpha = (float)asin(alphaPre);
     rotateY(*outPcl, *outPcl, -alpha);
     //calculate rotation for X axis
     float hypY = (float)sqrt( (deltaYup*deltaYup)+(deltaZx*deltaZx) );
     cout << "hypY: " << hypY << endl;
     double betaPre = deltaZx/hypY;
     float beta = (float)asin(betaPre);
     rotateX(*outPcl, *outPcl, -beta);
 /*
     if(summSideA > summSideB){
         translationXYZ(*outPcl, *outPcl, 0, 0, -transZ);
     }else{
         translationXYZ(*outPcl, *outPcl, 0, 0, -transZ);
     }
 */
     alpha = (alpha/M_PI)*(float)180.0;
     cout << "alpha: " << alpha << endl;
     beta = (beta/M_PI)*(float)180.0;
     cout << "beta: " << beta << endl;
     out = *outPcl;
 }
References convertPtrXYZRGBtoXYZ(), convertPtrXYZtoXYZRGB(), extractPlaneFromCloudRgb(), rotateX(), rotateY(), and translationXYZ().
Referenced by pclApp::testTranformOrientationToPlane().
simpleVis()
pcl::visualization::PCLVisualizer::Ptr pclUtilitys::simpleVis (pcl::PointCloud< pcl::PointXYZ >::ConstPtr cloud)
radiusOutlierRemovalhelpFilter input:
Parameters
pcl::PointCloud<pcl::PointXYZ>::ConstPtr cloud
Returns
pcl::visualization::PCLVisualizer::Ptr
Definition at line 1244 of file pclUtilitys.cpp.
 {
   // --------------------------------------------
   // -----Open 3D viewer and add point cloud-----
   // --------------------------------------------
   pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
   viewer->setBackgroundColor (0, 0, 0);
   viewer->addPointCloud<pcl::PointXYZ> (cloud, "sample cloud");
   viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "sample cloud");
   viewer->addCoordinateSystem (1.0);
   viewer->initCameraParameters ();
   return (viewer);
 }
References viewer.
statisticalOutlierRemovalFilter()
void pclUtilitys::statisticalOutlierRemovalFilter (const pcl::PointCloud< pcl::PointXYZ > & cloud, pcl::PointCloud< pcl::PointXYZ > & cloudOut, int numbersOfNeighbors, float deviationMul)
statisticalOutlierRemovalFilter input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& cloud, float distanceThreshold, int numbersOfNeighbors, float deviationMul output:
pcl::PointCloud<pcl::PointXYZ>& cloudOut
Returns
void
Definition at line 896 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = cloud;
     // Create the filtering object
     pcl::StatisticalOutlierRemoval<pcl::PointXYZ> sor;
     sor.setInputCloud (cloudIn);
     sor.setMeanK(numbersOfNeighbors);//50
     sor.setStddevMulThresh(deviationMul);//1.0
     sor.filter(cloudOut);
 }
statisticalOutlierRemovalFilterRgb()
void pclUtilitys::statisticalOutlierRemovalFilterRgb (const pcl::PointCloud< pcl::PointXYZRGB > & cloud, pcl::PointCloud< pcl::PointXYZRGB > & cloudOut, int numbersOfNeighbors, float deviationMul)
statisticalOutlierRemovalFilterRgb input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& cloud, float distanceThreshold, int numbersOfNeighbors, float deviationMul output:
pcl::PointCloud<pcl::PointXYZRGB>& cloudOut
Returns
void
Definition at line 944 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = cloud;
     // Create the filtering object
     pcl::StatisticalOutlierRemoval<pcl::PointXYZRGB> sor;
     sor.setInputCloud (cloudIn);
     sor.setMeanK(numbersOfNeighbors);//50
     sor.setStddevMulThresh(deviationMul);//1.0
     sor.filter(cloudOut);
 }
Referenced by pclApp::testViewsWithNormals().
testDoEuclideanClusteringRgb()
void pclUtilitys::testDoEuclideanClusteringRgb (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out)
test do euclidean clustering with RGB cloud input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 1605 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = in;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud_f (new pcl::PointCloud<pcl::PointXYZRGB>);
     // Creating the KdTree object for the search method of the extraction
     pcl::search::KdTree<pcl::PointXYZRGB>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZRGB>);
     tree->setInputCloud (cloudIn);
     //extracting
     std::vector<pcl::PointIndices> cluster_indices;
     pcl::EuclideanClusterExtraction<pcl::PointXYZRGB> ec;
     ec.setClusterTolerance (0.01); // 0.02 = 2cm
     ec.setMinClusterSize (60);
     ec.setMaxClusterSize (4000);
     ec.setSearchMethod (tree);
     ec.setInputCloud (cloudIn);
     ec.extract (cluster_indices);
     cout << "found clusters: " << cluster_indices.size() << endl;
     int comidx = 0;
     int idx=0;
     int idxmax=0;
     int i=0;
     int imax=cluster_indices.size();
     while(i<imax){
         idx=0;
         idxmax = cluster_indices[i].indices.size();
         cout << "  clusters nr: " << i << " size: " << idxmax << endl;
         while(idx<idxmax){
             if(idxmax > 120){
                 out.push_back((*cloudIn)[comidx]);
             }
         idx++;
         comidx++;
         }
     i++;
     }
 }
testRandomSampleConsensus()
void pclUtilitys::testRandomSampleConsensus ()
test random sample consensus
Returns
void
if (pcl::console::find_argument (argc, argv, "-s") >= 0 || pcl::console::find_argument (argc, argv, "-sf") >= 0) { (*cloud)[i].x = 1024 * rand () / (RAND_MAX + 1.0); (*cloud)[i].y = 1024 * rand () / (RAND_MAX + 1.0); if (i % 5 == 0) (*cloud)[i].z = 1024 * rand () / (RAND_MAX + 1.0); else if(i % 2 == 0) (*cloud)[i].z = sqrt(1 - ((*cloud)[i].x * (*cloud)[i].x)
((*cloud)[i].y * (*cloud)[i].y)); else (*cloud)[i].z = - sqrt(1 - ((*cloud)[i].x * (*cloud)[i].x)
((*cloud)[i].y * (*cloud)[i].y)); } else {
Definition at line 1789 of file pclUtilitys.cpp.
{
       // initialize PointClouds
       pcl::PointCloud<pcl::PointXYZ>::Ptr cloud (new pcl::PointCloud<pcl::PointXYZ>);
       pcl::PointCloud<pcl::PointXYZ>::Ptr final (new pcl::PointCloud<pcl::PointXYZ>);
       // populate our PointCloud with points
       cloud->width    = 500;
       cloud->height   = 1;
       cloud->is_dense = false;
       cloud->points.resize (cloud->width * cloud->height);
       long int maxP = cloud->size();
       //for (pcl::index_t i = 0; i < static_cast<pcl::index_t>(cloud->size ()); ++i)
       for (long int i = 0; i < maxP; ++i)
       {
           (*cloud)[i].x = 1024 * rand () / (RAND_MAX + 1.0);
           (*cloud)[i].y = 1024 * rand () / (RAND_MAX + 1.0);
           if( i % 2 == 0)
             (*cloud)[i].z = 1024 * rand () / (RAND_MAX + 1.0);
           else
             (*cloud)[i].z = -1 * ((*cloud)[i].x + (*cloud)[i].y);
         }
      // }
       std::vector<int> inliers;
       // created RandomSampleConsensus object and compute the appropriated model
       pcl::SampleConsensusModelSphere<pcl::PointXYZ>::Ptr
         model_s(new pcl::SampleConsensusModelSphere<pcl::PointXYZ> (cloud));
       pcl::SampleConsensusModelPlane<pcl::PointXYZ>::Ptr
         model_p (new pcl::SampleConsensusModelPlane<pcl::PointXYZ> (cloud));
         pcl::RandomSampleConsensus<pcl::PointXYZ> ransac (model_p);
         ransac.setDistanceThreshold (.01);
         ransac.computeModel();
         ransac.getInliers(inliers);
       // copies all inliers of the model computed to another PointCloud
       pcl::copyPointCloud (*cloud, inliers, *final);
       // creates the visualization object and adds either our original cloud or all of the inliers
       // depending on the command line arguments specified.
      // pcl::visualization::PCLVisualizer::Ptr viewer;
       pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
       viewer->setBackgroundColor (0, 0, 0);
       viewer->addPointCloud<pcl::PointXYZ> (cloud, "sample cloud");
       viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 3, "sample cloud");
       //viewer->addCoordinateSystem (1.0, "global");
       viewer->initCameraParameters ();
       while (!viewer->wasStopped ())
       {
         viewer->spinOnce (100);
         std::this_thread::sleep_for(100ms);
       }
 }
References viewer.
translationXYZ()
void pclUtilitys::translationXYZ (const pcl::PointCloud< pcl::PointXYZRGB > & in, pcl::PointCloud< pcl::PointXYZRGB > & out, float x, float y, float z)
draw axis PCL input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& in float x, float y, float z output:
pcl::PointCloud<pcl::PointXYZRGB>& out
Returns
void
Definition at line 308 of file pclUtilitys.cpp.
{
     Eigen::Matrix4f transform_1 = Eigen::Matrix4f::Identity();
     transform_1 (0,3) = x;
     transform_1 (1,3) = y;
     transform_1 (2,3) = z;
     pcl::transformPointCloud (in, out, transform_1);
 }
References z.
Referenced by setWallrelativeToOriginXY().
viewportsDiffVis()
pcl::visualization::PCLVisualizer::Ptr pclUtilitys::viewportsDiffVis (pcl::PointCloud< pcl::PointXYZ >::ConstPtr cloud1, pcl::PointCloud< pcl::PointXYZ >::ConstPtr cloud2)
visualisation via viewports two cloud without color input:
Parameters
pcl::PointCloud<pcl::PointXYZ>::ConstPtr cloud1, pcl::PointCloud<pcl::PointXYZ>::ConstPtr cloud2
Returns
pcl::visualization::PCLVisualizer::Ptr
Definition at line 1406 of file pclUtilitys.cpp.
{
       rootPclSize = (int)cloud1->size();
       rootPclResultSize = (int)cloud2->size();
       // --------------------------------------------------------
       // ----- Show the differenze between tow PCL          -----
       // --------------------------------------------------------
       pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
       viewer->initCameraParameters ();
       int v1(0);
       viewer->createViewPort(0.0, 0.0, 0.5, 1.0, v1);
       viewer->setBackgroundColor (0, 0, 0, v1);
       std::string strTextv1 = std::to_string(rootPclSize) + std::string(" Points");
       viewer->addText(strTextv1, 10, 10, "v1 text", v1);
       viewer->addPointCloud<pcl::PointXYZ> (cloud1, "sample cloud1", v1);
       int v2(0);
       viewer->createViewPort(0.5, 0.0, 1.0, 1.0, v2);
       viewer->setBackgroundColor (0.3, 0.3, 0.3, v2);
       std::string strTextv2 = std::to_string(rootPclResultSize) + std::string(" Points");
       viewer->addText(strTextv2, 10, 10, "v2 text", v2);
       viewer->addPointCloud<pcl::PointXYZ> (cloud2, "sample cloud2", v2);
       viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "sample cloud1");
       viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "sample cloud2");
       viewer->addCoordinateSystem (1.0);
       //viewer->initCameraParameters ();
       return (viewer);
 }
References rootPclResultSize, rootPclSize, and viewer.
viewportsDiffVisRgb()
pcl::visualization::PCLVisualizer::Ptr pclUtilitys::viewportsDiffVisRgb (pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloudRgb1, pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloudRgb2)
visualisation via viewports two RGB cloud input:
Parameters
pcl::PointCloud<pcl::PointXYZRGB>::ConstPtr cloudRgb1, pcl::PointCloud<pcl::PointXYZRGB>::ConstPtr cloudRgb2
Returns
pcl::visualization::PCLVisualizer::Ptr
Definition at line 1365 of file pclUtilitys.cpp.
{
       rootPclRgbSize = (int)cloudRgb1->size();
       rootPclRgbResultSize = (int)cloudRgb2->size();
       // --------------------------------------------------------
       // ----- Show the differenze between tow PCL          -----
       // --------------------------------------------------------
       pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
       viewer->initCameraParameters ();
       int v1(0);
       viewer->createViewPort(0.0, 0.0, 0.5, 1.0, v1);
       viewer->setBackgroundColor (0, 0, 0, v1);
       //viewer->addText("Radius: 0.01", 10, 10, "v1 text", v1);
       std::string strTextv1 = std::to_string(rootPclRgbSize) + std::string(" Points");
       viewer->addText(strTextv1, 10, 10, "v1 text", v1);
       pcl::visualization::PointCloudColorHandlerRGBField<pcl::PointXYZRGB> rgb(cloudRgb1);
       viewer->addPointCloud<pcl::PointXYZRGB> (cloudRgb1, rgb, "sample cloud1", v1);
       int v2(0);
       viewer->createViewPort(0.5, 0.0, 1.0, 1.0, v2);
       viewer->setBackgroundColor (0.9, 0.9, 0.9, v2);
       //viewer->addText("Radius: 0.1", 10, 10, "v2 text", v2);
       std::string strTextv2 = std::to_string(rootPclRgbResultSize) + std::string(" Points");
       viewer->addText(strTextv2, 10, 10, "v2 text", v2);
       pcl::visualization::PointCloudColorHandlerRGBField<pcl::PointXYZRGB> rgb2(cloudRgb2);
       viewer->addPointCloud<pcl::PointXYZRGB> (cloudRgb2, rgb2, "sample cloud2", v2);
       viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "sample cloud1");
       viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "sample cloud2");
       viewer->addCoordinateSystem (1.0);
       return (viewer);
 }
References rootPclRgbResultSize, rootPclRgbSize, and viewer.
Referenced by pclApp::testPclRgbObjectDetectionPipe01(), pclApp::testTranformOrientationToPlane(), and pclApp::testViewsWithViewports().
viewportsVis()
pcl::visualization::PCLVisualizer::Ptr pclUtilitys::viewportsVis (pcl::PointCloud< pcl::PointXYZ >::ConstPtr cloud, pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr cloudRgb)
visualisation via viewports cloud without and RGB cloud input:
Parameters
pcl::PointCloud<pcl::PointXYZ>::ConstPtr cloud, pcl::PointCloud<pcl::PointXYZRGB>::ConstPtr cloudRgb
Returns
pcl::visualization::PCLVisualizer::Ptr
Definition at line 1333 of file pclUtilitys.cpp.
 {
   pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
   viewer->initCameraParameters ();
   int v1(0);
   viewer->createViewPort(0.0, 0.0, 0.5, 1.0, v1);
   viewer->setBackgroundColor (0, 0, 0, v1);
   viewer->addText("Radius: 0.01", 10, 10, "v1 text", v1);
   viewer->addPointCloud<pcl::PointXYZ> (cloud, "sample cloud1", v1);
   int v2(0);
   viewer->createViewPort(0.5, 0.0, 1.0, 1.0, v2);
   viewer->setBackgroundColor (0.3, 0.3, 0.3, v2);
   viewer->addText("Radius: 0.1", 10, 10, "v2 text", v2);
   pcl::visualization::PointCloudColorHandlerRGBField<pcl::PointXYZRGB> rgb(cloudRgb);
   viewer->addPointCloud<pcl::PointXYZRGB> (cloudRgb, rgb, "sample cloud2", v2);
   viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "sample cloud1");
   viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "sample cloud2");
   viewer->addCoordinateSystem (1.0);
   return (viewer);
 }
References viewer.
voxelGrid()
void pclUtilitys::voxelGrid (const pcl::PointCloud< pcl::PointXYZ > & cloud, pcl::PointCloud< pcl::PointXYZ > & cloudOut, float distanceThreshold)
voxel grid input:
Parameters
const pcl::PointCloud<pcl::PointXYZ>& cloud, float distanceThreshold output:
pcl::PointCloud<pcl::PointXYZ>& cloudOut
Returns
void
Definition at line 792 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     *cloudIn = cloud;
     //conv pclXYZ to pcl2
     //pcl::PCLPointCloud2::Ptr cloudInPcl2 (new pcl::PCLPointCloud2 ());
     //pcl::toPCLPointCloud2(*cloudIn, *cloudInPcl2);
     //Voxel grid downsample
     //pcl::PCLPointCloud2::Ptr cloudPcl2filtered (new pcl::PCLPointCloud2 ());
     pcl::VoxelGrid<pcl::PointXYZ> sor;
     sor.setInputCloud(cloudIn);
     sor.setLeafSize (distanceThreshold, distanceThreshold, distanceThreshold);//0.04f
     //sor.filter (*cloudPcl2filtered);
     sor.filter (cloudOut);
     //conv pcl2 to pclXYZ
     //pcl::fromPCLPointCloud2(*cloudPcl2filtered, cloudOut);
     //test: pcl::fromPCLPointCloud2(*cloudInPcl2, cloudOut);
 }
Referenced by reconTwoPcl().
voxelGridRgb()
void pclUtilitys::voxelGridRgb (const pcl::PointCloud< pcl::PointXYZRGB > & cloud, pcl::PointCloud< pcl::PointXYZRGB > & cloudOut, float distanceThreshold)
voxel grid color input:
Parameters
const pcl::PointCloud<pcl::PointXYZRGB>& cloud, float distanceThreshold output:
pcl::PointCloud<pcl::PointXYZRGB>& cloudOut
Returns
void
Definition at line 824 of file pclUtilitys.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZRGB>);
     *cloudIn = cloud;
     //conv pclXYZ to pcl2
     //pcl::PCLPointCloud2::Ptr cloudInPcl2 (new pcl::PCLPointCloud2 ());
     //pcl::toPCLPointCloud2(*cloudIn, *cloudInPcl2);
     //Voxel grid downsample
     pcl::PCLPointCloud2::Ptr cloudPcl2filtered (new pcl::PCLPointCloud2 ());
     pcl::VoxelGrid<pcl::PointXYZRGB> sor;
     sor.setInputCloud(cloudIn);
     //float distanceThreshold = 0.04f;
     sor.setLeafSize (distanceThreshold, distanceThreshold, distanceThreshold);
     sor.filter (cloudOut);
     //conv pcl2 to pclXYZ
     //pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudRgbFiltered (new pcl::PointCloud<pcl::PointXYZRGB>);
     //pcl::fromPCLPointCloud2(*cloudPcl2filtered, cloudOut);
 }
Referenced by pclApp::testViewsWithNormals(), and pclApp::testViewsWithViewports().
Member Data Documentation
range_image
pcl::RangeImage& pclUtilitys::range_image static
Definition at line 201 of file pclUtilitys.h.
Referenced by narfKeypointExtraction(), and narfKeypointExtractionRgb().
range_image_widget
pcl::visualization::RangeImageVisualizer pclUtilitys::range_image_widget static
Definition at line 202 of file pclUtilitys.h.
Referenced by narfKeypointExtraction().
rootPclResultSize
int pclUtilitys::rootPclResultSize static
Definition at line 199 of file pclUtilitys.h.
Referenced by viewportsDiffVis().
rootPclRgbResultSize
int pclUtilitys::rootPclRgbResultSize static
Definition at line 200 of file pclUtilitys.h.
Referenced by viewportsDiffVisRgb().
rootPclRgbSize
int pclUtilitys::rootPclRgbSize static
Definition at line 198 of file pclUtilitys.h.
Referenced by viewportsDiffVisRgb().
rootPclSize
int pclUtilitys::rootPclSize static
Definition at line 197 of file pclUtilitys.h.
Referenced by viewportsDiffVis().
transM
Eigen::Matrix4f pclUtilitys::transM
Definition at line 203 of file pclUtilitys.h.
Referenced by icpNormals(), and icpSimple().
tree_xyz
pcl::search::KdTree< pcl::PointXYZ >::Ptr pclUtilitys::tree_xyz static
Definition at line 205 of file pclUtilitys.h.
Referenced by extractFPFHfromKeypoints(), getNormalsFromCloudRgb(), and getNormalsXYZIFromCloud().
tree_xyzrgb
pcl::search::KdTree< pcl::PointXYZRGB >::Ptr pclUtilitys::tree_xyzrgb static
Definition at line 206 of file pclUtilitys.h.
Referenced by getNormalsXYZIFromCloudRgb().
viewer
pcl::visualization::PCLVisualizer::Ptr pclUtilitys::viewer
Definition at line 196 of file pclUtilitys.h.
Referenced by FastPointFeatureHistogramsExample(), momentOfInertiaRgb(), momentOfInertiaTest(), momentOfInertiaTestRgb(), normalsVis(), pclApp::renderLoop(), rgbVis(), rgbVisDouble(), setViewerPose(), simpleVis(), pclApp::testLineCreater(), pclApp::testPclRgbObjectDetectionPipe01(), testRandomSampleConsensus(), pclApp::testTranformOrientationToPlane(), pclApp::testViewsWithNormals(), pclApp::testViewsWithViewports(), viewportsDiffVis(), viewportsDiffVisRgb(), and viewportsVis().
The documentation for this class was generated from the following files:
/media/hd2/dev/kinectV3/kv3Pcl/include/pclUtilitys.h
/media/hd2/dev/kinectV3/kv3Pcl/src/pclUtilitys.cpp