kv3_framework: audioMeasurement Class Reference
audioMeasurement Class Reference
#include "audioMeasurement.h"
Public Member Functions
audioMeasurement ()
~audioMeasurement ()
void run ()
void update ()
double rms (short *buffer)
void show (int Pvalue, int peak)
float getPvalue ()
float getPvalueMax ()
int getIntPvalue ()
int getIntPvalueMax ()
cv::Mat getMeasurementImage ()
Private Member Functions
void init ()
void updateImage ()
Private Attributes
int err
Static Private Attributes
static char * device = "plughw:2,0"
static short buffer [8 *1024]
static int buffer_size = sizeof(buffer)>>1
static snd_pcm_t * handle_capture
static snd_pcm_sframes_t frames
static double k = 0.45255
static double Pvalue = 0
static double peak = 0
static cv::Mat audioMeasurementImg
static int counterpValueBuffer = 0
static int pValueBuffer [MAX_PVALUE_X_BUFFER]
Detailed Description
Definition at line 32 of file audioMeasurement.h.
Constructor & Destructor Documentation
audioMeasurement()
audioMeasurement::audioMeasurement ()
Definition at line 19 of file audioMeasurement.cpp.
{
     init();
 }
References init().
~audioMeasurement()
audioMeasurement::~audioMeasurement ()
Definition at line 22 of file audioMeasurement.cpp.
{
     snd_pcm_close(handle_capture);
 }
References handle_capture.
Member Function Documentation
getIntPvalue()
int audioMeasurement::getIntPvalue ()
Definition at line 28 of file audioMeasurement.cpp.
 {return((int)round(audioMeasurement::Pvalue));}
References Pvalue.
getIntPvalueMax()
int audioMeasurement::getIntPvalueMax ()
Definition at line 29 of file audioMeasurement.cpp.
 {return((int)round(audioMeasurement::peak));}
References peak.
getMeasurementImage()
cv::Mat audioMeasurement::getMeasurementImage ()
Definition at line 30 of file audioMeasurement.cpp.
 {return(audioMeasurement::audioMeasurementImg);}
References audioMeasurementImg.
Referenced by showKv2Demo().
getPvalue()
float audioMeasurement::getPvalue ()
Definition at line 26 of file audioMeasurement.cpp.
 {return((float)audioMeasurement::Pvalue);}
References Pvalue.
getPvalueMax()
float audioMeasurement::getPvalueMax ()
Definition at line 27 of file audioMeasurement.cpp.
 {return((float)audioMeasurement::peak);}
References peak.
init()
void audioMeasurement::init () private
init / open pcm audio channel
Returns
void
Definition at line 37 of file audioMeasurement.cpp.
{
     err = snd_pcm_open(&handle_capture, device, SND_PCM_STREAM_CAPTURE, 0);
     if(err < 0) {
         printf("Capture open error: %s\n", snd_strerror(err));
         exit(EXIT_FAILURE);
     }
     err = snd_pcm_set_params(handle_capture,
                              SND_PCM_FORMAT_S16_LE,
                              SND_PCM_ACCESS_RW_INTERLEAVED,
                              1,
                              48000,
                              1,
                              500000);
     if(err < 0) {
         printf("Capture open error: %s\n", snd_strerror(err));
         exit(EXIT_FAILURE);
     }
 }
References device, err, and handle_capture.
Referenced by audioMeasurement().
rms()
double audioMeasurement::rms (short * buffer)
rms from square sum of the buffer input:
Parameters
short *buffer
Returns
double result
Definition at line 163 of file audioMeasurement.cpp.
 {
     int i;
     long int square_sum = 0.0;
     for(i=0; i<buffer_size; i++)
         square_sum += (buffer[i] * buffer[i]);
     double result = sqrt(square_sum/buffer_size);
     return result;
 }
References buffer, and buffer_size.
Referenced by run(), and update().
run()
void audioMeasurement::run ()
run audio data
Returns
void
Definition at line 134 of file audioMeasurement.cpp.
{
         frames = snd_pcm_readi(handle_capture, buffer, buffer_size);
         if(frames < 0) {
             // Try to recover
             frames = snd_pcm_recover(handle_capture, frames, 0);
             if(frames < 0) {
                 printf("snd_pcm_readi failed: %s\n", snd_strerror(err));
             }
         }
         if(frames > 0 && frames < (long)buffer_size) {
             printf("Short read (expected %li, read %li)\n", (long)buffer_size, frames);
         }
         // Successfully read, calculate dB and update peak value
         Pvalue = rms(buffer) * k;
         Pvalue = Pvalue - offsetPvalue;
         if(Pvalue > peak){peak = Pvalue;}
         show(Pvalue, peak);
 }
References buffer, buffer_size, err, frames, handle_capture, k, offsetPvalue, peak, Pvalue, rms(), and show().
show()
void audioMeasurement::show (int Pvalue, int peak)
show pValue input:
Parameters
int Pvalue, int peak
Returns
void
Definition at line 181 of file audioMeasurement.cpp.
 {
     int j;
     int dB;
     int dBpeak;
     for(j=0; j<13; j++)
         printf("\b");
     fflush(stdout);
     if(Pvalue > 0)
     {
         dB = (int)20 * log10(Pvalue);
         printf("dB=%d,", dB);
     }
     else
         printf("dB=--,");
     if(peak > 0)
     {
         dBpeak = (int)20 * log10(peak);
         printf("Peak=%d", dBpeak);
     }
     else
         printf("Peak=--", dB, peak);
     fflush(stdout);
 }
References peak, and Pvalue.
Referenced by run().
update()
void audioMeasurement::update ()
update audio data
Returns
void
std::cout << "pValueBuffer[0]: " << pValueBuffer[0] << std::endl;
Definition at line 97 of file audioMeasurement.cpp.
{
     frames = snd_pcm_readi(handle_capture, buffer, buffer_size);
     if(frames < 0) {
         // Try to recover
         frames = snd_pcm_recover(handle_capture, frames, 0);
         if(frames < 0) {
             //printf("snd_pcm_readi failed: %s\n", snd_strerror(err));
             return;
         }
         if(frames > 0 && frames < (long)buffer_size) {
             //printf("Short read (expected %li, read %li)\n", (long)buffer_size, frames);
             return;
         }
     }
     // Successfully read, calculate dB and update peak value
     Pvalue = rms(buffer) * k;
     if(Pvalue > peak){peak = Pvalue;}
     int i=MAX_PVALUE_X_BUFFER-1;
    // int imax=MAX_PVALUE_X_BUFFER-1;
     while(i>=0){
         pValueBuffer[i+1] = pValueBuffer[i];
     i--;
     }
     pValueBuffer[0] = (int)round(Pvalue);
     updateImage();
 }
References buffer, buffer_size, frames, handle_capture, k, MAX_PVALUE_X_BUFFER, peak, Pvalue, pValueBuffer, rms(), and updateImage().
Referenced by showKv2Demo().
updateImage()
void audioMeasurement::updateImage () private
update measurement image
Returns
void
Definition at line 63 of file audioMeasurement.cpp.
{
     const int thickness = 1;
     int x, y;
     int maxy = MAX_PVALUE_Y_BUFFER;
     int i=0;
     int imax=MAX_PVALUE_X_BUFFER;
     audioMeasurementImg.setTo(cv::Scalar(grayValue,grayValue,grayValue));
     while(i<imax){
         x = i;
         y = maxy-pValueBuffer[i];
         Point startPoint(x, maxy);
         Point endPoint(x, y);
         line(audioMeasurementImg, startPoint, endPoint, Scalar(0, 200, 0), thickness, LINE_8);
     i++;
     }
     const float fontScale = 0.5;
     std::stringstream strStreamdB;
     strStreamdB << std::fixed << std::setprecision(2) << audioMeasurement::Pvalue;
     string strdB = "dB: " + strStreamdB.str();
     cv::putText(audioMeasurementImg,
         strdB, //text
         cv::Point(imax/2-26, 26),
         cv::FONT_HERSHEY_SIMPLEX,
         fontScale,
         CV_RGB(118, 185, 200),
         1);
 }
References audioMeasurementImg, grayValue, MAX_PVALUE_X_BUFFER, MAX_PVALUE_Y_BUFFER, Pvalue, and pValueBuffer.
Referenced by update().
Member Data Documentation
audioMeasurementImg
cv::Mat audioMeasurement::audioMeasurementImg static private
Definition at line 58 of file audioMeasurement.h.
Referenced by getMeasurementImage(), and updateImage().
buffer
short audioMeasurement::buffer static private
Definition at line 50 of file audioMeasurement.h.
Referenced by rms(), run(), and update().
buffer_size
int audioMeasurement::buffer_size = sizeof(buffer)>>1 static private
Definition at line 51 of file audioMeasurement.h.
Referenced by rms(), run(), and update().
counterpValueBuffer
int audioMeasurement::counterpValueBuffer = 0 static private
Definition at line 59 of file audioMeasurement.h.
device
char * audioMeasurement::device = "plughw:2,0" static private
Definition at line 49 of file audioMeasurement.h.
Referenced by init().
err
int audioMeasurement::err private
Definition at line 57 of file audioMeasurement.h.
Referenced by init(), and run().
frames
snd_pcm_sframes_t audioMeasurement::frames static private
Definition at line 53 of file audioMeasurement.h.
Referenced by run(), and update().
handle_capture
snd_pcm_t * audioMeasurement::handle_capture static private
Definition at line 52 of file audioMeasurement.h.
Referenced by init(), run(), update(), and ~audioMeasurement().
k
double audioMeasurement::k = 0.45255 static private
Definition at line 54 of file audioMeasurement.h.
Referenced by run(), and update().
peak
double audioMeasurement::peak = 0 static private
Definition at line 56 of file audioMeasurement.h.
Referenced by getIntPvalueMax(), getPvalueMax(), run(), show(), and update().
Pvalue
double audioMeasurement::Pvalue = 0 static private
Definition at line 55 of file audioMeasurement.h.
Referenced by getIntPvalue(), getPvalue(), run(), show(), update(), and updateImage().
pValueBuffer
int audioMeasurement::pValueBuffer static private
Definition at line 60 of file audioMeasurement.h.
Referenced by update(), and updateImage().
The documentation for this class was generated from the following files:
/media/hd2/dev/kinectV3/kv3Pcl/include/audioMeasurement.h
/media/hd2/dev/kinectV3/kv3Pcl/src/audioMeasurement.cpp