kv3_framework: kv3 Class Reference
kv3 Class Reference
#include "kv3.h"
Public Member Functions
kv3 ()
~kv3 ()
void setup ()
void setupCalib ()
void create_xy_table (const k4a_calibration_t *calibration, k4a_image_t xy_table)
void writePCL (const char *file_name)
void write_color_point_cloud (const char *file_name)
void writeColorPcl1 (const char *file_name)
void writeColorPcl2 (const char *file_name)
void readCurrentColorMode ()
int update ()
void shutdown ()
void testloop ()
void capColor ()
void capDepth ()
void capIr ()
void capTemperature ()
void regDepth ()
void updateIMU ()
k4a::Vector extract_gravity_from_imu (k4a::Vector &imuAcc)
string getSerialNumber (k4a_device_t device)
inline string kv3::getSerialNumber(k4a_device_t device).
string getSerialNumber ()
string getHardwareVersion ()
void getCapTemperature (float &temperature)
void getImuTemperature (float &temperature)
void getIMU (k4a::Vector &vec)
void getIMU (float &x, float &y, float &z)
void getGravity (k4a::Vector &vec)
void getGravity (float &x, float &y, float &z)
void getCvColorImg (cv::Mat &img)
void getCvIrImg (cv::Mat &img)
void getCvDepthImg (cv::Mat &img)
void getCvRegDepthImg (cv::Mat &img)
void cropKv3Img (cv::Mat &imColor, cv::Mat &imDepth, const int w, const int h)
void resizeKv3Img (cv::Mat &imColor, cv::Mat &imDepth, const int inW, const int inH)
void convIrToVisibleImg (const cv::Mat &imgIr, cv::Mat &dest)
void convIrToVisible8BitGrayImg (const cv::Mat &src, cv::Mat &dest)
void convToVisibleImg (const cv::Mat &in, cv::Mat &out)
void cropKv3IrImg (cv::Mat &imIr, const int w, const int h)
void resizeKv3IrImg (cv::Mat &imIr, const int inW, const int inH)
void resizeKv3ImgColor (cv::Mat &imColor, const int inW, const int inH)
void resizeImg (cv::Mat &img, const int inW, const int inH)
void calcCvPclCamColor (const cv::Mat &depth, cv::Mat &cvPcl)
void calcCvPclCamResize (const cv::Mat &depth, cv::Mat &cvPcl, const int tarW, const int tarH, const bool bColor)
void calcCvPclCamIr (const cv::Mat &depth, cv::Mat &cvPcl)
void calcCvPclSimple (const cv::Mat &depth, cv::Mat &cvPcl)
Public Attributes
k4a_hardware_version_t * k4aHwVer_HwVersion
k4a_calibration_t calibration
const int32_t TIMEOUT_IN_MS = 1000
k4a_image_t kv3ImColor
k4a_image_t kv3ImIr
k4a_image_t kv3ImDepth
k4a_image_t kv3ImDepthReg
k4a_imu_sample_t imu_sample
k4a::Vector imuAcc
k4a::Vector imuGravity
cv::Mat imgColor
cv::Mat imgIr
cv::Mat imgDepth
cv::Mat imgDepthReg
Static Public Attributes
static int imgWidth = 360
static int imgHeight = 360
static k4a_device_t device = NULL
static k4a_capture_t capture = NULL
static k4a_transformation_t transformation = NULL
static k4a_image_t kv3_depth_image = NULL
static k4a_image_t kv3_xy_table = NULL
static k4a_image_t kv3ImPcl = NULL
static int kv3_point_count = 0
static string serialNumber
static float imuTemperature
static float capTemparature
static cv::Mat pclKv2
static cv::Mat imgRegRGB
static float cx0 = 0
static float cy0 = 0
static float fx0 = 0
static float fy0 = 0
static float cx1 = 0
static float cy1 = 0
static float fx1 = 0
static float fy1 = 0
Static Private Attributes
static k4a_device_configuration_t config
Detailed Description
kv3 class. kinect azure sensor set framework class.
Definition at line 56 of file kv3.h.
Constructor & Destructor Documentation
kv3()
kv3::kv3 ()
A constructor. A more elaborate description of the constructor.
Definition at line 41 of file kv3.cpp.
          {
    // k4a_set_debug_message_handler(nullptr, nullptr, K4A_LOG_LEVEL_OFF);
    // std::system("export K4A_ENABLE_LOG_TO_STDOUT=0");
 }
~kv3()
kv3::~kv3 ()
Definition at line 46 of file kv3.cpp.
           {
     shutdown();
 }
References shutdown().
Member Function Documentation
calcCvPclCamColor()
void kv3::calcCvPclCamColor (const cv::Mat & depth, cv::Mat & cvPcl)
calculate a point cloud in meter via depth image and color camera calibration data (fx,fy, cx, cy)
input:
Parameters
const cv::Mat &depth = opencv depth image Output:
cv::Mat &cvPcl = opencv point cloud
opencv format for pcl = cv::Mat kv2::pclKv2(424, 512, CV_32FC3, Scalar(0,0,0));//XYZ in meters (CV_32FC3)
Returns
void
Definition at line 896 of file kv3.cpp.
{
     int xmax = depth.size().width;
     int ymax = depth.size().height;
     cv::Mat bufferPcl(ymax, xmax, CV_32FC3, Scalar(0,0,0));//XYZ in meters (CV_32FC3)
     float pclX;
     float pclY;
     float pclZ;
     const float factor = 0.001;
     int y=0;
     while(y<ymax){
         int x=0;
         while(x<xmax){
             pclZ = (float)((depth.at<ushort>(y,x)) * factor);
             pclX = ((x - cx1) * pclZ / fx1);
             pclY = ((y - cy1) * pclZ / fy1);
             bufferPcl.at<cv::Vec3f>(y,x)[0] = pclX;
             bufferPcl.at<cv::Vec3f>(y,x)[1] = pclY;
             bufferPcl.at<cv::Vec3f>(y,x)[2] = pclZ;
             x++;
         }
     y++;
     }
     cvPcl = bufferPcl.clone();
 }
References cx1, cy1, fx1, and fy1.
Referenced by main().
calcCvPclCamIr()
void kv3::calcCvPclCamIr (const cv::Mat & depth, cv::Mat & cvPcl)
calculate a point cloud in meter via depth image and infrared camera calibration data (fx,fy, cx, cy)
input:
Parameters
const cv::Mat &depth = opencv depth image Output:
cv::Mat &cvPcl = opencv point cloud
opencv format for pcl = cv::Mat kv2::pclKv2(424, 512, CV_32FC3, Scalar(0,0,0));//XYZ in meters (CV_32FC3)
Returns
void
Definition at line 930 of file kv3.cpp.
{
     int xmax = depth.size().width;
     int ymax = depth.size().height;
     cv::Mat bufferPcl(ymax, xmax, CV_32FC3, Scalar(0,0,0));//XYZ in meters (CV_32FC3)
     float pclX;
     float pclY;
     float pclZ;
     const float factor = 0.001;
     int y=0;
     while(y<ymax){
         int x=0;
         while(x<xmax){
             pclZ = (float)((depth.at<ushort>(y,x)) * factor);
             pclX = ((x - cx0) * pclZ / fx0);
             pclY = ((y - cy0) * pclZ / fy0);
             bufferPcl.at<cv::Vec3f>(y,x)[0] = pclX;
             bufferPcl.at<cv::Vec3f>(y,x)[1] = pclY;
             bufferPcl.at<cv::Vec3f>(y,x)[2] = pclZ;
             x++;
         }
     y++;
     }
     cvPcl = bufferPcl.clone();
 }
References cx0, cy0, fx0, and fy0.
calcCvPclCamResize()
void kv3::calcCvPclCamResize (const cv::Mat & inDepth, cv::Mat & cvPcl, const int tarW, const int tarH, const bool bColor)
calculate the point cloud based on the depth image and calibration data (fx,fy,cx,cy)
input:depth image; width and the height of the depth image; calibration data source: true = color cam calibration; false = infrared calibartion data
Parameters
const cv::Mat &inDepth, const int tarW, const int tarH, const bool bColor output: point cloud
cv::Mat &cvPcl,
Returns
void
Definition at line 1470 of file kv3.cpp.
{
     //calculate calibration data new (cx, cy, fx, fy)
     if(inDepth.empty() == false){
         int w = tarW;
         int h = tarH;
         double ratioH = 0;
         double ratioW = 0;
         if(w <= 0){ w = inDepth.size().width; }
         if(h <= 0){ h = inDepth.size().height; }
         if(w > inDepth.size().width){ w = inDepth.size().width; }
         if(h > inDepth.size().height){ h = inDepth.size().height; }
         if(bColor == true){
             //ratioW = double((double)w/(double)k4a_image_get_width_pixels(kv3ImDepthReg));
             //ratioH = double((double)h/(double)k4a_image_get_height_pixels(kv3ImDepthReg));
             ratioW = double((double)w/(double)(calibration.color_camera_calibration.resolution_width));
             ratioH = double((double)h/(double)(calibration.color_camera_calibration.resolution_height));
         }else{
             //ratioW = double((double)w/(double)k4a_image_get_width_pixels(kv3ImDepth));
             //ratioH = double((double)h/(double)k4a_image_get_height_pixels(kv3ImDepth));
             ratioW = double((double)w/(double)(calibration.depth_camera_calibration.resolution_width));
             ratioH = double((double)h/(double)(calibration.depth_camera_calibration.resolution_height));
         }
         float cxr;
         float cyr;
         float fxr;
         float fyr;
         if(bColor == true){
             cxr = kv3::cx1 * ratioW;
             cyr = kv3::cy1 * ratioH;
             fxr = kv3::fx1 * ratioW;
             fyr = kv3::fy1 * ratioH;
         }else{
             cxr = kv3::cx0 * ratioW;
             cyr = kv3::cy0 * ratioH;
             fxr = kv3::fx0 * ratioW;
             fyr = kv3::fy0 * ratioH;
         }
         int xmax = inDepth.size().width;
         int ymax = inDepth.size().height;
         cv::Mat bufferPcl(ymax, xmax, CV_32FC3, Scalar(0,0,0));//XYZ in meters (CV_32FC3)
         float pclX;
         float pclY;
         float pclZ;
         const float factor = 0.001;
         int y=0;
         while(y<ymax){
             int x=0;
             while(x<xmax){
                 pclZ = (float)((inDepth.at<ushort>(y,x)) * factor);
                 pclX = ((x - cxr) * pclZ / fxr);
                 pclY = ((y - cyr) * pclZ / fyr);
                 bufferPcl.at<cv::Vec3f>(y,x)[0] = pclX;
                 bufferPcl.at<cv::Vec3f>(y,x)[1] = pclY;
                 bufferPcl.at<cv::Vec3f>(y,x)[2] = pclZ;
                 x++;
             }
         y++;
         }
         cvPcl = bufferPcl.clone();
     }//if img not empty
 }
References calibration, cx0, cx1, cy0, cy1, fx0, fx1, fy0, and fy1.
Referenced by main().
calcCvPclSimple()
void kv3::calcCvPclSimple (const cv::Mat & depth, cv::Mat & cvPcl)
calculate via depth image very simple a point cloud
input:
Parameters
const cv::Mat &depth = opencv depth image Output:
cv::Mat &cvPcl = opencv point cloud (values are in meter)
Returns
void
Definition at line 860 of file kv3.cpp.
{
     int xmax = depth.size().width;
     int ymax = depth.size().height;
     cv::Mat bufferPcl(ymax, xmax, CV_32FC3, Scalar(0,0,0));//XYZ in meters (CV_32FC3)
     float pclX;
     float pclY;
     float pclZ;
     const float factor = 0.001;
     int y=0;
     while(y<ymax){
         int x=0;
         while(x<xmax){
             pclZ = (float)((depth.at<ushort>(y,x)) * factor);
             pclX = (float)x*factor;
             pclY = (float)y*factor;
             bufferPcl.at<cv::Vec3f>(y,x)[0] = pclX;
             bufferPcl.at<cv::Vec3f>(y,x)[1] = pclY;
             bufferPcl.at<cv::Vec3f>(y,x)[2] = pclZ;
             x++;
         }
     y++;
     }
     cvPcl = bufferPcl.clone();
 }
capColor()
void kv3::capColor ()
capture the kinect azure color image.
input:
Parameters
void
output:
void / copy internal the data to k4a_image_t kv3:kv3ImColor
Returns
void
Error: output to comand line " | Color None \n "
Definition at line 966 of file kv3.cpp.
                   {
         // Probe for a color image
         kv3ImColor = k4a_capture_get_color_image(kv3::capture);
         if (kv3ImColor != NULL)
         {
             // Get the sizes of color image
             int width = k4a_image_get_width_pixels(kv3ImColor);
             int height = k4a_image_get_height_pixels(kv3ImColor);
             int strides = k4a_image_get_stride_bytes(kv3ImColor);
             //printf("Color image height, width and strides: %d, %d, %d\n", height, width, strides);
             // Store the image using opencv Mat
             uint8_t* colorImageData = k4a_image_get_buffer(kv3ImColor);
             imgColor = Mat(height, width, CV_8UC4, (void*)colorImageData, Mat::AUTO_STEP);
             //imshow("imgColor", imgColor);
         }else{
             printf(" | Color None                       ");
         }
 }
References capture, imgColor, and kv3ImColor.
Referenced by testloop(), and update().
capDepth()
void kv3::capDepth ()
capture the kinect azure depth image.
input:
Parameters
void
output:
void / copy internal the data to k4a_image_t kv3:kv3ImDepth
Returns
void
Error: output to comand line: " | Depth16 None"
Definition at line 1031 of file kv3.cpp.
                   {
         kv3ImDepth = k4a_capture_get_depth_image(capture);
         if (kv3ImDepth != NULL)
         {
             // Get the sizes of depth image
             int width = k4a_image_get_width_pixels(kv3ImDepth);
             int height = k4a_image_get_height_pixels(kv3ImDepth);
             int strides = k4a_image_get_stride_bytes(kv3ImDepth);
             //printf("Depth image height, width and strides: %d, %d, %d\n", height, width, strides);
             // Store the image using opencv Mat
             uint16_t* depthImageData = (uint16_t*)(void*)k4a_image_get_buffer(kv3ImDepth);
             imgDepth = Mat(height, width, CV_16U, (void*)depthImageData, Mat::AUTO_STEP);
             //imshow("imgDepth", imgDepth);
         }else{
             printf(" | Depth16 None\n");
         }
 }
References capture, imgDepth, and kv3ImDepth.
Referenced by testloop(), and update().
capIr()
void kv3::capIr ()
capture the kinect azure infrared image.
input:
Parameters
void
output:
void / copy internal the data to k4a_image_t kv3:kv3ImIr
Returns
void
Error: output to comand line " | IR None"
Definition at line 999 of file kv3.cpp.
                {
     kv3ImIr = k4a_capture_get_ir_image(kv3::capture);
     if (kv3ImIr != NULL)
     {
         // Get the sizes of depth image
         int width = k4a_image_get_width_pixels(kv3ImIr);
         int height = k4a_image_get_height_pixels(kv3ImIr);
         int strides = k4a_image_get_stride_bytes(kv3ImIr);
         //printf("IR image height, width and strides: %d, %d, %d\n", height, width, strides);
         // Store the image using opencv Mat
         uint16_t* irImageData = (uint16_t*)(void*)k4a_image_get_buffer(kv3ImIr);
         imgIr = Mat(height, width, CV_16U, (void*)irImageData, Mat::AUTO_STEP);
         //imshow("imgDepth", imgDepth);
     }else{
         printf(" | IR None\n");
     }
 }
References capture, imgIr, and kv3ImIr.
Referenced by testloop(), and update().
capTemperature()
void kv3::capTemperature ()
capture the kinect azure sensor temperature
input:
Parameters
void
output: update internal variable capTemparature value.
void
Returns
void
Definition at line 1210 of file kv3.cpp.
{
     capTemparature = (float)k4a_capture_get_temperature_c(capture);
 }
References capTemparature, and capture.
Referenced by testloop().
convIrToVisible8BitGrayImg()
void kv3::convIrToVisible8BitGrayImg (const cv::Mat & src, cv::Mat & dest)
converte 16 bit image to a visible 8bit gray image
input: infrared values
Parameters
const cv::Mat &src output: visible image
cv::Mat &dest
Returns
void
Definition at line 1770 of file kv3.cpp.
{
     //dest = src.clone();
     //  12bit=2^12=4096 // 14bit=2^14=16384 // 16bit=2^16=65536 / 131072
     const float resolution = 16384-1;
     float factor;
     float divisor;
     if(config.depth_mode == K4A_DEPTH_MODE_NFOV_2X2BINNED){
         divisor = (float)5460.0;
     }
     if(config.depth_mode == K4A_DEPTH_MODE_NFOV_UNBINNED){
         divisor = (float)3860.0;
     }
     if(config.depth_mode == K4A_DEPTH_MODE_WFOV_2X2BINNED){
         divisor = (float)2880.0;
     }
     if(config.depth_mode == K4A_DEPTH_MODE_WFOV_UNBINNED){
         divisor = (float)2210.0;
     }
     factor = (float)(float)65536/(divisor);
     factor = (factor / (float)256.0);
     int mW = src.size().width;
     int mH = src.size().height;
     dest = Mat(mH, mW, CV_8UC1);
     int y=0;
     y=0;
     while(y<mH){
         int x=0;
         while(x<mW){
             dest.at<uchar>(y,x) = (uint8_t)(src.at<ushort>(y,x)*factor);
             x++;
         }
         y++;
     }
     equalizeHist( dest, dest ); //8bit channel
 }
References config.
Referenced by test().
convIrToVisibleImg()
void kv3::convIrToVisibleImg (const cv::Mat & src, cv::Mat & dest)
converte 16 bit infrared image to a visible image
input: infrared values
Parameters
const cv::Mat &src output: visible image
cv::Mat &dest
Returns
void
Definition at line 1725 of file kv3.cpp.
{
     dest = src.clone();
     //  12bit=2^12=4096 // 14bit=2^14=16384 // 16bit=2^16=65536 / 131072
     const float resolution = 16384-1;
     float factor;
     float divisor;
     if(config.depth_mode == K4A_DEPTH_MODE_NFOV_2X2BINNED){
         divisor = (float)5460.0;
     }
     if(config.depth_mode == K4A_DEPTH_MODE_NFOV_UNBINNED){
         divisor = (float)3860.0;
     }
     if(config.depth_mode == K4A_DEPTH_MODE_WFOV_2X2BINNED){
         divisor = (float)2880.0;
     }
     if(config.depth_mode == K4A_DEPTH_MODE_WFOV_UNBINNED){
         divisor = (float)2210.0;
     }
     factor = (float)(65536/divisor);
     int mW = src.size().width;
     int mH = src.size().height;
     int y=0;
     y=0;
     while(y<mH){
         int x=0;
         while(x<mW){
             dest.at<ushort>(y,x) = (int)(src.at<ushort>(y,x))*(factor);
             x++;
         }
         y++;
     }
 }
References config.
Referenced by showKv2Demo(), and test().
convToVisibleImg()
void kv3::convToVisibleImg (const cv::Mat & in, cv::Mat & out)
converte 16 bit depth image to a visible image
input: depth values
Parameters
const cv::Mat &in output: visible image
cv::Mat &out
Returns
void
Definition at line 1682 of file kv3.cpp.
{
     out = in.clone();
     int maxValue = 0;
     int mW = in.size().width;
     int mH = in.size().height;
     int y=0;
     int x=0;
     y=0;
     while(y<mH){
         x=0;
         while(x<mW){
             int val = (int)(in.at<ushort>(y,x));
             if(val > maxValue){ maxValue = val; }
             //dest.at<ushort>(y,x) = (int)(src.at<ushort>(y,x))*(factor);
             x++;
         }
         y++;
     }
     float factor = (65536/maxValue);
     y=0;
     while(y<mH){
         x=0;
         while(x<mW){
             out.at<ushort>(y,x) = (int)round((in.at<ushort>(y,x))*(factor));
             x++;
         }
         y++;
     }
 }
Referenced by showKv2Demo().
create_xy_table()
void kv3::create_xy_table (const k4a_calibration_t * calibration, k4a_image_t xy_table)
create values to improve the depth values input:
Parameters
const k4a_calibration_t *calibration = internal calibration data
output:
k4a_image_t xy_table = values to improve the depth values
Returns
void
Definition at line 143 of file kv3.cpp.
 {
     k4a_float2_t *table_data = (k4a_float2_t *)(void *)k4a_image_get_buffer(xy_table);
     int width = calibration->depth_camera_calibration.resolution_width;
     int height = calibration->depth_camera_calibration.resolution_height;
     k4a_float2_t p;
     k4a_float3_t ray;
     int valid;
     for (int y = 0, idx = 0; y < height; y++)
     {
         p.xy.y = (float)y;
         for (int x = 0; x < width; x++, idx++)
         {
             p.xy.x = (float)x;
             k4a_calibration_2d_to_3d(
                 calibration, &p, 1.f, K4A_CALIBRATION_TYPE_DEPTH, K4A_CALIBRATION_TYPE_DEPTH, &ray, &valid);
             if (valid)
             {
                 table_data[idx].xy.x = ray.xyz.x;
                 table_data[idx].xy.y = ray.xyz.y;
             }
             else
             {
                 table_data[idx].xy.x = nanf("");
                 table_data[idx].xy.y = nanf("");
             }
         }
     }
 }
References calibration.
Referenced by setup().
cropKv3Img()
void kv3::cropKv3Img (cv::Mat & imColor, cv::Mat & imDepth, const int w, const int h)
crop depth and color image - center based crop
input: w = width of the new images and h = height of the new images
Parameters
cv::Mat &imColor, cv::Mat &imDepth, const int w, const int h output: resized images
cv::Mat &imColor, cv::Mat &imDepth
Returns
void
Definition at line 1400 of file kv3.cpp.
{
     if((imgColor.empty() == false)&&(imgDepthReg.empty()==false)){
         int maxW = imgColor.size().width;
         int maxH = imgColor.size().height;
         if((w > maxW)||(h > maxH)){
             imgColor.copyTo(imColor);
             imgDepthReg.copyTo(imgDepthReg);
             return;
         }else{
             int uX = (int)(round(maxW*0.5)) - (int)(round(w*0.5));
             int uY = (int)(round(maxH*0.5)) - (int)(round(h*0.5));
             cv::Rect roi = cv::Rect(uX,uY,w,h);
             cv::Mat resizeColor = imgColor(roi);
             imColor = resizeColor.clone();
             cv::Mat resizeDepthReg = imgDepthReg(roi);
             imDepth = resizeDepthReg.clone();
         }
     }//if img not empty
 }
References imgColor, and imgDepthReg.
cropKv3IrImg()
void kv3::cropKv3IrImg (cv::Mat & imIr, const int w, const int h)
crop infrared image - ceneter based
input: width and height from the new size
Parameters
const int inW, const int inH output: croped image
cv::Mat &img,
Returns
void
Definition at line 1619 of file kv3.cpp.
{
     if(imgIr.empty() == false){
         int maxW = imgIr.size().width;
         int maxH = imgIr.size().height;
         if((w > maxW)||(h > maxH)){
             imgIr.copyTo(imIr);
             return;
         }else{
             int uX = (int)(round(maxW*0.5)) - (int)(round(w*0.5));
             int uY = (int)(round(maxH*0.5)) - (int)(round(h*0.5));
             cv::Rect roi = cv::Rect(uX,uY,w, h);
             cv::Mat resizeColor = imgIr(roi);
             imIr = resizeColor.clone();
         }
     }//if img not empty
 }
References imgIr.
extract_gravity_from_imu()
k4a::Vector kv3::extract_gravity_from_imu (k4a::Vector & imuAcc) inline
calculate gravity vector based on IMU acceleration vector
input:acceleration vector
Parameters
imuAcc
output: calculate gravity vector
vector depthGravity x,y,z
void
Returns
void
Error: comand line: "Failed to read a imu sample"
Definition at line 1259 of file kv3.cpp.
 {
     //const k4a_calibration_t& sensorCalibration;
     const float* transformation_color_IMU_R = calibration.extrinsics[K4A_CALIBRATION_TYPE_ACCEL][K4A_CALIBRATION_TYPE_COLOR].rotation;
     k4a::Vector Rx = { transformation_color_IMU_R[0], transformation_color_IMU_R[1], transformation_color_IMU_R[2] };
     k4a::Vector Ry = { transformation_color_IMU_R[3], transformation_color_IMU_R[4], transformation_color_IMU_R[5] };
     k4a::Vector Rz = { transformation_color_IMU_R[6], transformation_color_IMU_R[7], transformation_color_IMU_R[8] };
     k4a::Vector depthAcc = { Rx.Dot(imuAcc), Ry.Dot(imuAcc) , Rz.Dot(imuAcc) };
     // The acceleration due to gravity, g, is in a direction toward the ground.
     // However an accelerometer at rest in a gravity field reports upward acceleration
     // relative to the local inertial frame (the frame of a freely falling object).
     k4a::Vector depthGravity = depthAcc.Normalized() * -1;
     return depthGravity;
 }
References calibration, k4a::Vector::Dot(), imuAcc, and k4a::Vector::Normalized().
Referenced by updateIMU().
getCapTemperature()
void kv3::getCapTemperature (float & tempera)
capture the kinect azure sensor temperature, whitout update the internal variable
input:
Parameters
void
output: update internal variable temperature value.
value by reference: float &tempera
Returns
void
Definition at line 1193 of file kv3.cpp.
{
     tempera = (float)k4a_capture_get_temperature_c(capture);
     //room temp = 18.3  :: value= 25,6 - 26,4
    // C = (F - 32) * 5/9
    // F = C * 1,8 + 32
 }
References capture.
Referenced by addTextToImg().
getCvColorImg()
void kv3::getCvColorImg (cv::Mat & img)
get color image as opencv image
input:void
Parameters
void
output: image by reference
cv::Mat &img
Returns
void
Definition at line 1348 of file kv3.cpp.
{
     imgColor.copyTo(img);
 }
References imgColor.
Referenced by main(), and showKv2Demo().
getCvDepthImg()
void kv3::getCvDepthImg (cv::Mat & img)
get depth image as opencv image
input:void
Parameters
void
output: image by reference
cv::Mat &img
Returns
void
Definition at line 1374 of file kv3.cpp.
{
     imgDepth.copyTo(img);
 }
References imgDepth.
Referenced by main(), and showKv2Demo().
getCvIrImg()
void kv3::getCvIrImg (cv::Mat & img)
get infrared image as opencv image
input:void
Parameters
void
output: image by reference
cv::Mat &img
Returns
void
Definition at line 1361 of file kv3.cpp.
{
     imgIr.copyTo(img);
 }
References imgIr.
Referenced by main(), showKv2Demo(), and test().
getCvRegDepthImg()
void kv3::getCvRegDepthImg (cv::Mat & img)
get regidtered depth image as opencv image
input:void
Parameters
void
output: image by reference
cv::Mat &img
Returns
void
Definition at line 1387 of file kv3.cpp.
{
     imgDepthReg.copyTo(img);
 }
References imgDepthReg.
Referenced by main(), and showKv2Demo().
getGravity() [1/2]
void kv3::getGravity (float & x, float & y, float & z)
get gravity vector
input:void
Parameters
void
output: gravity vector
float &x, float &y, float &z
Returns
void
Definition at line 1333 of file kv3.cpp.
{
     x = kv3::imuGravity.X;
     y = kv3::imuGravity.Y;
     z = kv3::imuGravity.Z;
 }
References imuGravity, k4a::Vector::X, k4a::Vector::Y, k4a::Vector::Z, and z.
getGravity() [2/2]
void kv3::getGravity (k4a::Vector & vec)
get gravity vector
input:void
Parameters
void
output: gravity vector
k4a::Vector& vec
Returns
void
Definition at line 1315 of file kv3.cpp.
{
     vec = imuGravity;//.Normalized();
     //std::cout << "Before : " << imu_grav.X << " " << imu_grav.Y << " " << imu_grav.Z << std::endl;
     //std::cout << "After : " << vec.X << " " << vec.Y << " " << vec.Z << std::endl;
     //k4a::Vector angle = vec.Angle(k4a::Vector(0,1.0,0));
     //std::cout << "After : " << vec.X << " " << vec.Y << " " << vec.Z << std::endl;
 }
References imuGravity.
Referenced by addTextToImg().
getHardwareVersion()
string kv3::getHardwareVersion ()
capture the kinect azure registered depth image.
input:
Parameters
void
output: HwVerRgb HwVerDepth HwVerDepthSensor HwVerAudio HwVerFirmwareBuild HwVerFirmwareSignature
string
Returns
void
Error: output to comand line: imgDepthReg is empty
Definition at line 1111 of file kv3.cpp.
{
     std::string strHwVer = string("");
     try{
         k4a_device_get_version( kv3::device , kv3::k4aHwVer_HwVersion);
         uint32_t major, minor, iteration;
         major = k4aHwVer_HwVersion->rgb.major;
         minor = k4aHwVer_HwVersion->rgb.major;
         iteration = k4aHwVer_HwVersion->rgb.major;
         std::string strHwVerRgb = std::string("rgb:") + std::to_string(major) + std::string(":") + std::to_string(minor) + std::string(":") + std::to_string(iteration);
         major = k4aHwVer_HwVersion->depth.major;
         minor = k4aHwVer_HwVersion->depth.major;
         iteration = k4aHwVer_HwVersion->depth.major;
         std::string strHwVerDepth = std::string(";depth:") + std::to_string(major) + std::string(":") + std::to_string(minor) + std::string(":") + std::to_string(iteration);
         major = k4aHwVer_HwVersion->depth_sensor.major;
         minor = k4aHwVer_HwVersion->depth_sensor.major;
         iteration = k4aHwVer_HwVersion->depth_sensor.major;
         std::string strHwVerDepthSensor = std::string(";depth_sensor:") + std::to_string(major) + std::string(":") + std::to_string(minor) + std::string(":") + std::to_string(iteration);
         major = k4aHwVer_HwVersion->audio.major;
         minor = k4aHwVer_HwVersion->audio.major;
         iteration = k4aHwVer_HwVersion->audio.major;
         std::string strHwVerAudio = std::string(";audio:") + std::to_string(major) + std::string(":") + std::to_string(minor) + std::string(":") + std::to_string(iteration);
         major = k4aHwVer_HwVersion->firmware_build;
         std::string strHwVerFirmwareBuild =  string("");
         if(k4aHwVer_HwVersion->firmware_build == K4A_FIRMWARE_BUILD_RELEASE){
             strHwVerFirmwareBuild = string(";firmware_build=Production firmware");
         }
         if(k4aHwVer_HwVersion->firmware_build == K4A_FIRMWARE_BUILD_DEBUG){
             strHwVerFirmwareBuild = string(";firmware_build=Pre-production firmware");
         }
         major = k4aHwVer_HwVersion->firmware_signature;
         std::string strHwVerFirmwareSignature =  string("");
         if(k4aHwVer_HwVersion->firmware_signature == K4A_FIRMWARE_SIGNATURE_MSFT){
             strHwVerFirmwareSignature = string(";firmware_signature=Microsoft signed firmware");
         }
         if(k4aHwVer_HwVersion->firmware_signature == K4A_FIRMWARE_SIGNATURE_TEST){
             strHwVerFirmwareSignature = string(";firmware_signature=Test signed firmware");
         }
         if(k4aHwVer_HwVersion->firmware_signature == K4A_FIRMWARE_SIGNATURE_UNSIGNED){
             strHwVerFirmwareSignature = string(";firmware_signature=Unsigned firmware");
         }
         strHwVer = strHwVerRgb + strHwVerDepth + strHwVerDepthSensor + strHwVerAudio + strHwVerFirmwareBuild + strHwVerFirmwareSignature;
     }catch(string e){
         strHwVer = string("Exeption: ") + e;
     }
     return(strHwVer);
 }
References device, and k4aHwVer_HwVersion.
getIMU() [1/2]
void kv3::getIMU (float & x, float & y, float & z)
get accelartion vector
input:void
Parameters
void
output: accelaration vector
float &x, float &y, float &z
Returns
void
Definition at line 1300 of file kv3.cpp.
{
     x = kv3::imuAcc.X;
     y = kv3::imuAcc.Y;
     z = kv3::imuAcc.Z;
 }
References imuAcc, k4a::Vector::X, k4a::Vector::Y, k4a::Vector::Z, and z.
getIMU() [2/2]
void kv3::getIMU (k4a::Vector & vec)
get accelartion vector
input:void
Parameters
void
output: accelaration vector
k4a::Vector& vec
Returns
void
Definition at line 1285 of file kv3.cpp.
{
     vec = imuAcc;//.Normalized();
     //std::cout << "IMU Acc : " << imu_Acc.X << " " << imu_Acc.Y << " " << imu_Acc.Z << std::endl;
     //std::cout << "After : " << vec.X << " " << vec.Y << " " << vec.Z << std::endl;
 }
References imuAcc.
Referenced by addTextToImg().
getImuTemperature()
void kv3::getImuTemperature (float & temperature)
capture the kinect azure IMU temperature
input:
Parameters
void
output: update internal variable temperature value.
value by reference: float &temperature
Returns
void
Definition at line 1175 of file kv3.cpp.
{
     temperature = imuTemperature;
     //room temp = 18.3  :: value= 10,6 - 10,7
     // C = (F - 32) * 5/9
     // F = C * 1,8 + 32
 }
References imuTemperature.
Referenced by addTextToImg().
getSerialNumber() [1/2]
string kv3::getSerialNumber ()
Deliver the serial number from device (MS kinect azure)
Parameters
void parameter
Returns
serial number from device as std::string
Definition at line 129 of file kv3.cpp.
{
     return(kv3::serialNumber);
 }
References serialNumber.
Referenced by setupCalib().
getSerialNumber() [2/2]
string kv3::getSerialNumber (k4a_device_t device) inline
inline string kv3::getSerialNumber(k4a_device_t device).
This function read the serial number from kinect azure sensor device.
Parameters
input k4a_device_t device handle from kinect azure device .
Returns
std::string with the serial number.
Definition at line 88 of file kv3.cpp.
 {
     size_t serial_number_length = 0;
     if (K4A_BUFFER_RESULT_TOO_SMALL != k4a_device_get_serialnum(device, NULL, &serial_number_length))
     {
         cout << "Failed to get serial number length" << endl;
         k4a_device_close(device);
         exit(-1);
     }
     char *serial_number = new (std::nothrow) char[serial_number_length];
     if (serial_number == NULL)
     {
         cout << "Failed to allocate memory for serial number (" << serial_number_length << " bytes)" << endl;
         k4a_device_close(device);
         exit(-1);
     }
     if (K4A_BUFFER_RESULT_SUCCEEDED != k4a_device_get_serialnum(device, serial_number, &serial_number_length))
     {
         cout << "Failed to get serial number" << endl;
         delete[] serial_number;
         serial_number = NULL;
         k4a_device_close(device);
         exit(-1);
     }
     string s(serial_number);
     delete[] serial_number;
     serial_number = NULL;
     kv3::serialNumber = s;
     return s;
 }
References device, and serialNumber.
Referenced by addTextToImg().
readCurrentColorMode()
void kv3::readCurrentColorMode ()
read the current color mode from the MS Kinect Azure.
input:
Parameters
void Output:
no,but output into the console.
Returns
void
Definition at line 572 of file kv3.cpp.
{
 /*
 k4a_result_t k4a_device_get_color_control   (   k4a_device_t    device_handle,
         k4a_color_control_command_t     command,
         k4a_color_control_mode_t *      mode,
         int32_t *   value
     )
 */
     k4a_color_control_command_t     command;
     k4a_color_control_mode_t *      mode;
     int32_t *   value ;
     k4a_color_control_mode_t    myMode;
     command = K4A_COLOR_CONTROL_POWERLINE_FREQUENCY;
     //command = K4A_COLOR_CONTROL_BRIGHTNESS;
     //command = K4A_COLOR_CONTROL_WHITEBALANCE; //available in auto mode
     //command = K4A_COLOR_CONTROL_EXPOSURE_TIME_ABSOLUTE; //available in auto mode
     if (K4A_RESULT_SUCCEEDED != k4a_device_get_color_control(device, command, mode, value)){
         cout << "---- ERROR --- read k4a_device_get_color_control was not succesfull" << endl;
         //https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/940
         cout << "---- Automatic control is active, if the firmware < AzureKinectDK_Fw_1.6.110079014.bin" << endl;
     }else{
         myMode = *mode;
         if(myMode == K4A_COLOR_CONTROL_MODE_AUTO){
             cout << "auto is active.";
         }
         if(myMode == K4A_COLOR_CONTROL_MODE_MANUAL){
             cout << "manual is active.";
             /*
             int32_t myValue = *value;
             if(myValue == 1){
                 cout << "powerline compensation for 50 Hz is active.";
             }
             if(myValue== 2){
                 cout << "powerline compensation for 60 Hz is active.";
             }
             */
         }
     }
 }
References device.
Referenced by setup().
regDepth()
void kv3::regDepth ()
capture the kinect azure registered depth image.
input:
Parameters
void
output:
void / copy internal the data to k4a_image_t kv3:kv3ImDepthReg
Returns
void
Error: output to comand line: imgDepthReg is empty
Definition at line 1062 of file kv3.cpp.
 {
     //create depth image equal to the color image size
     int color_image_width_pixels = k4a_image_get_width_pixels(kv3ImColor);
     int color_image_height_pixels = k4a_image_get_height_pixels(kv3ImColor);
     if (K4A_RESULT_SUCCEEDED != k4a_image_create(K4A_IMAGE_FORMAT_DEPTH16,
                                                  color_image_width_pixels,
                                                  color_image_height_pixels,
                                                  color_image_width_pixels * (int)sizeof(uint16_t),
                                                  &kv3ImDepthReg))
     {
         cout << "Failed to create transformed depth image" << endl;
     }
     //transform depth to register depth image
     if(K4A_RESULT_SUCCEEDED != k4a_transformation_depth_image_to_color_camera(transformation, kv3ImDepth, kv3ImDepthReg))
     {
         cout << "Failed to compute transformed depth image" << endl;
     }
     //create opencv imgDepthReg
     uint8_t *buffer = k4a_image_get_buffer(kv3ImDepthReg);
     uint16_t *depth_buffer = reinterpret_cast<uint16_t *>(buffer);
     cv::Mat mat(color_image_height_pixels, color_image_width_pixels, CV_16U);//CV_MAKETYPE(DataType<uint16_t>::type, 1));
     memcpy(mat.data, depth_buffer, color_image_height_pixels * color_image_width_pixels * 1 * sizeof(uint16_t));
     mat.copyTo(imgDepthReg);
     if(imgDepthReg.empty()){
         cout << "imgDepthReg is empty" << endl;
     }else{
         int width = k4a_image_get_width_pixels(kv3ImDepthReg);
         int height = k4a_image_get_height_pixels(kv3ImDepthReg);
         int strides = k4a_image_get_stride_bytes(kv3ImDepthReg);
         //printf("DepthReg image height, width and strides: %d, %d, %d\n", height, width, strides);
         //imshow("imgDepthReg", imgDepthReg);
     }
 }
References imgDepthReg, kv3ImColor, kv3ImDepth, kv3ImDepthReg, and transformation.
Referenced by testloop(), and update().
resizeImg()
void kv3::resizeImg (cv::Mat & img, const int inW, const int inH)
resize image
input: width and height from the new size
Parameters
const int inW, const int inH output: imColor
cv::Mat &img,
Returns
void
Definition at line 1582 of file kv3.cpp.
{
     if(img.empty() == false){
         int w = inW;
         int h = inH;
         if(w <= 0){
             //calculate w
             int mW = img.size().width;
             int mH = img.size().height;
             double ratioWH = double((double)mW/(double)mH);
             w = (int)round((double)h * ratioWH);
         }
         if(h <= 0){
             //calculate h
             int mW = img.size().width;
             int mH = img.size().height;
             double ratioWH = double((double)mH/(double)mW);
             h = (int)round((double)w * ratioWH);
         }
         cv::Mat resizeColor;
         cv::Size destSize = cv::Size(w,h);
         cv::resize(img, resizeColor, destSize, cv::INTER_CUBIC);
         img = resizeColor.clone();
     }//if img not empty
 }
Referenced by showKv2Demo().
resizeKv3Img()
void kv3::resizeKv3Img (cv::Mat & imSrcRgb, cv::Mat & imDepth, const int inW, const int inH)
resize depth and color image to the same size
input: w = width of the new images and h = height of the new images
in case h OR w = 0, then calculate the function the missing value to get a image with correct ratio.
Parameters
const int inW, const int inH output: resized images
cv::Mat &imSrcRgb, cv::Mat &imDepth,
Returns
void
Definition at line 1430 of file kv3.cpp.
{
     if((imSrcRgb.empty() == false)&&(imgDepthReg.empty()==false)){
         int w = inW;
         int h = inH;
         if(w <= 0){
             //calculate w
             int mW = imSrcRgb.size().width;
             int mH = imSrcRgb.size().height;
             double ratioWH = double((double)mW/(double)mH);
             w = (int)round((double)h * ratioWH);
         }
         if(h <= 0){
             //calculate h
             int mW = imSrcRgb.size().width;
             int mH = imSrcRgb.size().height;
             double ratioWH = double((double)mH/(double)mW);
             h = (int)round((double)w * ratioWH);
         }
         cv::Mat resizeColor;
         cv::Size destSize = cv::Size(w,h);
         cv::resize(imSrcRgb, resizeColor, destSize, cv::INTER_CUBIC);
         imSrcRgb = resizeColor.clone();
         cv::Mat resizeDepthReg;
         cv::resize(imgDepthReg, resizeDepthReg, destSize, cv::INTER_CUBIC);
         imDepth = resizeDepthReg.clone();
     }//if img not empty
 }
References imgDepthReg.
Referenced by main().
resizeKv3ImgColor()
void kv3::resizeKv3ImgColor (cv::Mat & imColor, const int inW, const int inH)
resize color image
input: width and height from the new size
Parameters
const int inW, const int inH output: imColor
cv::Mat &imColor,
Returns
void
Definition at line 1545 of file kv3.cpp.
{
     if(imgColor.empty() == false){
         int w = inW;
         int h = inH;
         if(w <= 0){
             //calculate w
             int mW = imgColor.size().width;
             int mH = imgColor.size().height;
             double ratioWH = double((double)mW/(double)mH);
             w = (int)round((double)h * ratioWH);
         }
         if(h <= 0){
             //calculate h
             int mW = imgColor.size().width;
             int mH = imgColor.size().height;
             double ratioWH = double((double)mH/(double)mW);
             h = (int)round((double)w * ratioWH);
         }
         cv::Mat resizeColor;
         cv::Size destSize = cv::Size(w,h);
         cv::resize(imgColor, resizeColor, destSize, cv::INTER_CUBIC);
         imColor = resizeColor.clone();
     }//if img not empty
 }
References imgColor.
resizeKv3IrImg()
void kv3::resizeKv3IrImg (cv::Mat & imIr, const int inW, const int inH)
resize image
input: width and height from the new size
Parameters
const int inW, const int inH output: resized image
cv::Mat &imIr,
Returns
void
Definition at line 1645 of file kv3.cpp.
{
     if(imgIr.empty() == false){
         int w = inW;
         int h = inH;
         if(w <= 0){
             //calculate w
             int mW = imgIr.size().width;
             int mH = imgIr.size().height;
             double ratioWH = double((double)mW/(double)mH);
             w = (int)round((double)h * ratioWH);
         }
         if(h <= 0){
             //calculate h
             int mW = imgIr.size().width;
             int mH = imgIr.size().height;
             double ratioWH = double((double)mH/(double)mW);
             h = (int)round((double)w * ratioWH);
         }
         cv::Mat resizeIr;
         cv::Size destSize = cv::Size(w,h);
         cv::resize(imgColor, resizeIr, destSize, cv::INTER_CUBIC);
         imIr = resizeIr.clone();
     }//if img not empty
 }
References imgColor, and imgIr.
setup()
void kv3::setup ()
setup the MS Kinect Azure modes
input:
Parameters
void Output:
void
Returns
void
Definition at line 628 of file kv3.cpp.
                {
     uint32_t device_count = k4a_device_get_installed_count();
     if (device_count == 0)
     {
         cout << "No K4A devices found" << endl;
         exit(0);
     }
     if (K4A_RESULT_SUCCEEDED != k4a_device_open(K4A_DEVICE_DEFAULT, &device))
     {
         cout << "No K4A devices found" << endl;
         if (device != NULL)
         {
             k4a_device_close(device);
         }
     }
     /*
     Config from - KinectAzureCapture --- https://github.com/WeLoveKiraboshi/KinectAzureCapture
     k4a_device_configuration_t config = K4A_DEVICE_CONFIG_INIT_DISABLE_ALL;
     config.synchronized_images_only = true;
     config.color_format = K4A_IMAGE_FORMAT_COLOR_BGRA32;//examples/transformation
     config.color_resolution = K4A_COLOR_RESOLUTION_1536P; //K4A_COLOR_RESOLUTION_720P;
     //config.depth_format = K4A_IMAGE_FORMAT_DEPTH16;//https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/
     //config.depth_mode = K4A_DEPTH_MODE_NFOV_UNBINNED;//640x576.
     config.depth_mode = K4A_DEPTH_MODE_WFOV_UNBINNED;//1024x1024.
     config.camera_fps = K4A_FRAMES_PER_SECOND_15; //30
     */
     /*
     Config from - k4a-measurement
     // Set the configuration of device, you can also set it after open the device but before starting the camera
     */
     k4a_device_configuration_t config = K4A_DEVICE_CONFIG_INIT_DISABLE_ALL;
     config.color_format = K4A_IMAGE_FORMAT_COLOR_BGRA32;  // <==== For Color image
     config.color_resolution = K4A_COLOR_RESOLUTION_720P; //K4A_COLOR_RESOLUTION_1080P;//K4A_COLOR_RESOLUTION_2160P;//K4A_COLOR_RESOLUTION_3072P;
     //config.depth_mode = K4A_DEPTH_MODE_WFOV_UNBINNED;
     //config.camera_fps = K4A_FRAMES_PER_SECOND_15;
     config.depth_mode = K4A_DEPTH_MODE_NFOV_UNBINNED;
     config.camera_fps = K4A_FRAMES_PER_SECOND_30;
     config.synchronized_images_only = true;
     /*
     Depth: config.depth_mode
         K4A_DEPTH_MODE_OFF
         Depth sensor will be turned off with this setting.
         K4A_DEPTH_MODE_NFOV_2X2BINNED
         Depth captured at 320x288.
         Passive IR is also captured at 320x288.
         K4A_DEPTH_MODE_NFOV_UNBINNED
         Depth captured at 640x576.
         Passive IR is also captured at 640x576.
         K4A_DEPTH_MODE_WFOV_2X2BINNED
         Depth captured at 512x512.
         Passive IR is also captured at 512x512.
         K4A_DEPTH_MODE_WFOV_UNBINNED
         Depth captured at 1024x1024.
         Passive IR is also captured at 1024x1024.
         K4A_DEPTH_MODE_PASSIVE_IR
         Passive IR only, captured at 1024x1024.
     COLOR: config.color_resolution
         K4A_COLOR_RESOLUTION_OFF
         Color camera will be turned off with this setting.
         K4A_COLOR_RESOLUTION_720P
         1280 * 720 16:9
         K4A_COLOR_RESOLUTION_1080P
         1920 * 1080 16:9
         K4A_COLOR_RESOLUTION_1440P
         2560 * 1440 16:9
         K4A_COLOR_RESOLUTION_1536P
         2048 * 1536 4:3
         K4A_COLOR_RESOLUTION_2160P
         3840 * 2160 16:9
         K4A_COLOR_RESOLUTION_3072P
         4096 * 3072 4:3
    */
     if (K4A_RESULT_SUCCEEDED !=
         k4a_device_get_calibration(device, config.depth_mode, config.color_resolution, &calibration))
     {
         cout << "Failed to get calibration" << endl;
         exit(0);
     }
         k4a_image_create(K4A_IMAGE_FORMAT_CUSTOM,
                         calibration.depth_camera_calibration.resolution_width,
                         calibration.depth_camera_calibration.resolution_height,
                         calibration.depth_camera_calibration.resolution_width * (int)sizeof(k4a_float2_t),
                         &kv3_xy_table);
         create_xy_table(&calibration, kv3_xy_table);
         k4a_image_create(K4A_IMAGE_FORMAT_CUSTOM,
                         calibration.depth_camera_calibration.resolution_width,
                         calibration.depth_camera_calibration.resolution_height,
                         calibration.depth_camera_calibration.resolution_width * (int)sizeof(k4a_float3_t),
                         &kv3ImPcl);
     setupCalib(); //get intrinsic data from color and depth cam
     if (K4A_RESULT_SUCCEEDED != k4a_device_start_cameras(device, &config))
     {
         cout << "Failed to start cameras" << endl;
         exit(0);
     }
     if (K4A_RESULT_SUCCEEDED != k4a_device_start_imu(device))
     {
         cout <<"Failed to get imu data from capture" << endl;
         exit(0);
     }
     readCurrentColorMode();
 }
References calibration, config, create_xy_table(), device, kv3_xy_table, kv3ImPcl, readCurrentColorMode(), and setupCalib().
Referenced by kv3Cam(), kv3RunCam(), main(), showKv2Demo(), and testSyncStart().
setupCalib()
void kv3::setupCalib () inline
setup the camera calibration from the depth camera and the color camera.
input:
Parameters
void
Returns
void
Definition at line 508 of file kv3.cpp.
{
     k4a_calibration_camera_t calib0 = calibration.depth_camera_calibration;
     cout << "\n===== Device "  << ": " << getSerialNumber(device) << " =====\n";
     cout << "depth camera resolution width: " << calib0.resolution_width << endl;
     cout << "depth camera resolution height: " << calib0.resolution_height << endl;
     cout << "depth camera principal point x: " << calib0.intrinsics.parameters.param.cx << endl;
     cout << "depth camera principal point y: " << calib0.intrinsics.parameters.param.cy << endl;
     cout << "depth camera focal length x: " << calib0.intrinsics.parameters.param.fx << endl;
     cout << "depth camera focal length y: " << calib0.intrinsics.parameters.param.fy << endl;
     cout << "depth camera radial distortion coefficients:" << endl;
     cout << "depth camera k1: " << calib0.intrinsics.parameters.param.k1 << endl;
     cout << "depth camera k2: " << calib0.intrinsics.parameters.param.k2 << endl;
     cout << "depth camera k3: " << calib0.intrinsics.parameters.param.k3 << endl;
     cout << "depth camera k4: " << calib0.intrinsics.parameters.param.k4 << endl;
     cout << "depth camera k5: " << calib0.intrinsics.parameters.param.k5 << endl;
     cout << "depth camera k6: " << calib0.intrinsics.parameters.param.k6 << endl;
     cout << "depth camera center of distortion in Z=1 plane, x: " << calib0.intrinsics.parameters.param.codx << endl;
     cout << "depth camera center of distortion in Z=1 plane, y: " << calib0.intrinsics.parameters.param.cody << endl;
     cout << "depth camera tangential distortion coefficient x: " << calib0.intrinsics.parameters.param.p1 << endl;
     cout << "depth camera tangential distortion coefficient y: " << calib0.intrinsics.parameters.param.p2 << endl;
     cout << "depth camera metric radius: " << calib0.intrinsics.parameters.param.metric_radius << endl;
     k4a_calibration_camera_t calib1 = calibration.color_camera_calibration;
     cout << "color camera resolution width: " << calib1.resolution_width << endl;
     cout << "color camera resolution height: " << calib1.resolution_height << endl;
     cout << "color camera principal point x: " << calib1.intrinsics.parameters.param.cx << endl;
     cout << "color camera principal point y: " << calib1.intrinsics.parameters.param.cy << endl;
     cout << "color camera focal length x: " << calib1.intrinsics.parameters.param.fx << endl;
     cout << "color camera focal length y: " << calib1.intrinsics.parameters.param.fy << endl;
     cout << "color camera radial distortion coefficients:" << endl;
     cout << "color camera k1: " << calib1.intrinsics.parameters.param.k1 << endl;
     cout << "color camera k2: " << calib1.intrinsics.parameters.param.k2 << endl;
     cout << "color camera k3: " << calib1.intrinsics.parameters.param.k3 << endl;
     cout << "color camera k4: " << calib1.intrinsics.parameters.param.k4 << endl;
     cout << "color camera k5: " << calib1.intrinsics.parameters.param.k5 << endl;
     cout << "color camera k6: " << calib1.intrinsics.parameters.param.k6 << endl;
     cout << "color camera center of distortion in Z=1 plane, x: " << calib1.intrinsics.parameters.param.codx << endl;
     cout << "color camera center of distortion in Z=1 plane, y: " << calib1.intrinsics.parameters.param.cody << endl;
     cout << "color camera tangential distortion coefficient x: " << calib1.intrinsics.parameters.param.p1 << endl;
     cout << "color camera tangential distortion coefficient y: " << calib1.intrinsics.parameters.param.p2 << endl;
     cout << "color camera metric radius: " << calib1.intrinsics.parameters.param.metric_radius << endl;
     transformation = k4a_transformation_create(&calibration);
     kv3::cx0 = (float)calib0.intrinsics.parameters.param.cx;
     kv3::cy0 = (float)calib0.intrinsics.parameters.param.cy;
     kv3::fx0 = (float)calib0.intrinsics.parameters.param.fx;
     kv3::fy0 = (float)calib0.intrinsics.parameters.param.fy;
     kv3::cx1 = (float)calib1.intrinsics.parameters.param.cx;
     kv3::cy1 = (float)calib1.intrinsics.parameters.param.cy;
     kv3::fx1 = (float)calib1.intrinsics.parameters.param.fx;
     kv3::fy1 = (float)calib1.intrinsics.parameters.param.fy;
 }
References calibration, cx0, cx1, cy0, cy1, device, fx0, fx1, fy0, fy1, getSerialNumber(), and transformation.
Referenced by setup().
shutdown()
void kv3::shutdown ()
This function release all open captured k4a_image_t images
- kv3ImColor
- kv3ImDepth
- kv3ImDepthReg
- kv3ImIr.
Parameters
void parameter
Returns
no return value
Definition at line 60 of file kv3.cpp.
                   {
     if(kv3ImColor != NULL){
         k4a_image_release(kv3ImColor);
     }
     if(kv3ImDepth != NULL){
         k4a_image_release(kv3ImDepth);
     }
     if(kv3ImDepthReg != NULL){
         k4a_image_release(kv3ImDepthReg);
     }
     if(kv3ImIr != NULL){
         k4a_image_release(kv3ImIr);
     }
     if (device != NULL){
         k4a_device_stop_cameras(device);
         k4a_device_close(device);
     }
 }
References device, kv3ImColor, kv3ImDepth, kv3ImDepthReg, and kv3ImIr.
Referenced by update(), and ~kv3().
testloop()
void kv3::testloop ()
demo to grap MS Kinect Azure data inside a loop (Ir, color, depth, IMU)
input:
Parameters
void Output:
void
Returns
void
Definition at line 799 of file kv3.cpp.
                   {
     k4a::Vector IMU_vec;
     k4a::Vector grav_vec;
     while(1){
         switch (k4a_device_get_capture(device, &capture, TIMEOUT_IN_MS))
         {
         case K4A_WAIT_RESULT_SUCCEEDED:
             capColor();
             capIr();
             capDepth();
             regDepth();
             capTemperature();
             updateIMU();
             //getIMU(IMU_vec);
             //getGravity(grav_vec);
             break;
         case K4A_WAIT_RESULT_TIMEOUT:
             printf("Timed out waiting for a capture\n");
             continue;
             break;
         case K4A_WAIT_RESULT_FAILED:
             printf("Failed to read a capture\n");
             if (device != NULL)
             {
                 k4a_device_stop_cameras(device);
                 k4a_device_close(device);
             }
         }
         char key = waitKey(10);
         if(key == 27){ break; }
     }
     // Shut down the camera when finished with application logic
     if(kv3ImColor != NULL){
         k4a_image_release(kv3ImColor);
     }
     if(kv3ImIr != NULL){
         k4a_image_release(kv3ImIr);
     }
     if(kv3ImDepth != NULL){
         k4a_image_release(kv3ImDepth);
     }
     if(kv3ImDepthReg != NULL){
         k4a_image_release(kv3ImDepthReg);
     }
     if (device != NULL){
         k4a_device_stop_cameras(device);
         k4a_device_close(device);
     }
 }
References capColor(), capDepth(), capIr(), capTemperature(), capture, device, kv3ImColor, kv3ImDepth, kv3ImDepthReg, kv3ImIr, regDepth(), TIMEOUT_IN_MS, and updateIMU().
update()
int kv3::update ()
update all MS Kinect Azure sensor data (Ir, color, depth, IMU)
input:
Parameters
void Output:
int retval
Returns
K4A_WAIT_RESULT_SUCCEEDED | K4A_WAIT_RESULT_SUCCEEDED | K4A_WAIT_RESULT_FAILED
Definition at line 768 of file kv3.cpp.
                {
     int retval = 0;
     k4a_wait_result_t resultInfo = k4a_device_get_capture(device, &capture, TIMEOUT_IN_MS);
     if(resultInfo == K4A_WAIT_RESULT_SUCCEEDED){
         capColor();
         capIr();
         capDepth();
         regDepth();
         updateIMU();
         retval = (1);
     }
     if(resultInfo == K4A_WAIT_RESULT_SUCCEEDED){
         //cout << "Timed out waiting for a capture" << endl;
         retval = (2);
     }
     if(resultInfo == K4A_WAIT_RESULT_FAILED){
         cout << "Failed to read a capture" << endl;
         shutdown();
         retval = (-1);
     }
     return(retval);
 }
References capColor(), capDepth(), capIr(), capture, device, regDepth(), shutdown(), TIMEOUT_IN_MS, and updateIMU().
Referenced by kv3Cam(), kv3RunCam(), main(), showKv2Demo(), and testSyncStart().
updateIMU()
void kv3::updateIMU () inline
capture the kinect azure IMU sensor
input:
Parameters
void
output: update internal variable
imuAcc: accelaration
imuGravity
imuTemperature
void
Returns
void
Error: comand line: "Failed to read a imu sample"
Definition at line 1228 of file kv3.cpp.
 {
     // Capture an IMU sample
     int32_t imu_timeout_ms = 60;
     switch (k4a_device_get_imu_sample(device, &imu_sample, imu_timeout_ms))
     {
         case K4A_WAIT_RESULT_SUCCEEDED:
             break;
         case K4A_WAIT_RESULT_TIMEOUT:
             cout <<"Timed out waiting for a imu sample" << endl;
         case K4A_WAIT_RESULT_FAILED:
             cout << "Failed to read a imu sample" << endl;
     }
     // Access the accelerometer readings
     imuAcc = imu_sample.acc_sample;
     imuGravity = extract_gravity_from_imu(imuAcc);
     imuTemperature = (float)imu_sample.temperature;
 }
References device, extract_gravity_from_imu(), imu_sample, imuAcc, imuGravity, and imuTemperature.
Referenced by testloop(), and update().
write_color_point_cloud()
void kv3::write_color_point_cloud (const char * file_name)
read the point cloud with color data via k4a commands and save it as PLY file to give path. input:
Parameters
const char *file_name = path and filename to the save location.
Returns
void
Definition at line 184 of file kv3.cpp.
 {
     std::vector<color_point_t> points;
     int width = k4a_image_get_width_pixels(kv3ImPcl);
     int height = k4a_image_get_height_pixels(kv3ImPcl);
     int16_t *point_cloud_image_data = (int16_t *)(void *)k4a_image_get_buffer(kv3ImPcl);
     uint8_t *color_image_data = k4a_image_get_buffer(kv3ImColor);
     for (int i = 0; i < width * height; i++)
     {
         color_point_t point;
         point.xyz[0] = point_cloud_image_data[3 * i + 0];
         point.xyz[1] = point_cloud_image_data[3 * i + 1];
         point.xyz[2] = point_cloud_image_data[3 * i + 2];
         if (point.xyz[2] == 0)
         {
             continue;
         }
         point.rgb[0] = color_image_data[4 * i + 0];
         point.rgb[1] = color_image_data[4 * i + 1];
         point.rgb[2] = color_image_data[4 * i + 2];
         uint8_t alpha = color_image_data[4 * i + 3];
         if (point.rgb[0] == 0 && point.rgb[1] == 0 && point.rgb[2] == 0 && alpha == 0)
         {
             continue;
         }
         points.push_back(point);
     }
 #define PLY_START_HEADER "ply"
 #define PLY_END_HEADER "end_header"
 #define PLY_ASCII "format ascii 1.0"
 #define PLY_ELEMENT_VERTEX "element vertex"
     // save to the ply file
     std::ofstream ofs(file_name); // text mode first
     ofs << PLY_START_HEADER << std::endl;
     ofs << PLY_ASCII << std::endl;
     ofs << PLY_ELEMENT_VERTEX << " " << points.size() << std::endl;
     ofs << "property float x" << std::endl;
     ofs << "property float y" << std::endl;
     ofs << "property float z" << std::endl;
     ofs << "property uchar red" << std::endl;
     ofs << "property uchar green" << std::endl;
     ofs << "property uchar blue" << std::endl;
     ofs << "element face 0" << std::endl;
     ofs << "property list uchar int vertex_indices" << std::endl;
     ofs << PLY_END_HEADER << std::endl;
     ofs.close();
     std::stringstream ss;
     for (size_t i = 0; i < points.size(); ++i)
     {
         // image data is BGR
         ss << (float)points[i].xyz[0] << " " << (float)points[i].xyz[1] << " " << (float)points[i].xyz[2];
         ss << " " << (float)points[i].rgb[2] << " " << (float)points[i].rgb[1] << " " << (float)points[i].rgb[0];
         ss << std::endl;
     }
     std::ofstream ofs_text(file_name, std::ios::out | std::ios::app);
     ofs_text.write(ss.str().c_str(), (std::streamsize)ss.str().length());
 }
References kv3ImColor, kv3ImPcl, PLY_ASCII, PLY_ELEMENT_VERTEX, PLY_END_HEADER, PLY_START_HEADER, color_point_t::rgb, and color_point_t::xyz.
writeColorPcl1()
void kv3::writeColorPcl1 (const char * file_name)
calculate the point cloud with improved the depth values and
transform color data size to depth image size via k4a commands and
save it as PLY file to give file path.
input:
Parameters
const char *file_name = path and filename to the save location.
Returns
void
Definition at line 333 of file kv3.cpp.
 {
     int width = k4a_image_get_width_pixels(kv3ImDepth);
     int height = k4a_image_get_height_pixels(kv3ImDepth);
     uint16_t *depth_data = (uint16_t *)(void *)k4a_image_get_buffer(kv3ImDepth);
     k4a_float2_t *xy_table_data = (k4a_float2_t *)(void *)k4a_image_get_buffer(kv3_xy_table);
     int widthXYtable = k4a_image_get_width_pixels(kv3_xy_table);
     int heightXYtable = k4a_image_get_height_pixels(kv3_xy_table);
     k4a_float3_t *point_cloud_data = (k4a_float3_t *)(void *)k4a_image_get_buffer(kv3ImPcl);
     int widthpcld = k4a_image_get_width_pixels(kv3ImPcl);
     int heightpcld = k4a_image_get_height_pixels(kv3ImPcl);
     int point_count = 0;
     int maxLimit = width * height;
     //cout << "--- ---- --- maxLimit: " << maxLimit << endl; //ok
     for (int i = 0; i < maxLimit; i++)
     {
         if (depth_data[i] != 0 && !isnan(xy_table_data[i].xy.x) && !isnan(xy_table_data[i].xy.y))
         {
             point_cloud_data[i].xyz.x = xy_table_data[i].xy.x * (float)depth_data[i];
             point_cloud_data[i].xyz.y = xy_table_data[i].xy.y * (float)depth_data[i];
             point_cloud_data[i].xyz.z = (float)depth_data[i];
             point_count++;
         }
         else
         {
             point_cloud_data[i].xyz.x = nanf("");
             point_cloud_data[i].xyz.y = nanf("");
             point_cloud_data[i].xyz.z = nanf("");
         }
     }
     // color image resize
     k4a_image_t kv3ImColorTrans = NULL;
     k4a_image_create(K4A_IMAGE_FORMAT_COLOR_BGRA32, width, height, width * 4 * (int)sizeof(uint8_t), &kv3ImColorTrans);
     k4a_transformation_color_image_to_depth_camera(transformation, kv3ImDepth, kv3ImColor, kv3ImColorTrans);
     uint8_t *colorImg = k4a_image_get_buffer(kv3ImColorTrans);
     // save to the ply file
     std::ofstream ofs(file_name); // text mode first
     ofs << "ply" << std::endl;
     ofs << "format ascii 1.0" << std::endl;
     ofs << "element vertex"
         << " " << point_count << std::endl;
     ofs << "property float x" << std::endl;
     ofs << "property float y" << std::endl;
     ofs << "property float z" << std::endl;
     ofs << "property uchar red" << std::endl;
     ofs << "property uchar green" << std::endl;
     ofs << "property uchar blue" << std::endl;
     ofs << "element face 0" << std::endl;
     ofs << "property list uchar int vertex_indices" << std::endl;
     ofs << "end_header" << std::endl;
     ofs.close();
     std::stringstream ss;
     for (int i = 0; i < width * height; i++)
     {
         if (isnan(point_cloud_data[i].xyz.x) || isnan(point_cloud_data[i].xyz.y) || isnan(point_cloud_data[i].xyz.z))
         {
             continue;
         }
         ss << (float)point_cloud_data[i].xyz.x << " "
         << (float)point_cloud_data[i].xyz.y << " "
         << (float)point_cloud_data[i].xyz.z << " "
         << (uint)colorImg[4 * i + 2] << " "
         << (uint)colorImg[4 * i + 1] << " "
         << (uint)colorImg[4 * i + 0] << " "
         << std::endl;
     }
     std::ofstream ofs_text(file_name, std::ios::out | std::ios::app);
     ofs_text.write(ss.str().c_str(), (std::streamsize)ss.str().length());
 }
References kv3_xy_table, kv3ImColor, kv3ImDepth, kv3ImPcl, and transformation.
Referenced by main().
writeColorPcl2()
void kv3::writeColorPcl2 (const char * file_name)
transform the depthReg image and the color image to a point cloud with color data via k4a commands and
save it as PLY file to give file path.
input:
Parameters
const char *file_name = path and filename to the save location.
Returns
void
Definition at line 420 of file kv3.cpp.
{
     int w = k4a_image_get_width_pixels(kv3ImDepthReg);
     int h = k4a_image_get_height_pixels(kv3ImDepthReg);
     int point_count = w * h;
     //int w = k4a_image_get_width_pixels(kv3ImDepth);
     //int h = k4a_image_get_height_pixels(kv3ImDepth);
     //PCL from depth image
     k4a_image_t pclImg = NULL;
     if (K4A_RESULT_SUCCEEDED != k4a_image_create(K4A_IMAGE_FORMAT_CUSTOM,
                                                  w,
                                                  h,
                                                  w * 3 * (int)sizeof(int16_t),
                                                  &pclImg))
     {
         printf("Failed to create point cloud image\n");
     }else{
         //printf("successful to create point cloud image\n");
     }
     if (K4A_RESULT_SUCCEEDED != k4a_transformation_depth_image_to_point_cloud(transformation,
                                                                               kv3ImDepthReg,
                                                                               K4A_CALIBRATION_TYPE_COLOR,
                                                                               pclImg))
     {
         printf("Failed to compute point cloud\n");
     }else{
         //printf("successful to compute point cloud\n");
     }
     int16_t *pclData = (int16_t *)(void *)k4a_image_get_buffer(pclImg);
     uint8_t *colorImg = k4a_image_get_buffer(kv3ImColor);
     // save to the ply file
     std::ofstream ofs(file_name); // text mode first
     ofs << "ply" << std::endl;
     ofs << "format ascii 1.0" << std::endl;
     ofs << "element vertex"
         << " " << point_count << std::endl;
     ofs << "property float x" << std::endl;
     ofs << "property float y" << std::endl;
     ofs << "property float z" << std::endl;
     ofs << "property uchar red" << std::endl;
     ofs << "property uchar green" << std::endl;
     ofs << "property uchar blue" << std::endl;
     ofs << "element face 0" << std::endl;
     ofs << "property list uchar int vertex_indices" << std::endl;
     ofs << "end_header" << std::endl;
     ofs.close();
     std::stringstream ss;
     int limitMax = w * h;
     for (int i = 0; i < limitMax; i++)
     {
         float pclx = pclData[3 * i + 0];
         float pcly = pclData[3 * i + 1];
         float pclz = pclData[3 * i + 2];
         if (isnan(pclx) || isnan(pcly) || isnan(pclz))
         {
             //continue;
             pclData[3 * i + 0] = 0;
             pclData[3 * i + 1] = 0;
             pclData[3 * i + 2] = 0;
         }
         ss << (float)pclData[3 * i + 0] << " "
            << (float)pclData[3 * i + 1] << " "
            << (float)pclData[3 * i + 2] << " "
            << (uint)colorImg[4 * i + 2] << " "
            << (uint)colorImg[4 * i + 1] << " "
            << (uint)colorImg[4 * i + 0] << " "
            << std::endl;
     }
     std::ofstream ofs_text(file_name, std::ios::out | std::ios::app);
     ofs_text.write(ss.str().c_str(), (std::streamsize)ss.str().length());
 }
References kv3ImColor, kv3ImDepthReg, and transformation.
Referenced by main().
writePCL()
void kv3::writePCL (const char * file_name)
read the point cloud without color data via k4a commands and
improve the depth values and
save it as PLY file to give file path.
input:
Parameters
const char *file_name = path and filename to the save location.
Returns
void
Definition at line 258 of file kv3.cpp.
 {
     int width = k4a_image_get_width_pixels(kv3ImDepth);
     int height = k4a_image_get_height_pixels(kv3ImDepth);
     uint16_t *depth_data = (uint16_t *)(void *)k4a_image_get_buffer(kv3ImDepth);
     k4a_float2_t *xy_table_data = (k4a_float2_t *)(void *)k4a_image_get_buffer(kv3_xy_table);
     int widthXYtable = k4a_image_get_width_pixels(kv3_xy_table);
     int heightXYtable = k4a_image_get_height_pixels(kv3_xy_table);
     k4a_float3_t *point_cloud_data = (k4a_float3_t *)(void *)k4a_image_get_buffer(kv3ImPcl);
     int widthpcld = k4a_image_get_width_pixels(kv3ImPcl);
     int heightpcld = k4a_image_get_height_pixels(kv3ImPcl);
     int point_count = 0;
     int maxLimit = width * height;
     //cout << "--- ---- --- maxLimit: " << maxLimit << endl; //ok
     for (int i = 0; i < maxLimit; i++)
     {
         if (depth_data[i] != 0 && !isnan(xy_table_data[i].xy.x) && !isnan(xy_table_data[i].xy.y))
         {
             point_cloud_data[i].xyz.x = xy_table_data[i].xy.x * (float)depth_data[i];
             point_cloud_data[i].xyz.y = xy_table_data[i].xy.y * (float)depth_data[i];
             point_cloud_data[i].xyz.z = (float)depth_data[i];
             point_count++;
         }
         else
         {
             point_cloud_data[i].xyz.x = nanf("");
             point_cloud_data[i].xyz.y = nanf("");
             point_cloud_data[i].xyz.z = nanf("");
         }
     }
     // save to the ply file
     std::ofstream ofs(file_name); // text mode first
     ofs << "ply" << std::endl;
     ofs << "format ascii 1.0" << std::endl;
     ofs << "element vertex"
         << " " << point_count << std::endl;
     ofs << "property float x" << std::endl;
     ofs << "property float y" << std::endl;
     ofs << "property float z" << std::endl;
     ofs << "element face 0" << std::endl;
     ofs << "property list uchar int vertex_indices" << std::endl;
     ofs << "end_header" << std::endl;
     ofs.close();
     std::stringstream ss;
     for (int i = 0; i < width * height; i++)
     {
         if (isnan(point_cloud_data[i].xyz.x) || isnan(point_cloud_data[i].xyz.y) || isnan(point_cloud_data[i].xyz.z))
         {
             continue;
         }
         ss << (float)point_cloud_data[i].xyz.x << " "
            << (float)point_cloud_data[i].xyz.y << " "
            << (float)point_cloud_data[i].xyz.z << std::endl;
     }
     std::ofstream ofs_text(file_name, std::ios::out | std::ios::app);
     ofs_text.write(ss.str().c_str(), (std::streamsize)ss.str().length());
 }
References kv3_xy_table, kv3ImDepth, and kv3ImPcl.
Referenced by main().
Member Data Documentation
calibration
k4a_calibration_t kv3::calibration
Definition at line 115 of file kv3.h.
Referenced by calcCvPclCamResize(), create_xy_table(), extract_gravity_from_imu(), setup(), and setupCalib().
capTemparature
float kv3::capTemparature static
Definition at line 136 of file kv3.h.
Referenced by capTemperature().
capture
k4a_capture_t kv3::capture = NULL static
Definition at line 116 of file kv3.h.
Referenced by capColor(), capDepth(), capIr(), capTemperature(), getCapTemperature(), testloop(), and update().
config
k4a_device_configuration_t kv3::config static private
Definition at line 157 of file kv3.h.
Referenced by convIrToVisible8BitGrayImg(), convIrToVisibleImg(), and setup().
cx0
float kv3::cx0 = 0 static
Definition at line 146 of file kv3.h.
Referenced by calcCvPclCamIr(), calcCvPclCamResize(), and setupCalib().
cx1
float kv3::cx1 = 0 static
Definition at line 151 of file kv3.h.
Referenced by calcCvPclCamColor(), calcCvPclCamResize(), and setupCalib().
cy0
float kv3::cy0 = 0 static
Definition at line 147 of file kv3.h.
Referenced by calcCvPclCamIr(), calcCvPclCamResize(), and setupCalib().
cy1
float kv3::cy1 = 0 static
Definition at line 152 of file kv3.h.
Referenced by calcCvPclCamColor(), calcCvPclCamResize(), and setupCalib().
device
k4a_device_t kv3::device = NULL static
Definition at line 113 of file kv3.h.
Referenced by getHardwareVersion(), getSerialNumber(), readCurrentColorMode(), setup(), setupCalib(), shutdown(), testloop(), update(), and updateIMU().
fx0
float kv3::fx0 = 0 static
Definition at line 148 of file kv3.h.
Referenced by calcCvPclCamIr(), calcCvPclCamResize(), and setupCalib().
fx1
float kv3::fx1 = 0 static
Definition at line 153 of file kv3.h.
Referenced by calcCvPclCamColor(), calcCvPclCamResize(), and setupCalib().
fy0
float kv3::fy0 = 0 static
Definition at line 149 of file kv3.h.
Referenced by calcCvPclCamIr(), calcCvPclCamResize(), and setupCalib().
fy1
float kv3::fy1 = 0 static
Definition at line 154 of file kv3.h.
Referenced by calcCvPclCamColor(), calcCvPclCamResize(), and setupCalib().
imgColor
cv::Mat kv3::imgColor
Definition at line 138 of file kv3.h.
Referenced by capColor(), cropKv3Img(), getCvColorImg(), resizeKv3ImgColor(), and resizeKv3IrImg().
imgDepth
cv::Mat kv3::imgDepth
Definition at line 140 of file kv3.h.
Referenced by capDepth(), and getCvDepthImg().
imgDepthReg
cv::Mat kv3::imgDepthReg
Definition at line 141 of file kv3.h.
Referenced by cropKv3Img(), getCvRegDepthImg(), regDepth(), and resizeKv3Img().
imgHeight
int kv3::imgHeight = 360 static
Definition at line 112 of file kv3.h.
imgIr
cv::Mat kv3::imgIr
Definition at line 139 of file kv3.h.
Referenced by capIr(), cropKv3IrImg(), getCvIrImg(), and resizeKv3IrImg().
imgRegRGB
cv::Mat kv3::imgRegRGB static
Definition at line 144 of file kv3.h.
imgWidth
int kv3::imgWidth = 360 static
Definition at line 111 of file kv3.h.
imu_sample
k4a_imu_sample_t kv3::imu_sample
Definition at line 123 of file kv3.h.
Referenced by updateIMU().
imuAcc
k4a::Vector kv3::imuAcc
Definition at line 124 of file kv3.h.
Referenced by extract_gravity_from_imu(), getIMU(), and updateIMU().
imuGravity
k4a::Vector kv3::imuGravity
Definition at line 125 of file kv3.h.
Referenced by getGravity(), and updateIMU().
imuTemperature
float kv3::imuTemperature static
Definition at line 135 of file kv3.h.
Referenced by getImuTemperature(), and updateIMU().
k4aHwVer_HwVersion
k4a_hardware_version_t* kv3::k4aHwVer_HwVersion
Definition at line 114 of file kv3.h.
Referenced by getHardwareVersion().
kv3_depth_image
k4a_image_t kv3::kv3_depth_image = NULL static
Definition at line 129 of file kv3.h.
kv3_point_count
int kv3::kv3_point_count = 0 static
Definition at line 132 of file kv3.h.
kv3_xy_table
k4a_image_t kv3::kv3_xy_table = NULL static
Definition at line 130 of file kv3.h.
Referenced by setup(), writeColorPcl1(), and writePCL().
kv3ImColor
k4a_image_t kv3::kv3ImColor
Definition at line 119 of file kv3.h.
Referenced by capColor(), regDepth(), shutdown(), testloop(), write_color_point_cloud(), writeColorPcl1(), and writeColorPcl2().
kv3ImDepth
k4a_image_t kv3::kv3ImDepth
Definition at line 121 of file kv3.h.
Referenced by capDepth(), regDepth(), shutdown(), testloop(), writeColorPcl1(), and writePCL().
kv3ImDepthReg
k4a_image_t kv3::kv3ImDepthReg
Definition at line 122 of file kv3.h.
Referenced by regDepth(), shutdown(), testloop(), and writeColorPcl2().
kv3ImIr
k4a_image_t kv3::kv3ImIr
Definition at line 120 of file kv3.h.
Referenced by capIr(), shutdown(), and testloop().
kv3ImPcl
k4a_image_t kv3::kv3ImPcl = NULL static
Definition at line 131 of file kv3.h.
Referenced by setup(), write_color_point_cloud(), writeColorPcl1(), and writePCL().
pclKv2
cv::Mat kv3::pclKv2 static
Definition at line 143 of file kv3.h.
serialNumber
string kv3::serialNumber static
Definition at line 134 of file kv3.h.
Referenced by getSerialNumber().
TIMEOUT_IN_MS
const int32_t kv3::TIMEOUT_IN_MS = 1000
Definition at line 118 of file kv3.h.
Referenced by testloop(), and update().
transformation
k4a_transformation_t kv3::transformation = NULL static
Definition at line 117 of file kv3.h.
Referenced by regDepth(), setupCalib(), writeColorPcl1(), and writeColorPcl2().
The documentation for this class was generated from the following files:
/media/hd2/dev/kinectV3/kv3Pcl/include/kv3.h
/media/hd2/dev/kinectV3/kv3Pcl/src/kv3.cpp