kv3_framework: pclApp Class Reference
pclApp Class Reference
#include "pclApp.h"
Public Member Functions
pclApp ()
~pclApp ()
void mainStart ()
void renderLoop ()
void loadPlyTestPcl ()
void testPclObjectDetectionPipe01 ()
void testPclRgbObjectDetectionPipe01 ()
void testViewsWithNormals ()
void testViewsWithViewports ()
void testLineCreater (float x, float y, float z)
void testTranformOrientationToPlane ()
void testBigestPlaneOrientationToPlane ()
void convMatPclToPCL (const cv::Mat &srcPcl, const cv::Mat &srcRgb, pcl::PointCloud< pcl::PointXYZRGB >::Ptr &out, int xmax, int ymax)
void convMatPclToPCL (const cv::Mat &srcPcl, pcl::PointCloud< pcl::PointXYZRGB >::Ptr &out, int xmax, int ymax)
Public Attributes
pclUtilitys * pclUti
pcl::PLYReader Reader
pcl::PointCloud< pcl::PointXYZ >::Ptr rootPcl
pcl::PointCloud< pcl::PointXYZRGB >::Ptr rootPclRgb
pcl::PointCloud< pcl::PointXYZRGB >::Ptr rootPclRgbFull
pcl::PointCloud< pcl::PointXYZ >::Ptr rootPcl2
pcl::PointCloud< pcl::PointXYZRGB >::Ptr rootPclRgb2
pcl::PointCloud< pcl::PointXYZRGB >::Ptr rootPclRgb2Full
pcl::PointCloud< pcl::PointXYZ >::Ptr rootPcl3
pcl::PointCloud< pcl::PointXYZRGB >::Ptr rootPclRgb3
pcl::PointCloud< pcl::PointXYZ >::Ptr rootPclResult
pcl::PointCloud< pcl::PointXYZRGB >::Ptr rootPclRgbResult
Static Public Attributes
static int rootPclSize = 0
static int rootPclRgbSize = 0
static int rootPclResultSize = 0
static int rootPclRgbResultSize = 0
Detailed Description
Definition at line 60 of file pclApp.h.
Constructor & Destructor Documentation
pclApp()
pclApp::pclApp ()
Definition at line 21 of file pclApp.cpp.
 {}
~pclApp()
pclApp::~pclApp ()
Definition at line 22 of file pclApp.cpp.
 {}
Member Function Documentation
convMatPclToPCL() [1/2]
void pclApp::convMatPclToPCL (const cv::Mat & srcPcl, const cv::Mat & srcRgb, pcl::PointCloud< pcl::PointXYZRGB >::Ptr & out, int xmax, int ymax)
convert opencv Mat PCL image and opencv color mat image to pointcloud library color PCL input:
Parameters
Mat PCL, Mat colorImage, int xmax = pcl width, int ymax pcl height output:
pcl::PointCloud<pcl::PointXYZRGB>::Ptr& out
Returns
void
Definition at line 33 of file pclApp.cpp.
{
     long int counter = 0;
     int y=0;
     int x=0;
     y=0;
     while(y<ymax){
         x=0;
         while(x<xmax){
             float z = srcPcl.at<cv::Vec3f>(y,x)[2];//pcl z value
             if((z > 0.001)||(z < -0.001)){
                 pcl::PointXYZRGB point;
                 point.x = srcPcl.at<cv::Vec3f>(y,x)[0];
                 point.y = srcPcl.at<cv::Vec3f>(y,x)[1];
                 point.z = srcPcl.at<cv::Vec3f>(y,x)[2];
                 point.r = srcRgb.at<Vec3b>(y,x)[2];
                 point.g = srcRgb.at<Vec3b>(y,x)[1];
                 point.b = srcRgb.at<Vec3b>(y,x)[0];
                 out->push_back(point);
                 counter++;
             }
             x++;
         }
         y++;
     }
     //cout << "counter: " << counter << endl;
     out->points.resize((uint32_t)counter);
 }
References z.
convMatPclToPCL() [2/2]
void pclApp::convMatPclToPCL (const cv::Mat & srcPcl, pcl::PointCloud< pcl::PointXYZRGB >::Ptr & out, int xmax, int ymax)
convert opencv Mat PCL image to pointcloud library color PCL input:
Parameters
Mat PCL, int xmax = pcl width, int ymax pcl height output:
pcl::PointCloud<pcl::PointXYZRGB>::Ptr& out
Returns
void
Definition at line 70 of file pclApp.cpp.
{
     long int counter = 0;
     int y=0;
     int x=0;
     y=0;
     while(y<ymax){
         x=0;
         while(x<xmax){
             float z = srcPcl.at<cv::Vec3f>(y,x)[2];//pcl z value
             if((z > 0.001)||(z < -0.001)){
                 pcl::PointXYZRGB point;
                 point.x = srcPcl.at<cv::Vec3f>(y,x)[0];
                 point.y = srcPcl.at<cv::Vec3f>(y,x)[1];
                 point.z = srcPcl.at<cv::Vec3f>(y,x)[2];
                 out->push_back(point);
                 counter++;
             }
             x++;
         }
         y++;
     }
     //cout << "counter: " << counter << endl;
     out->points.resize((uint32_t)counter);
 }
References z.
loadPlyTestPcl()
void pclApp::loadPlyTestPcl ()
load ply to different formats
Returns
void
Definition at line 100 of file pclApp.cpp.
{
     pcl::PointCloud<pcl::PointXYZ>::Ptr pcl01 (new pcl::PointCloud<pcl::PointXYZ>);
     rootPcl = pcl01;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr pcl02 (new pcl::PointCloud<pcl::PointXYZRGB>);
     rootPclRgb = pcl02;
     pcl::PointCloud<pcl::PointXYZ>::Ptr pcl03 (new pcl::PointCloud<pcl::PointXYZ>);
     rootPcl2 = pcl03;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr pcl04 (new pcl::PointCloud<pcl::PointXYZRGB>);
     rootPclRgb2 = pcl04;
     pcl::PointCloud<pcl::PointXYZ>::Ptr pcl05 (new pcl::PointCloud<pcl::PointXYZ>);
     rootPcl3 = pcl05;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr pcl06 (new pcl::PointCloud<pcl::PointXYZRGB>);
     rootPclRgb3 = pcl06;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr pcl07 (new pcl::PointCloud<pcl::PointXYZRGB>);
     rootPclRgbFull = pcl07;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr pcl08 (new pcl::PointCloud<pcl::PointXYZRGB>);
     rootPclRgb2Full = pcl08;
 /*
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/5_042190541047_PCL.ply", *rootPcl);
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/5_042190541047_PCLrgb.ply", *rootPclRgb);    //0_042190541047PCLEdgeRgb.ply //0_042190541047_PCLrgb
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/6_042190541047_PCL.ply", *rootPcl2);
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/6_042190541047_PCLrgb.ply", *rootPclRgb2);
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/7_042190541047_PCL.ply", *rootPcl3);
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/7_042190541047_PCLrgb.ply", *rootPclRgb3);
 */
     //Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/5_042190541047_PCL.ply", *rootPcl);
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/5_042190541047PCLEdgeRgb.ply", *rootPclRgb); //0_042190541047PCLEdgeRgb.ply //0_042190541047_PCLrgb
     //Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/6_042190541047_PCL.ply", *rootPcl2);
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/6_042190541047PCLEdgeRgb.ply", *rootPclRgb2);
     //Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/7_042190541047_PCL.ply", *rootPcl3);
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/7_042190541047PCLEdgeRgb.ply", *rootPclRgb3);
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/5_042190541047_PCLrgb.ply", *rootPclRgbFull);
     Reader.read("/media/hd2/db/RGBD/kv2/kv2Rec/6_042190541047_PCLrgb.ply", *rootPclRgb2Full);
     //pclUti->convertXYZBGRtoRGB(*rootPclRgb); PCLEdgeRgb
     pclUti->convertXYZRGBtoXYZ(*rootPclRgb, rootPcl);
     pclUti->convertXYZRGBtoXYZ(*rootPclRgb2, rootPcl2);
     pclUti->convertXYZRGBtoXYZ(*rootPclRgb3, rootPcl3);
     pclApp::rootPclSize = (int)rootPcl->size();
     pclApp::rootPclRgbSize = (int)rootPclRgb->size();
 }
References pclUtilitys::convertXYZRGBtoXYZ(), pclUti, Reader, rootPcl, rootPcl2, rootPcl3, rootPclRgb, rootPclRgb2, rootPclRgb2Full, rootPclRgb3, rootPclRgbFull, rootPclRgbSize, and rootPclSize.
mainStart()
void pclApp::mainStart ()
start main with utility functions
Returns
void
Definition at line 467 of file pclApp.cpp.
{
     pclUtilitys myPclUtilitysObj = pclUtilitys();
     pclApp::pclUti = &myPclUtilitysObj;
     //convMatPclToPCL();
     //loadPlyTestPcl();
         //testViewsWithViewports();
         //testViewsWithNormals();
         //testPclObjectDetectionPipe01();
         //testPclRgbObjectDetectionPipe01();
         //testLineCreater(2.0, 0, 0);
         //testTranformOrientationToPlane();
     //testObj.Run(strFilePath, Feature3d::Method::Harris); //ok sehr viele keypoints
     //testObj.Run(strFilePath, Feature3d::Method::ISS); //ok sehr viele keypoints auf den Sitzen weniger an der Wand,
     //testObj.Run(strFilePath, Feature3d::Method::SIFT); // ok sehr viele keypoints
 }
References pclUti.
renderLoop()
void pclApp::renderLoop ()
Render loop
Returns
void
Definition at line 151 of file pclApp.cpp.
{
     /*
     float angular_resolution_x = (float) (  1.0f * (M_PI/180.0f));  //   1.0 degree in radians
     float angular_resolution_y = (float) (  1.0f * (M_PI/90.0f));  //   1.0 degree in radians
     float maxAngleWidth     = (float) (360.0f * (M_PI/180.0f));  // 360.0 degree in radians
     float maxAngleHeight    = (float) (180.0f * (M_PI/180.0f));  // 180.0 degree in radians
     Eigen::Affine3f scene_sensor_pose (Eigen::Affine3f::Identity ());
     float noiseLevel=0.00;
     float minRange = 0.0f;
     int borderSize = 1;
     */
     while (!pclUti->viewer->wasStopped ()){
         //pclUti->range_image_widget.spinOnce ();
         pclUti->viewer->spinOnce (1);
         std::this_thread::sleep_for(33ms);
         /*
         scene_sensor_pose = pclUti->viewer->getViewerPose();
         pclUti->range_image->createFromPointCloud (*rootPcl, angular_resolution_x, angular_resolution_y,
                                           pcl::deg2rad (360.0f), pcl::deg2rad (180.0f),
                                           scene_sensor_pose, pcl::RangeImage::LASER_FRAME, noiseLevel, minRange, borderSize);
         pclUti->range_image_widget.showRangeImage (*pclUti->range_image);
         */
     }
 }
References pclUti, and pclUtilitys::viewer.
Referenced by testLineCreater(), testPclRgbObjectDetectionPipe01(), testTranformOrientationToPlane(), testViewsWithNormals(), and testViewsWithViewports().
testBigestPlaneOrientationToPlane()
void pclApp::testBigestPlaneOrientationToPlane ()
test bigest plane orientation to plane
Returns
void
Definition at line 454 of file pclApp.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr pclRgb1 (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr pclRgb2 (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr dummy1 (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr dummy2 (new pcl::PointCloud<pcl::PointXYZRGB>);
 }
testLineCreater()
void pclApp::testLineCreater (float x, float y, float z)
test line creater input:
Parameters
float x, float y, float z
Returns
void
Definition at line 388 of file pclApp.cpp.
{
     //pcl::PointCloud<pcl::PointXYZ>::Ptr cloudIn (new pcl::PointCloud<pcl::PointXYZ>);
     //pcl::PointCloud<pcl::PointXYZRGB> axisPcl;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr axisPcl (new pcl::PointCloud<pcl::PointXYZRGB>);
     //axisPcl->width = 20;
     //axisPcl->height = 20;
     axisPcl->is_dense = true;
     //axisPcl->points.resize(axisPcl->width * axisPcl->height);
     float ix = x;
     float iy = y;
     float iz = z;
     float step = 0.01;
     int i=0;
     int imax=100;
     while(i<imax){
         pcl::PointXYZRGB axisPointX = pcl::PointXYZRGB(ix,y,z ,255,0,0);
         pcl::PointXYZRGB axisPointY = pcl::PointXYZRGB(x,iy,z ,0,255,0);
         pcl::PointXYZRGB axisPointZ = pcl::PointXYZRGB(x,y,iz ,0,0,255);
         axisPcl->push_back(axisPointX);
         ix = ix + step;
         axisPcl->push_back(axisPointY);
         iy = iy + step;
         axisPcl->push_back(axisPointZ);
         iz = iz + step;
     i++;
     }
     //std::cout << "Resulting sift points are of size: " << axisPcl->size () <<std::endl;
     //pcl::io::savePLYFile("/media/hd2/dev/pcl/test.ply", *axisPcl);
     //Viewer selection
     pclUti->viewer = pclUti->rgbVis(axisPcl);
     //pclUti->viewer = pclUti->rgbVis(rootPclRgb);
     renderLoop();
 }
References pclUti, renderLoop(), pclUtilitys::rgbVis(), pclUtilitys::viewer, and z.
testPclObjectDetectionPipe01()
void pclApp::testPclObjectDetectionPipe01 ()
testPclRgbObjectDetectionPipe01()
void pclApp::testPclRgbObjectDetectionPipe01 ()
test to detect object inside RGB PCL
Returns
void
Definition at line 215 of file pclApp.cpp.
{
     //PCL RGB
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudBufferRgb (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudClusterRgb (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudMergedRgb (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudDummyOutRgb (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZI>::Ptr cloudIOut (new pcl::PointCloud<pcl::PointXYZI>);
     pcl::PointCloud<pcl::PointXYZ>::Ptr pclfilter1 (new pcl::PointCloud<pcl::PointXYZ>);
     pcl::PointCloud<pcl::PointXYZ>::Ptr pclfilter2 (new pcl::PointCloud<pcl::PointXYZ>);
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudBuffer (new pcl::PointCloud<pcl::PointXYZ>);
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudMerged (new pcl::PointCloud<pcl::PointXYZ>);
     pcl::PointCloud<pcl::PointXYZ>::Ptr cloudXYZCluster (new pcl::PointCloud<pcl::PointXYZ>);
     // Rotate
     float theta;
     //theta = (float)((float)180.0f*(float)((float)M_PI)/(float)180.0f);
     //cout << "theta:" << theta << endl;
     //pclUti->rotateZ(*rootPclRgb, *cloudBufferRgb, theta);
     //  Prepocess
     //pclUti->voxelGridRgb(*rootPclRgb, *cloudBufferRgb, 0.02f); //do not use before keypoint detection
     //pclUti->statisticalOutlierRemovalFilterRgb(*rootPclRgb, *cloudBufferRgb, 300, 1.0); //ok
     // TEST AREA
     /*
     pcl::RangeImage::Ptr range_image_New(new pcl::RangeImage);
     pclUti->createRangeImageFromPcl(*rootPcl, rangeImage); //ok
     *range_image_New = rangeImage;
     */
 //  pclUti->voxelGrid(*rootPcl, *cloudBuffer, 0.02f); //ok
 //  pclUti->statisticalOutlierRemovalFilter(*cloudBuffer, *cloudBuffer, 300, 1.5); //ok
     /*
     pclUti->extractPlaneFromCloud(*cloudBuffer, *cloudBuffer, true);//ok
     pclUti->extractPlaneFromCloud(*cloudBuffer, *cloudBuffer, true);//ok
     pclUti->extractPlaneFromCloud(*cloudBuffer, *cloudBuffer, true);//ok
     pclUti->extractPlaneFromCloud(*cloudBuffer, *cloudBuffer, true);//ok
     pclUti->extractPlaneFromCloud(*cloudBuffer, *cloudBuffer, true);//ok
     pclUti->doEuclideanClustering(*cloudBuffer, *cloudXYZCluster);
     */
     //pclUti->voxelGridRgb(*rootPclRgb, *cloudBufferRgb, 0.02f); //ok 0.02f is nice compromise
     //pclUti->statisticalOutlierRemovalFilterRgb(*cloudBufferRgb, *cloudBufferRgb, 300, 1.5); //ok
     /*
     pclUti->extractPlaneFromCloudRgb(*cloudBufferRgb, *cloudBufferRgb, true);//ok
     pclUti->extractPlaneFromCloudRgb(*cloudBufferRgb, *cloudBufferRgb, true);//ok
     pclUti->extractPlaneFromCloudRgb(*cloudBufferRgb, *cloudBufferRgb, true);//ok
     pclUti->extractPlaneFromCloudRgb(*cloudBufferRgb, *cloudBufferRgb, true);//ok
     cout << "preprocessing done ..." << endl;
     pclUti->doEuclideanClusteringRgb(*cloudBufferRgb, *cloudClusterRgb);
     */
     //pclUti->doRegionGrowingSegmentationColor(*cloudBufferRgb, *cloudClusterRgb);//ok
     //pclUti->doRegionGrowingSegmentation(*rootPcl, *cloudClusterRgb); //ok
     //pclUti->testRandomSampleConsensus();// nok ???
     //pclUti->doConditionalEuclideanClusteringRgb(*cloudBufferRgb,*cloudBufferRgb);//NOK
     //pclUti->doEuclideanClusteringRgb(*cloudBufferRgb, *cloudClusterRgb);
     //pclUti->testDoEuclideanClusteringRgb(*cloudBufferRgb, *cloudClusterRgb);
     //pclUti->doCylinderSegmentationRgb(*cloudBufferRgb, *cloudClusterRgb);
     //pclUti->narfKeypointExtractionRgb(*cloudBufferRgb, *cloudClusterRgb);
     //pclUti->rotateZ(*rootPclRgb, *cloudBufferRgb);
     //pclUti->keypointExtractionNARF(*cloudBufferRgb, *cloudClusterRgb); //ok
     //pclUti->keypointExtractionISS(*cloudBufferRgb, *cloudClusterRgb); //ok
     //pclUti->keypointExtractionSIFT(*cloudBufferRgb, *cloudClusterRgb); //ok
     //pclUti->keypointExtractionHarris(*cloudBufferRgb, *cloudClusterRgb); //ok
     //pcl::copyPointCloud(*rootPclRgb,*cloudClusterRgb);
     /*
     pclUti->convertZPcl(*cloudClusterRgb);
     // Rotate
     theta = (float)((float)-180.0f*(float)((float)M_PI)/(float)180.0f);
     pclUti->rotateY(*cloudClusterRgb, *cloudClusterRgb, theta);
         theta = (float)((float)-180.0f*(float)((float)M_PI)/(float)180.0f);
     pclUti->rotateZ(*cloudClusterRgb, *cloudClusterRgb, theta);
     */
     //pclUti->translationXYZ(*rootPclRgb, *cloudClusterRgb, 0, 0, 0);
     //pclUti->setPclRGBColor(*cloudClusterRgb, 255.0, 0, 0);
     //pclUti->FastPointFeatureHistogramsExample(*cloudBufferRgb, *cloudClusterRgb, *cloudDummyOutRgb); //ok - works not optimal
 /*
     pclUti->voxelGrid(*rootPcl, *pclfilter1, 0.020f); //ok
     pclUti->voxelGrid(*rootPcl2, *pclfilter2, 0.020f); //ok
     pcl::PointCloud<pcl::PointNormal>::Ptr src_normals_ptr (new pcl::PointCloud<pcl::PointNormal>);
     pcl::PointCloud<pcl::PointNormal>::Ptr tar_normals_ptr (new pcl::PointCloud<pcl::PointNormal>);
     pclUti->getNormalsFromCloud(*pclfilter1, *src_normals_ptr);
     pclUti->getNormalsFromCloud(*pclfilter2, *tar_normals_ptr);
     pcl::PointCloud<pcl::PointWithScale>::Ptr src_keypoints_ptr (new pcl::PointCloud<pcl::PointWithScale>);
     pclUti->keypointExtractionSIFT(*pclfilter1, src_normals_ptr, *src_keypoints_ptr);   //voxel grid error
     pcl::PointCloud<pcl::PointWithScale>::Ptr tar_keypoints_ptr (new pcl::PointCloud<pcl::PointWithScale>);
     pclUti->keypointExtractionSIFT(*pclfilter2, tar_normals_ptr, *tar_keypoints_ptr);
     Eigen::Matrix4f tform = Eigen::Matrix4f::Identity();
     pclUti->extractFPFHfromKeypoints(*pclfilter1, *pclfilter2,
                                      *src_keypoints_ptr, *tar_keypoints_ptr,
                                      *src_normals_ptr, *tar_normals_ptr,
                                      tform);
     //pcl::transformPointCloud(*pclfilter1, *cloudBuffer, tform); //cloudBuffer = is tformed pclfilter1
     //pclUti->mergeXYZPcl(*cloudBuffer, *pclfilter2, cloudMerged);
 */
     Eigen::Matrix4f tform = Eigen::Matrix4f::Identity();
     pclUti->reconTwoPcl(*rootPcl, *rootPcl2, tform);
     //pcl::transformPointCloud(*rootPcl, *cloudBuffer, tform); //cloudBuffer = is tformed rootPCL
     //pclUti->mergeXYZPcl(*cloudBuffer, *rootPcl2, cloudMerged);
     pcl::transformPointCloud(*rootPclRgbFull, *cloudBufferRgb, tform); //cloudBuffer = is tformed rootPCL
     pclUti->mergeXYZRGBPcl(*cloudBufferRgb, *rootPclRgb2Full, cloudMergedRgb);
     //update data
     rootPclResult = cloudMerged;
     rootPclRgbResult = cloudMergedRgb;
     pclApp::rootPclResultSize = (int)rootPclResult->size();
     pclApp::rootPclRgbResultSize = (int)rootPclRgbResult->size();
     //Viewer selection
     pclUti->viewer = pclUti->viewportsDiffVisRgb(rootPclRgb, rootPclRgbResult);
     //pclUti->momentOfInertiaRgb(*cloudClusterRgb); //ok
     //pclUti->viewer = pclUti->viewportsDiffVis(rootPcl, rootPclResult);
     //pclUti->viewer = pclUti->simpleRangeImgVis(range_image_New);
     //--------------------
     // -----Main loop-----
     //--------------------
     renderLoop();
 }
References pclUtilitys::mergeXYZRGBPcl(), pclUti, pclUtilitys::reconTwoPcl(), renderLoop(), rootPcl, rootPcl2, rootPclResult, rootPclResultSize, rootPclRgb, rootPclRgb2Full, rootPclRgbFull, rootPclRgbResult, rootPclRgbResultSize, pclUtilitys::viewer, and pclUtilitys::viewportsDiffVisRgb().
testTranformOrientationToPlane()
void pclApp::testTranformOrientationToPlane ()
test Transform to Orientation to plane
Returns
void
Definition at line 431 of file pclApp.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr pclRgb1 (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr pclRgb2 (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr dummy1 (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr dummy2 (new pcl::PointCloud<pcl::PointXYZRGB>);
     pclUti->setWallrelativeToOriginXY(*rootPclRgbFull, *dummy1);
     //pclUti->setWallrelativeToOriginXY(*rootPclRgb2Full, *dummy2);
         //pclUti->createWallPlane(dummy1);
         //pclUti->mergeXYZRGBPcl(*rootPclRgbFull, *dummy1, pclRgb1);
     //pclUti->viewer = pclUti->rgbVis(dummy1);
     pclUti->viewer = pclUti->viewportsDiffVisRgb(rootPclRgbFull, dummy1);
     //pclUti->viewer = pclUti->viewportsDiffVisRgb(rootPclRgb2Full, dummy2);
     //pclUti->viewer = pclUti->rgbVisDouble(pclRgb1, pclRgb2);
     renderLoop();
 }
References pclUti, renderLoop(), rootPclRgbFull, pclUtilitys::setWallrelativeToOriginXY(), pclUtilitys::viewer, and pclUtilitys::viewportsDiffVisRgb().
testViewsWithNormals()
void pclApp::testViewsWithNormals ()
view the normals
Returns
void
Definition at line 182 of file pclApp.cpp.
{
     //boost::shared_ptr<pcl::visualization::PCLVisualizer> openCloud;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr myCloud (new pcl::PointCloud<pcl::PointXYZRGB>);
     pcl::PointCloud<pcl::Normal>::Ptr myNormals (new pcl::PointCloud<pcl::Normal>);
     pclUti->voxelGridRgb(*rootPclRgb, *rootPclRgb, 0.06f);
     pclUti->statisticalOutlierRemovalFilterRgb(*rootPclRgb, *rootPclRgb, 50, 1.0);
     pclUti->getNormalsFromCloudRgb(*rootPclRgb, *myNormals);
     pclUti->viewer = pclUti->normalsVis(rootPclRgb, myNormals);
     renderLoop();
 }
References pclUtilitys::getNormalsFromCloudRgb(), pclUtilitys::normalsVis(), pclUti, renderLoop(), rootPclRgb, pclUtilitys::statisticalOutlierRemovalFilterRgb(), pclUtilitys::viewer, and pclUtilitys::voxelGridRgb().
testViewsWithViewports()
void pclApp::testViewsWithViewports ()
view with viewports
Returns
void
Definition at line 201 of file pclApp.cpp.
{
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudVRgb (new pcl::PointCloud<pcl::PointXYZRGB>);
     //viewer = viewportsVis(rootPcl,rootPclRgb);
     pclUti->voxelGridRgb(*rootPclRgb, *cloudVRgb, 0.04f);
     pclUti->viewer = pclUti->viewportsDiffVisRgb(rootPclRgb, cloudVRgb);
     renderLoop();
 }
References pclUti, renderLoop(), rootPclRgb, pclUtilitys::viewer, pclUtilitys::viewportsDiffVisRgb(), and pclUtilitys::voxelGridRgb().
Member Data Documentation
pclUti
pclUtilitys* pclApp::pclUti
Definition at line 84 of file pclApp.h.
Referenced by loadPlyTestPcl(), mainStart(), renderLoop(), testLineCreater(), testPclRgbObjectDetectionPipe01(), testTranformOrientationToPlane(), testViewsWithNormals(), and testViewsWithViewports().
Reader
pcl::PLYReader pclApp::Reader
Definition at line 85 of file pclApp.h.
Referenced by loadPlyTestPcl().
rootPcl
pcl::PointCloud<pcl::PointXYZ>::Ptr pclApp::rootPcl
Definition at line 86 of file pclApp.h.
Referenced by loadPlyTestPcl(), and testPclRgbObjectDetectionPipe01().
rootPcl2
pcl::PointCloud<pcl::PointXYZ>::Ptr pclApp::rootPcl2
Definition at line 89 of file pclApp.h.
Referenced by loadPlyTestPcl(), and testPclRgbObjectDetectionPipe01().
rootPcl3
pcl::PointCloud<pcl::PointXYZ>::Ptr pclApp::rootPcl3
Definition at line 92 of file pclApp.h.
Referenced by loadPlyTestPcl().
rootPclResult
pcl::PointCloud<pcl::PointXYZ>::Ptr pclApp::rootPclResult
Definition at line 94 of file pclApp.h.
Referenced by testPclRgbObjectDetectionPipe01().
rootPclResultSize
int pclApp::rootPclResultSize = 0 static
Definition at line 98 of file pclApp.h.
Referenced by testPclRgbObjectDetectionPipe01().
rootPclRgb
pcl::PointCloud<pcl::PointXYZRGB>::Ptr pclApp::rootPclRgb
Definition at line 87 of file pclApp.h.
Referenced by loadPlyTestPcl(), testPclRgbObjectDetectionPipe01(), testViewsWithNormals(), and testViewsWithViewports().
rootPclRgb2
pcl::PointCloud<pcl::PointXYZRGB>::Ptr pclApp::rootPclRgb2
Definition at line 90 of file pclApp.h.
Referenced by loadPlyTestPcl().
rootPclRgb2Full
pcl::PointCloud<pcl::PointXYZRGB>::Ptr pclApp::rootPclRgb2Full
Definition at line 91 of file pclApp.h.
Referenced by loadPlyTestPcl(), and testPclRgbObjectDetectionPipe01().
rootPclRgb3
pcl::PointCloud<pcl::PointXYZRGB>::Ptr pclApp::rootPclRgb3
Definition at line 93 of file pclApp.h.
Referenced by loadPlyTestPcl().
rootPclRgbFull
pcl::PointCloud<pcl::PointXYZRGB>::Ptr pclApp::rootPclRgbFull
Definition at line 88 of file pclApp.h.
Referenced by loadPlyTestPcl(), testPclRgbObjectDetectionPipe01(), and testTranformOrientationToPlane().
rootPclRgbResult
pcl::PointCloud<pcl::PointXYZRGB>::Ptr pclApp::rootPclRgbResult
Definition at line 95 of file pclApp.h.
Referenced by testPclRgbObjectDetectionPipe01().
rootPclRgbResultSize
int pclApp::rootPclRgbResultSize = 0 static
Definition at line 99 of file pclApp.h.
Referenced by testPclRgbObjectDetectionPipe01().
rootPclRgbSize
int pclApp::rootPclRgbSize = 0 static
Definition at line 97 of file pclApp.h.
Referenced by loadPlyTestPcl().
rootPclSize
int pclApp::rootPclSize = 0 static
Definition at line 96 of file pclApp.h.
Referenced by loadPlyTestPcl().
The documentation for this class was generated from the following files:
/media/hd2/dev/kinectV3/kv3Pcl/include/pclApp.h
/media/hd2/dev/kinectV3/kv3Pcl/src/pclApp.cpp