kv3_framework: /media/hd2/dev/kinectV3/kv3Pcl/src/kv3audio.cpp File Reference
kv3audio.cpp File Reference
Implementation of the class functions to access the kinect azure microphone audio data.
#include "kv3audio.h"
Variables
static snd_pcm_sframes_t(* readi_func)(snd_pcm_t *handle, void *buffer, snd_pcm_uframes_t size)
static snd_pcm_sframes_t(* writei_func)(snd_pcm_t *handle, const void *buffer, snd_pcm_uframes_t size)
static snd_pcm_sframes_t(* readn_func)(snd_pcm_t *handle, void **bufs, snd_pcm_uframes_t size)
static snd_pcm_sframes_t(* writen_func)(snd_pcm_t *handle, void **bufs, snd_pcm_uframes_t size)
Detailed Description
Implementation of the class functions to access the kinect azure microphone audio data.
created on: 09.02.2023; last update: 24.06.2023
Author
Jörg Angermayer
Copyright
Licensed under MIT
Definition in file kv3audio.cpp.
Variable Documentation
readi_func
snd_pcm_sframes_t(* readi_func) (snd_pcm_t *handle, void *buffer, snd_pcm_uframes_t size) static
Definition at line 21 of file kv3audio.cpp.
Referenced by kv3audio::pcm_read(), and kv3audio::run().
readn_func
snd_pcm_sframes_t(* readn_func) (snd_pcm_t *handle, void **bufs, snd_pcm_uframes_t size) static
Definition at line 23 of file kv3audio.cpp.
Referenced by kv3audio::run().
writei_func
snd_pcm_sframes_t(* writei_func) (snd_pcm_t *handle, const void *buffer, snd_pcm_uframes_t size) static
Definition at line 22 of file kv3audio.cpp.
Referenced by kv3audio::run().
writen_func
snd_pcm_sframes_t(* writen_func) (snd_pcm_t *handle, void **bufs, snd_pcm_uframes_t size) static
Definition at line 24 of file kv3audio.cpp.
Referenced by kv3audio::run().