kv3_framework: /media/hd2/dev/kinectV3/kv3Pcl/src/main.cpp File Reference
main.cpp File Reference
main to show how to use the kv3 class.
#include <iostream>
#include <thread>
#include "kv3.h"
#include "kv3odas.h"
#include "audioMeasurement.h"
#include "pclUtilitys.h"
#include "pclApp.h"
Functions
void addTextToImg (const cv::Mat &in, cv::Mat &out, kv3 &kv3AppObj)
addTextToImg
void showKv2Demo (kv3odas *kv3AppOdas, audioMeasurement *audioM)
void test (kv3 &kv3AppObj)
void * kv3Cam (void *ptr)
void kv3RunCam ()
void kv3RunOdasServer ()
void * kv3OdasServer (void *ptr)
void testSyncStart (kv3odas kv3AppOdas)
int main ()
Variables
static int counterAudio = 0
static pthread_t thrKv3Cam
static pthread_t thrOdas
Detailed Description
main to show how to use the kv3 class.
Copyright
Licensed under MIT
Author: Jörg Angermayer
created on: 09.02.2023
last update: 24.06.2023
Definition in file main.cpp.
Function Documentation
addTextToImg()
void addTextToImg (const cv::Mat & in, cv::Mat & out, kv3 & kv3AppObj)
addTextToImg
add sensor values (serial nummber, temperature from cam and IMU, gravity, accelaration) into the image
input: const cv::Mat (original image on which the text is to be written) kv3 &kv3AppObj (kv3 handle)
output: cv::Mat &out (original image with added text)
Definition at line 45 of file main.cpp.
{
         out = in.clone();
         float capTemperature;
         float imuTemperature;
         kv3AppObj.getCapTemperature(capTemperature);
         kv3AppObj.getImuTemperature(imuTemperature);
         float gravX;
         float gravY;
         float gravZ;
         kv3AppObj.getGravity(gravX, gravY, gravZ);
         float accX;
         float accY;
         float accZ;
         kv3AppObj.getIMU(accX, accY, accZ);
         int xOffset = (int)(26);
         int yOffset = (int)(26);
         const float fontScale = 0.5;
         const int txtOffset = 20;
         string strSerNr = "Serial Number: " + kv3AppObj.getSerialNumber();
         cv::putText(out,
             strSerNr, //text
             cv::Point(xOffset, yOffset),
             cv::FONT_HERSHEY_SIMPLEX,
             fontScale,
             CV_RGB(118, 185, 0),
             1);
         std::stringstream strStreamCapTemp;
         strStreamCapTemp << std::fixed << std::setprecision(1) << capTemperature;
         string strTempKv3 = "temp.kv3: " + strStreamCapTemp.str();//std::to_string(strStreamCapTemp);
         cv::putText(out,
             strTempKv3, //text
             cv::Point(xOffset, yOffset + 26),
             cv::FONT_HERSHEY_SIMPLEX,
             fontScale,
             CV_RGB(118, 185, 0),
             1);
         std::stringstream strStreamImuTemp;
         strStreamImuTemp << std::fixed << std::setprecision(1) << imuTemperature;
         string strTempImu = "temp.IMU: " + strStreamImuTemp.str();
         cv::putText(out,
             strTempImu, //text
             cv::Point(xOffset, yOffset + 26 + 26),
             cv::FONT_HERSHEY_SIMPLEX,
             fontScale,
             CV_RGB(118, 185, 0),
             1);
         //Gravity
         int gravOffset = yOffset + 26 + 26 + 26;
         std::stringstream strStreamGravX;
         strStreamGravX << std::fixed << std::setprecision(3) << gravX;
         string strGravX= "Gravity X: " + strStreamGravX.str();
         cv::putText(out,
             strGravX, //text
             cv::Point(xOffset, gravOffset),
             cv::FONT_HERSHEY_SIMPLEX,
             fontScale,
             CV_RGB(118, 185, 0),
             1);
         std::stringstream strStreamGravY;
         strStreamGravY << std::fixed << std::setprecision(3) << gravY;
         string strGravY= "Gravity Y: " + strStreamGravY.str();
         cv::putText(out,
             strGravY, //text
             cv::Point(xOffset, gravOffset + 26),
             cv::FONT_HERSHEY_SIMPLEX,
             fontScale,
             CV_RGB(118, 185, 0),
             1);
         std::stringstream strStreamGravZ;
         strStreamGravZ << std::fixed << std::setprecision(3) << gravZ;
         string strGravZ= "Gravity Z: " + strStreamGravZ.str();
         cv::putText(out,
             strGravZ, //text
             cv::Point(xOffset, gravOffset + 26 + 26),
             cv::FONT_HERSHEY_SIMPLEX,
             fontScale,
             CV_RGB(118, 185, 0),
             1);
         //IMU - ACC
         int accOffset = gravOffset + 26 + 26 + 26;
         std::stringstream strStreamAccX;
         strStreamAccX << std::fixed << std::setprecision(3) << accX;
         string strAccX = "IMU acc X: " + strStreamAccX.str();
         cv::putText(out,
             strAccX, //text
             cv::Point(xOffset, accOffset),
             cv::FONT_HERSHEY_SIMPLEX,
             fontScale,
             CV_RGB(118, 185, 0),
             1);
         std::stringstream strStreamAccY;
         strStreamAccY << std::fixed << std::setprecision(3) << accY;
         string strAccY = "IMU acc Y: " + strStreamAccY.str();
         cv::putText(out,
             strAccY, //text
             cv::Point(xOffset, accOffset + 26),
             cv::FONT_HERSHEY_SIMPLEX,
             fontScale,
             CV_RGB(118, 185, 0),
             1);
         std::stringstream strStreamAccZ;
         strStreamAccZ << std::fixed << std::setprecision(3) << accZ;
         string strAccZ = "IMU acc Z: " + strStreamAccZ.str();
         cv::putText(out,
             strAccZ, //text
             cv::Point(xOffset, accOffset + 26 + 26),
             cv::FONT_HERSHEY_SIMPLEX,
             fontScale,
             CV_RGB(118, 185, 0),
             1);
 }
References kv3::getCapTemperature(), kv3::getGravity(), kv3::getIMU(), kv3::getImuTemperature(), and kv3::getSerialNumber().
Referenced by showKv2Demo().
kv3Cam()
void* kv3Cam (void * ptr)
grab kv3 camera
Returns
void
Definition at line 371 of file main.cpp.
{
     kv3 kv3AppObj = kv3();
     kv3AppObj.setup();
     //kv3AppObj.testloop();
     while(1){
         kv3AppObj.update();
         test(kv3AppObj);
         char key = waitKey(10);
         if(key == 27){ break; }
     }
 }
References kv3::setup(), test(), and kv3::update().
kv3OdasServer()
void* kv3OdasServer (void * ptr)
create ODAS server function pointer
Returns
void
Definition at line 423 of file main.cpp.
{
     kv3odas *kv3AppOdasPtr;
     kv3AppOdasPtr = (kv3odas *)ptr;
     kv3AppOdasPtr->odasServer();
 }
References kv3odas::odasServer().
kv3RunCam()
void kv3RunCam ()
update kv3 data and use a function to show data inside windows
Returns
void
Definition at line 388 of file main.cpp.
                 {
     kv3 kv3AppObj = kv3();
     kv3AppObj.setup();
     while(1){
         kv3AppObj.update();
         test(kv3AppObj);
 /*
         float capTemperature;
         float imuTemperature;
         kv3AppObj.getCapTemperature(capTemperature);
         kv3AppObj.getImuTemperature(imuTemperature);
         cout << "capTemperature: " << capTemperature << " imuTemperature: " << imuTemperature << endl;
 */
         char key = waitKey(10);
         if(key == 27){ break; }
     }
 }
References kv3::setup(), test(), and kv3::update().
kv3RunOdasServer()
void kv3RunOdasServer ()
run ODAS server
Returns
void
Definition at line 413 of file main.cpp.
{
     kv3odas kv3AppOdas = kv3odas(9000);
     kv3AppOdas.odasServer();
 }
References kv3odas::odasServer().
main()
int main ()
main function
Returns
void
myPclUtilitysObj.viewer->wasStopped ()
Show
Definition at line 469 of file main.cpp.
            {
     cout << "main to show kv3 demo ..." << endl;
     static int masterCounter = 0;
     Mat cvDepthImg;
     pcl::PointCloud<pcl::PointXYZRGB>::Ptr updatedPcl;
     kv3 kv3AppObj = kv3();
     kv3AppObj.setup();
     pclApp myPclApp = pclApp();
     pclUtilitys myPclUtilitysObj = pclUtilitys();
     string strWin03 = string("PointCloud image - CV_32FC3 - 21");
     while(1){
         kv3AppObj.update();
         //kv3AppObj.getCvRegDepthImg(cvDepthImg);
         //kv3AppObj.getCvDepthImg(cvDepthImg);
         //imshow("cvDepthImg", cvDepthImg);
     /*
         if(cvDepthImg.empty() == false){
             kv3AppObj.getCvRegDepthImg(cvDepthImg);
             myPclApp.convMatPclToPCL(cvDepthImg, updatedPcl, cvDepthImg.size().width, cvDepthImg.size().height);
             if(updatedPcl != nullptr){
                 //myPclUtilitysObj.rgbVis(updatedPcl);
                 myPclUtilitysObj.viewer = myPclUtilitysObj.rgbVis(updatedPcl);
                 myPclUtilitysObj.viewer->spinOnce(1);
                 std::this_thread::sleep_for(33ms);
             }
         }
     */
         Mat colorImg;
         Mat regDepth;
         Mat depth;
         Mat irImg;
         kv3AppObj.getCvColorImg(colorImg);
         kv3AppObj.getCvDepthImg(depth);
         kv3AppObj.getCvRegDepthImg(regDepth);
         kv3AppObj.getCvIrImg(irImg);
         //Mat resIrImg = irImg.clone();
         Mat resizeImgColor = colorImg.clone();
         Mat resizeImgColorDepth = depth.clone();
         Mat resizeImgDepth = depth.clone();
         Mat resizeImgIr = irImg.clone();
         int widthOfPcl = 512;  //640
         int heigthOfPcl = 0; //576
         //Color image - ok
         kv3AppObj.resizeKv3Img(resizeImgColor, resizeImgColorDepth,  widthOfPcl, 0);
         //IR image - ok
         //kv3AppObj.resizeKv3Img(resizeImgIr, resizeImgDepth,  widthOfPcl, 0); // wrong calibration
         imshow("resizeImgColor", resizeImgColor);
         //imshow("resIrImgRgb", resizeImgIr);
         int point_count = 0;
         //kv3AppObj.generate_point_cloud(&point_count); //OK  -- for higher accuracy of depth values via MS
 /*
         float capTemperature;
         float imuTemperature;
         kv3AppObj.getCapTemperature(capTemperature);
         kv3AppObj.getImuTemperature(imuTemperature);
         cout << "capTemperature: " << capTemperature << " imuTemperature: " << imuTemperature << endl;
 */
         char key = waitKey(1);
         if(key == 27){
             cv::destroyWindow( strWin03 );
             break; }
         if(key == 's'){
             masterCounter++;
             string strNum = to_string(masterCounter);
             string strFilePath0 = string("/var/www/ramdev/kv3_CV2_PCL_color_") + strNum + string(".ply");
             string strFilePath1 = string("/var/www/ramdev/kv3_CV2_PCL_color_big_") + strNum + string(".ply");
             string strFilePath2 = string("/var/www/ramdev/kv3_MS_gen_PCL_") + strNum + string(".ply");
             string strFilePath3 = string("/var/www/ramdev/kv3_MS_gen_PCL_Color_") + strNum + string(".ply");
             string strFilePath4 = string("/var/www/ramdev/kv3_MS_PCL_color_") + strNum + string(".ply");
             //Color ok - smaller because resized
             Mat kv3PclColor;
             kv3AppObj.calcCvPclCamResize(resizeImgColorDepth, kv3PclColor, widthOfPcl, 0, true);
             cv::viz::writeCloud(strFilePath0, kv3PclColor, resizeImgColor);
             //ok - but big, but nice mapping
             Mat kv3PclColorBig;
             kv3AppObj.calcCvPclCamColor(regDepth, kv3PclColorBig);
             cv::viz::writeCloud(strFilePath1, kv3PclColorBig, colorImg);
 /*
             // IR - ok - but wrong calibration
             masterCounter++;
             string strNumIr = to_string(masterCounter);
             string strFilePathIr = string("/var/www/ramdev/kv3Ir_") + strNumIr + string(".ply");
             //IR
             Mat kv3PclIr;
             kv3AppObj.calcCvPclCamResize(resizeImgDepth, kv3PclIr, widthOfPcl, 0, false);
             Mat visIrImg;
             kv3AppObj.convIrToVisible8BitGrayImg(resizeImgIr, visIrImg);
             Mat resIrImgRgb;
             cvtColor(visIrImg, resIrImgRgb, cv::COLOR_GRAY2RGB);
             cv::viz::writeCloud(strFilePathIr, kv3PclIr, resIrImgRgb);
 */
             //cv::destroyWindow( strWin03 );
             //break;
             kv3AppObj.writePCL(strFilePath2.c_str());   //Ok PCL , no color but gen depth fix
             kv3AppObj.writeColorPcl1(strFilePath3.c_str()); // ok, but color doesn't map nice, used MS gen fixed PCL data and map the color, only
             kv3AppObj.writeColorPcl2(strFilePath4.c_str()); // ok, but color doesn't map nice
             //kv3AppObj.writeColorPcl3("/var/www/ramdev/testColor3.ply", point_count);// nok
          }
     }//end while
     //  cd /media/hd2/git_pool_hd2/ODASpool/odas/build/bin
     //  sudo ./odaslive -vc /media/hd2/git_pool_hd2/ODASpool/odas/config/odaslive/kv3Socket.cfg
     //kv3RunCam();
 /*
     kv3odas kv3AppOdas = kv3odas(9000);
     pthread_create(&thrOdas, NULL, kv3OdasServer, (kv3odas *)&kv3AppOdas);
     kv3AppOdas.startOdasLive();
 */
     //audioMeasurement audioM = audioMeasurement();
     //showKv2Demo(&kv3AppOdas, &audioM);
     //showKv2Demo(nullptr, &audioM);
     //showKv2Demo(&kv3AppOdas, nullptr);
     return 0;
 }
References kv3::calcCvPclCamColor(), kv3::calcCvPclCamResize(), kv3::getCvColorImg(), kv3::getCvDepthImg(), kv3::getCvIrImg(), kv3::getCvRegDepthImg(), kv3::resizeKv3Img(), kv3::setup(), kv3::update(), kv3::writeColorPcl1(), kv3::writeColorPcl2(), and kv3::writePCL().
showKv2Demo()
void showKv2Demo (kv3odas * kv3AppOdas, audioMeasurement * audioM)
show image windows with kinect v3 data, audio data and ODAS data input:
Parameters
kv3odas object audioMeasurement object
Returns
void
Definition at line 174 of file main.cpp.
{
     //kv3audiovisu kv3AppAudiovisuObj = kv3audiovisu();
     //AudioMeasurement
     string strWin05 = string("Audio Measurement");
     //ODAS
     int idx;
     float x, y, z, len;
     string strWin04 = string("ODAS - Open embeddeD Audio System");
     //kv3
     string strWin01 = string("Resized and registered color and depth image - CV_8UC4 - 24");
     string strWin02 = string("Original Ir(left) and depth(right) image - CV_16UC1 - 2");
     string strWin03 = string("PointCloud image - CV_32FC3 - 21");
     float factor = 1.4;
     int w = round(640/factor);
     int h = round(576/factor);
     int h2 = 0;
         Mat colorImg;
         Mat irImg;
         Mat depthImg;
         Mat regDepth;
         Mat kv3PCL;
         Mat audioMimg;
     int winx1 = 0;
     int winy1 = 0;
     kv3 kv3AppObj = kv3();
     kv3AppObj.setup();
     /*
     std::string strHwVersion = kv3AppObj.getHardwareVersion();
     cout << " ---- --- -- Kinect Azure hardware version -- --- ----" << endl;
     cout << strHwVersion << endl;
     cout << " ---- --- -- - -- --- ----" << endl;
     */
     cout << "start update loop" << endl;
     Mat win02(h, w*2, CV_16UC1, Scalar(0,0,0));
     while(1){
         if(audioM != nullptr){
             audioM->update();
             audioMimg = audioM->getMeasurementImage();
         }
         kv3AppObj.update();
         kv3AppObj.getCvColorImg(colorImg);
         kv3AppObj.getCvIrImg(irImg);
         kv3AppObj.getCvDepthImg(depthImg);
         kv3AppObj.getCvRegDepthImg(regDepth);
         //kv3AppObj.calcCvPcl(regDepth, kv3PCL);
         kv3AppObj.resizeImg(colorImg, w, 0);
         kv3AppObj.resizeImg(regDepth, w, 0);
         h2 = colorImg.size().height;
         Mat win01(h2, w*2, CV_8UC4, Scalar(0,0,0));
         kv3AppObj.resizeImg(irImg, w, h);
         kv3AppObj.resizeImg(depthImg, w, h);
         kv3AppObj.resizeImg(kv3PCL, w, h2);
         kv3AppObj.convToVisibleImg(regDepth, regDepth);
         kv3AppObj.convIrToVisibleImg(irImg, irImg);
         kv3AppObj.convToVisibleImg(depthImg, depthImg);
         //cout << "colorImg.type: " << colorImg.type() << endl;
         //cout << "irImg.type: " << irImg.type() << endl;
         //cout << "depthImg.type: " << depthImg.type() << endl;
         //cout << "regDepth.type: " << regDepth.type() << endl;
         //cout << "kv3PCL type: " << kv3PCL.type() << endl;
     cv::namedWindow( strWin01, cv::WINDOW_AUTOSIZE|cv::WINDOW_GUI_NORMAL);
     cv::namedWindow( strWin02, cv::WINDOW_AUTOSIZE|cv::WINDOW_GUI_NORMAL);
     cv::namedWindow( strWin03, cv::WINDOW_AUTOSIZE|cv::WINDOW_GUI_NORMAL);
     if(kv3AppOdas != nullptr){
         cv::namedWindow( strWin04, cv::WINDOW_AUTOSIZE|cv::WINDOW_GUI_NORMAL);
     }
     if(audioM != nullptr){
         cv::namedWindow( strWin05, cv::WINDOW_AUTOSIZE|cv::WINDOW_GUI_NORMAL);
     }
         //win 01
         Mat regDepth8UC4;
         regDepth.convertTo(regDepth8UC4, CV_8UC4, 1.0 / 255.0, 0.0);
         cvtColor(regDepth8UC4, regDepth8UC4, cv::COLOR_RGB2RGBA);
         addTextToImg(regDepth8UC4, regDepth8UC4, kv3AppObj);
         regDepth8UC4.copyTo(win01(Rect(w, 0, regDepth8UC4.size().width, h2)));
         Mat colorImg2;
         cvtColor(colorImg, colorImg2, cv::COLOR_RGB2RGBA);
         colorImg.copyTo(win01(Rect(0, 0, colorImg.size().width, h2)));
         //win 02
         imshow(strWin01,win01);
         moveWindow(strWin01, 0, 0);
         irImg.copyTo(win02(Rect(0, 0, irImg.size().width, irImg.size().height)));
         depthImg.copyTo(win02(Rect(w, 0, depthImg.size().width, depthImg.size().height)));
         imshow(strWin02,win02);
         moveWindow(strWin02, 0, win01.size().height+64);
         //win 03
         imshow(strWin03, kv3PCL);
         moveWindow(strWin03, w+w+72, 0);
         //ODAS
         if(kv3AppOdas != nullptr){
             kv3AppOdas->getNearesSoundObj(idx, x, y, z, len);
             Mat trImg = kv3AppOdas->drawOdasTrackingData(idx, x, y, z);
             imshow(strWin04,trImg);
             moveWindow(strWin04, w+w+72, win01.size().height+64);
         }
         //Audio Measurement
         if(audioM != nullptr){
             imshow(strWin05, audioMimg);
             moveWindow(strWin05, 0, h2+win02.size().height+64+64);
         }
         char key = waitKey(10);
         if(key == 27){
             cv::destroyWindow( strWin01 );
             cv::destroyWindow( strWin02 );
             cv::destroyWindow( strWin03 );
             if(kv3AppOdas != nullptr){
                 cv::destroyWindow( strWin04 );
             }
             if(audioM != nullptr){
                 cv::destroyWindow( strWin05 );
             }
             break; }
     }
 }
References addTextToImg(), kv3::convIrToVisibleImg(), kv3::convToVisibleImg(), kv3odas::drawOdasTrackingData(), kv3::getCvColorImg(), kv3::getCvDepthImg(), kv3::getCvIrImg(), kv3::getCvRegDepthImg(), audioMeasurement::getMeasurementImage(), kv3odas::getNearesSoundObj(), kv3::resizeImg(), kv3::setup(), audioMeasurement::update(), kv3::update(), and z.
test()
void test (kv3 & kv3AppObj)
test crop image input:
Parameters
kv3 object
Returns
void
Definition at line 319 of file main.cpp.
{
     Mat cropImgColor;
     Mat cropImgIr;
     Mat cropImgDepth;
     Mat resizeImgColor;
     Mat resizeImgDepth;
     /*
     //Ok worked
     Mat origColor;
     kv3AppObj.getCvColorImg(origColor);
     imshow("origColor", origColor);
     kv3AppObj.cropKv3Img(cropImgColor, cropImgDepth, 360, 360);
     imshow("cropImg", cropImgColor);
     imshow("cropImgDepth", cropImgDepth);
     */
     /*
     //Ok worked
     kv3AppObj.resizeKv3Img(resizeImgColor, resizeImgDepth,  400, 0);
     imshow("resizeImg", resizeImgColor);
     imshow("resizeImgDepth", resizeImgDepth);
     */
     Mat conCropImgIr;
     Mat conCropImg8Ir;
     kv3AppObj.getCvIrImg(cropImgIr);
     if(cropImgIr.empty() == false){
         kv3AppObj.convIrToVisibleImg(cropImgIr, conCropImgIr);
         if(conCropImgIr.empty() == false){
             imshow("conCropImgIr", conCropImgIr);
         }else{
             cout << "conCropImgIr is empty..." << endl;
         }
         kv3AppObj.convIrToVisible8BitGrayImg(cropImgIr, conCropImg8Ir);
         if(conCropImg8Ir.empty() == false){
             imshow("conCropImg8Ir", conCropImg8Ir);
         }else{
             cout << "conCropImg8Ir is empty..." << endl;
         }
     }else{
         cout << "cropImgIr is empty..." << endl;
     }
 }
References kv3::convIrToVisible8BitGrayImg(), kv3::convIrToVisibleImg(), and kv3::getCvIrImg().
Referenced by kv3Cam(), kv3RunCam(), and testSyncStart().
testSyncStart()
void testSyncStart (kv3odas kv3AppOdas)
test sync between kv3 image data and ODAS data input:
Parameters
kv3odas object
Returns
void
Definition at line 437 of file main.cpp.
{
     kv3audiovisu kv3AppAudiovisuObj = kv3audiovisu();
     int idx;
     float x;
     float y;
     float z;
     float len;
     kv3 kv3AppObj = kv3();
     kv3AppObj.setup();
     while(1){
         kv3AppObj.update();
             kv3AppOdas.getNearesSoundObj(idx, x, y, z, len);
             //cout << "idx: " << idx << " x: " << x << " y: " << y << " z: " << z << " len: " << len << endl;
             Mat trImg = kv3AppAudiovisuObj.drawOdasTrackingData(idx, x, y, z);
             imshow("trImg",trImg);
         test(kv3AppObj);
         //float capTemperature;
         //kv3AppObj.getCapTemperature(capTemperature);
         //cout << "capTemperature: " << capTemperature << endl;
         char key = waitKey(10);
         if(key == 27){ break; }
     }
 }
References kv3audiovisu::drawOdasTrackingData(), kv3odas::getNearesSoundObj(), kv3::setup(), test(), kv3::update(), and z.
Variable Documentation
counterAudio
int counterAudio = 0 static
Definition at line 32 of file main.cpp.
thrKv3Cam
pthread_t thrKv3Cam static
Definition at line 35 of file main.cpp.
thrOdas
pthread_t thrOdas static
Definition at line 36 of file main.cpp.