kv3_framework: fmt_capture Struct Reference
fmt_capture Struct Reference
#include "kv3audio.h"
Public Attributes
void(* start)(int fd, size_t count)
void(* end)(int fd)
char * what
long long max_filesize
Detailed Description
Definition at line 291 of file kv3audio.h.
Member Data Documentation
end
void(* fmt_capture::end) (int fd)
Definition at line 293 of file kv3audio.h.
Referenced by kv3audio::capture(), and kv3audio::run().
max_filesize
long long fmt_capture::max_filesize
Definition at line 295 of file kv3audio.h.
Referenced by kv3audio::capture().
start
void(* fmt_capture::start) (int fd, size_t count)
Definition at line 292 of file kv3audio.h.
Referenced by kv3audio::capture().
what
char* fmt_capture::what
Definition at line 294 of file kv3audio.h.
The documentation for this struct was generated from the following file:
/media/hd2/dev/kinectV3/kv3Pcl/include/kv3audio.h