kv3_framework: k4a::Vector Struct Reference
k4a::Vector Struct Reference
#include "Vector.h"
Public Member Functions
Vector ()
Vector (float x, float y, float z)
Vector (const k4a_float3_t &v)
float Dot (const Vector &other) const
float SquareLength () const
float Length () const
Vector operator* (float c) const
Vector operator/ (float c) const
Vector Normalized () const
float Angle (const Vector &other) const
Public Attributes
float X
float Y
float Z
Detailed Description
Definition at line 42 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/3]
k4a::Vector::Vector () inline
Definition at line 48 of file Vector.h.
         {
         }
Vector() [2/3]
k4a::Vector::Vector (float x, float y, float z) inline
Definition at line 52 of file Vector.h.
                 : X(x)
                 , Y(y)
                 , Z(z)
         {
         }
Vector() [3/3]
k4a::Vector::Vector (const k4a_float3_t & v) inline
Definition at line 59 of file Vector.h.
                 : X(v.xyz.x)
                 , Y(v.xyz.y)
                 , Z(v.xyz.z)
         {
         }
Member Function Documentation
Angle()
float k4a::Vector::Angle (const Vector & other) const inline
Definition at line 96 of file Vector.h.
         {
             return std::acos(Dot(other) / Length() / other.Length());
         }
References Dot(), and Length().
Dot()
float k4a::Vector::Dot (const Vector & other) const inline
Definition at line 66 of file Vector.h.
         {
             return X * other.X + Y * other.Y + Z * other.Z;
         }
References X, Y, and Z.
Referenced by Angle(), and kv3::extract_gravity_from_imu().
Length()
float k4a::Vector::Length () const inline
Definition at line 76 of file Vector.h.
         {
             return std::sqrt(SquareLength());
         }
References SquareLength().
Referenced by Angle(), and Normalized().
Normalized()
Vector k4a::Vector::Normalized () const inline
Definition at line 91 of file Vector.h.
         {
             return *this / Length();
         }
References Length().
Referenced by kv3::extract_gravity_from_imu().
operator*()
Vector k4a::Vector::operator* (float c) const inline
Definition at line 81 of file Vector.h.
         {
             return { X * c, Y * c, Z * c };
         }
References X, Y, and Z.
operator/()
Vector k4a::Vector::operator/ (float c) const inline
Definition at line 86 of file Vector.h.
         {
             return *this * (1 / c);
         }
SquareLength()
float k4a::Vector::SquareLength () const inline
Definition at line 71 of file Vector.h.
         {
             return X * X + Y * Y + Z * Z;
         }
References X, Y, and Z.
Referenced by Length().
Member Data Documentation
X
float k4a::Vector::X
Definition at line 44 of file Vector.h.
Referenced by Dot(), kv3::getGravity(), kv3::getIMU(), operator*(), and SquareLength().
Y
float k4a::Vector::Y
Definition at line 45 of file Vector.h.
Referenced by Dot(), kv3::getGravity(), kv3::getIMU(), operator*(), and SquareLength().
Z
float k4a::Vector::Z
Definition at line 46 of file Vector.h.
Referenced by Dot(), kv3::getGravity(), kv3::getIMU(), operator*(), and SquareLength().
The documentation for this struct was generated from the following file:
/media/hd2/dev/kinectV3/kv3Pcl/include/Vector.h